slogo_team13: View.MenuTemplate Class Reference
View.MenuTemplate Class Reference
Public Member Functions
MenuTemplate (String s)
void addMenuItem (String name, EventHandler< ActionEvent > handler)
void addEvent (EventHandler< ActionEvent > handler)
Detailed Description
Definition at line 8 of file MenuTemplate.java.
Constructor & Destructor Documentation
View.MenuTemplate.MenuTemplate (String s)
Constructor
Parameters
s String representing the title of the Menu
handler Event for which the Menu reacts upon
Definition at line 15 of file MenuTemplate.java.
Member Function Documentation
void View.MenuTemplate.addEvent (EventHandler< ActionEvent > handler)
Creates an object on the GUI that the user can interact with
Parameters
handler ActionEvent for the object to react to
Implements View.UserObjects.
Definition at line 25 of file MenuTemplate.java.
void View.MenuTemplate.addMenuItem (String name, EventHandler< ActionEvent > handler)
Definition at line 19 of file MenuTemplate.java.
Referenced by View.SlogoView.addMenuBar(), View.SlogoView.createfileMenu(), View.SlogoView.makeAddMenu(), View.SlogoView.makeLanguageMenu(), View.SlogoView.makeMenu(), and View.SlogoView.makeUserCommand().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/View/MenuTemplate.java