slogo_team13: commands.turtleCommands.TurtleCommand Class Reference
commands.turtleCommands.TurtleCommand Class Reference abstract
Public Member Functions
TurtleCommand (String userInput, boolean isExpression) throws BackendException
Set< Class<?extends IInformationContainer > > getRequiredInformationTypes ()
void setRequiredInformation (Collection< IInformationContainer > containers)
Public Member Functions inherited from commands.BaseCommand
BaseCommand (String userInput, boolean isExpression) throws BackendException
double execute () throws BackendException
abstract Set< Class<?extends IInformationContainer > > getRequiredInformationTypes ()
abstract void setRequiredInformation (Collection< IInformationContainer > containers) throws BackendException
String getLeftoverString ()
Protected Member Functions
BaseTurtleContainer getTurtleContainer ()
BaseGridContainer getGridContainer ()
void parseArguments (String userInput) throws BackendException
BaseCommand[] getExpressionList ()
abstract int getArgumentCount ()
void reset ()
Protected Member Functions inherited from commands.BaseCommand
abstract double onExecute () throws BackendException
abstract void parseArguments (String userInput) throws BackendException
void setLeftoverCommands (String string) throws BackendException
String[] splitByInnerListCommand (String input)
boolean startsWithCommandStartIndicator (String input)
abstract void reset ()
Private Attributes
BaseCommand[] myArgumentList
BaseGridContainer myGridContainer
BaseTurtleContainer myTurtleContainer
Static Private Attributes
static final String INSUFFICIENT_ARGUMENTS_PROVIDED = "Insufficient arguments provided"
static final int NUM_TURTLE_CONTAINERS = 2
Additional Inherited Members
Protected Attributes inherited from commands.BaseCommand
final String COMMAND_DELIMITER = "\\s+"
Static Protected Attributes inherited from commands.BaseCommand
static String COMMAND_INDICATOR = "liststart"
static String COMMAND_END_INDICATOR = "listend"
static String COMMAND_SEPARATOR = " "
static String VARIABLE_INDICATOR = "variable"
Detailed Description
Author
Rahul Harikrishnan, Duke Kim, $cotty $haw
Definition at line 18 of file TurtleCommand.java.
Constructor & Destructor Documentation
commands.turtleCommands.TurtleCommand.TurtleCommand (String userInput, boolean isExpression) throws BackendException
Definition at line 25 of file TurtleCommand.java.
Member Function Documentation
abstract int commands.turtleCommands.TurtleCommand.getArgumentCount () abstract protected
Referenced by commands.turtleCommands.TurtleCommand.parseArguments().
BaseCommand [] commands.turtleCommands.TurtleCommand.getExpressionList () protected
Definition at line 89 of file TurtleCommand.java.
References commands.turtleCommands.TurtleCommand.myArgumentList.
Referenced by commands.turtleCommands.BackCommand.onExecute(), commands.turtleCommands.ForwardCommand.onExecute(), commands.turtleCommands.RightCommand.onExecute(), commands.turtleCommands.SetHeadingCommand.onExecute(), commands.turtleCommands.LeftCommand.onExecute(), commands.turtleCommands.TowardsCommand.onExecute(), and commands.turtleCommands.SetPositionCommand.onExecute().
BaseGridContainer commands.turtleCommands.TurtleCommand.getGridContainer () protected
Definition at line 60 of file TurtleCommand.java.
References commands.turtleCommands.TurtleCommand.myGridContainer.
Referenced by commands.turtleCommands.MultipleTurtleCommand.addFutureActiveTurtleTurtles(), commands.turtleCommands.BackCommand.onExecute(), commands.turtleCommands.LeftCommand.onExecute(), commands.turtleCommands.RightCommand.onExecute(), commands.turtleCommands.ForwardCommand.onExecute(), commands.turtleCommands.SetHeadingCommand.onExecute(), commands.viewCommands.ClearScreenCommand.onExecute(), commands.turtleCommands.TowardsCommand.onExecute(), commands.turtleCommands.SetPositionCommand.onExecute(), and commands.viewCommands.HomeCommand.onExecute().
Set<Class<? extends IInformationContainer> > commands.turtleCommands.TurtleCommand.getRequiredInformationTypes ()
Definition at line 30 of file TurtleCommand.java.
BaseTurtleContainer commands.turtleCommands.TurtleCommand.getTurtleContainer () protected
Definition at line 56 of file TurtleCommand.java.
References commands.turtleCommands.TurtleCommand.myTurtleContainer.
Referenced by commands.turtleCommands.MultipleTurtleCommand.addFutureActiveTurtleTurtles(), commands.viewQueries.YCorQuery.onExecute(), commands.viewQueries.XCorQuery.onExecute(), commands.turtleCommands.BackCommand.onExecute(), commands.turtleCommands.NumberOfTurtlesCommand.onExecute(), commands.viewQueries.HeadingQuery.onExecute(), commands.turtleCommands.RightCommand.onExecute(), commands.turtleCommands.ForwardCommand.onExecute(), commands.turtleCommands.SetHeadingCommand.onExecute(), commands.turtleCommands.LeftCommand.onExecute(), commands.viewCommands.HideTurtleCommand.onExecute(), commands.viewCommands.ShowTurtleCommand.onExecute(), commands.turtleCommands.IDCommand.onExecute(), commands.viewCommands.ClearScreenCommand.onExecute(), commands.turtleCommands.TowardsCommand.onExecute(), commands.turtleCommands.SetPositionCommand.onExecute(), commands.turtleCommands.AskCommand.onExecute(), commands.viewCommands.HomeCommand.onExecute(), and commands.turtleCommands.AskWithCommand.onExecute().
void commands.turtleCommands.TurtleCommand.parseArguments (String userInput) throws BackendException protected
Definition at line 65 of file TurtleCommand.java.
References commandParser.CommandFactory.createCommand(), commands.turtleCommands.TurtleCommand.getArgumentCount(), commands.BaseCommand.getLeftoverString(), and commands.BaseCommand.setLeftoverCommands().
void commands.turtleCommands.TurtleCommand.reset () protected
Definition at line 96 of file TurtleCommand.java.
void commands.turtleCommands.TurtleCommand.setRequiredInformation (Collection< IInformationContainer > containers)
Definition at line 38 of file TurtleCommand.java.
References commands.turtleCommands.TurtleCommand.NUM_TURTLE_CONTAINERS.
Member Data Documentation
final String commands.turtleCommands.TurtleCommand.INSUFFICIENT_ARGUMENTS_PROVIDED = "Insufficient arguments provided" static private
Definition at line 19 of file TurtleCommand.java.
BaseCommand [] commands.turtleCommands.TurtleCommand.myArgumentList private
Definition at line 21 of file TurtleCommand.java.
Referenced by commands.turtleCommands.TurtleCommand.getExpressionList().
BaseGridContainer commands.turtleCommands.TurtleCommand.myGridContainer private
Definition at line 22 of file TurtleCommand.java.
Referenced by commands.turtleCommands.TurtleCommand.getGridContainer().
BaseTurtleContainer commands.turtleCommands.TurtleCommand.myTurtleContainer private
Definition at line 23 of file TurtleCommand.java.
Referenced by commands.turtleCommands.TurtleCommand.getTurtleContainer().
final int commands.turtleCommands.TurtleCommand.NUM_TURTLE_CONTAINERS = 2 static private
Definition at line 20 of file TurtleCommand.java.
Referenced by commands.turtleCommands.TurtleCommand.setRequiredInformation().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/commands/turtleCommands/TurtleCommand.java