slogo_team13: GUIFunctions.StampImage Class Reference
GUIFunctions.StampImage Class Reference
Public Member Functions
StampImage (Turtle myTurtle)
Private Member Functions
void addEffect ()
Detailed Description
Definition at line 8 of file StampImage.java.
Constructor & Destructor Documentation
GUIFunctions.StampImage.StampImage (Turtle myTurtle)
Definition at line 9 of file StampImage.java.
References GUIFunctions.StampImage.addEffect(), turtle.Turtle.getXPos(), and turtle.Turtle.getYPos().
Member Function Documentation
void GUIFunctions.StampImage.addEffect () private
Definition at line 19 of file StampImage.java.
Referenced by GUIFunctions.StampImage.StampImage().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/GUIFunctions/StampImage.java