slogo_team13: communicator.MainController Class Reference
communicator.MainController Class Reference
Public Member Functions
MainController (SlogoView view)
void receiveCommand (String enteredText)
void start ()
void pause (int x, int y)
void stop ()
void loadLanguage (File file)
List< Turtle > getActiveTurtles ()
void addTurtle (Turtle turtle, int gridID, boolean isActive)
void addGrid (Grid grid, boolean isActive)
void setGridAsActive (int gridID)
IInformationContainer loadPreferences (File file) throws BackendException
void savePreferences (IInformationContainer container, String filename) throws BackendException
void savePreferences (String filename) throws BackendException
void setTurtleAsActive (int turtleID)
Public Member Functions inherited from communicator.BaseController
BaseController (SlogoView view)
abstract void receiveCommand (String enteredText)
abstract void pause (int x, int y)
abstract void stop ()
abstract void start ()
abstract void loadLanguage (File file)
abstract void addTurtle (Turtle turtle, int gridID, boolean isActive)
abstract void addGrid (Grid grid, boolean isActive)
abstract List< Turtle > getActiveTurtles ()
abstract IInformationContainer loadPreferences (File file) throws BackendException
abstract void savePreferences (IInformationContainer container, String filename) throws BackendException
abstract void setGridAsActive (int gridID)
abstract void setTurtleAsActive (int turtleID)
Protected Member Functions
void reportErrorToView (Exception ex)
Protected Member Functions inherited from communicator.BaseController
abstract void reportErrorToView (Exception ex)
Private Member Functions
void setTimers ()
void executeCommand (BaseCommand command)
void sendUserDefinedVariablesAndCommands ()
BaseTurtleContainer getTurtleContainer ()
BaseGridContainer getGridContainer ()
Private Attributes
SlogoView myView
ConcurrentLinkedQueue< BaseCommand > myCommandQueue
ConcurrentLinkedQueue< String > myInputsToParse
AtomicBoolean myCommandIsExecuting
Collection< BaseCommand > myExecutedCommands
AnimationTimer myCommandExecutionTimer
AnimationTimer myCommandParserTimer
LanguageFileParser myTranslator
CommandToClassTranslator myCommandToClassTranslator
IInformationGateway myInformationGateway
Static Private Attributes
static final String ERROR_READING_FROM_FILE = "Error reading from file"
static final String ERROR_WRITING_TO_FILE = "Error writing to file"
static final String DEFAULT_ENGLISH_FILE = "src/resources/languages/English.properties"
static final String ENGLISH_TO_CLASS_FILE = "src/resources/languages/EnglishToClassName.properties"
Detailed Description
Author
Duke, Rahul This class is an implementation of the BaseController designed for asynchronous execution using animation timelines. BaseController is responsible for ensuring that the different containers are correctly updated when such information can be provided via the view. It handles error processing and reporting to the View, as well as provides implementation details for user to load and save functions/variables using Serializable.
Definition at line 41 of file MainController.java.
Constructor & Destructor Documentation
communicator.MainController.MainController (SlogoView view)
Definition at line 59 of file MainController.java.
References communicator.MainController.reportErrorToView(), commandParser.CommandFactory.setCommandToClassRelation(), commandParser.CommandFactory.setInformationGateway(), and communicator.MainController.setTimers().
Member Function Documentation
void communicator.MainController.addGrid (Grid grid, boolean isActive)
Definition at line 203 of file MainController.java.
References commands.information.BaseGridContainer.addGrid(), and communicator.MainController.getGridContainer().
Referenced by View.SlogoView.addGrid().
void communicator.MainController.addTurtle (Turtle turtle, int gridID, boolean isActive)
Definition at line 197 of file MainController.java.
References commands.information.BaseTurtleContainer.addTurtle(), and communicator.MainController.getTurtleContainer().
Referenced by View.SlogoView.addTurtle().
void communicator.MainController.executeCommand (BaseCommand command) private
Definition at line 147 of file MainController.java.
References commands.BaseCommand.execute(), communicator.MainController.reportErrorToView(), communicator.MainController.sendUserDefinedVariablesAndCommands(), and View.SlogoView.setDisable().
Referenced by communicator.MainController.setTimers().
List<Turtle> communicator.MainController.getActiveTurtles ()
Definition at line 191 of file MainController.java.
References commands.information.BaseTurtleContainer.getActiveTurtles(), and communicator.MainController.getTurtleContainer().
BaseGridContainer communicator.MainController.getGridContainer () private
Definition at line 219 of file MainController.java.
Referenced by communicator.MainController.addGrid(), and communicator.MainController.setGridAsActive().
BaseTurtleContainer communicator.MainController.getTurtleContainer () private
Definition at line 214 of file MainController.java.
References commands.information.IInformationGateway.getContainer().
Referenced by communicator.MainController.addTurtle(), and communicator.MainController.getActiveTurtles().
void communicator.MainController.loadLanguage (File file)
Definition at line 183 of file MainController.java.
References commandParser.LanguageFileParser.extractFromLanguageFile(), and communicator.MainController.reportErrorToView().
IInformationContainer communicator.MainController.loadPreferences (File file) throws BackendException
Definition at line 226 of file MainController.java.
References commands.information.IInformationGateway.addContainer(), and communicator.MainController.reportErrorToView().
Referenced by View.SlogoView.checkNullFile().
void communicator.MainController.pause (int x, int y)
Definition at line 135 of file MainController.java.
void communicator.MainController.receiveCommand (String enteredText)
Definition at line 116 of file MainController.java.
References communicator.MainController.reportErrorToView(), View.SlogoView.setDisable(), and commandParser.LanguageFileParser.translateUserInputIntoEnglish().
Referenced by View.SlogoView.executeUserCommand(), and View.SlogoView.sendCommandAndMakeButton().
void communicator.MainController.reportErrorToView (Exception ex) protected
Definition at line 178 of file MainController.java.
References View.SlogoView.showError().
Referenced by communicator.MainController.executeCommand(), communicator.MainController.loadLanguage(), communicator.MainController.loadPreferences(), communicator.MainController.MainController(), communicator.MainController.receiveCommand(), communicator.MainController.savePreferences(), communicator.MainController.sendUserDefinedVariablesAndCommands(), and communicator.MainController.setTimers().
void communicator.MainController.savePreferences (IInformationContainer container, String filename) throws BackendException
Definition at line 245 of file MainController.java.
References communicator.MainController.reportErrorToView().
Referenced by View.SlogoView.saveFileToController(), and communicator.MainController.savePreferences().
void communicator.MainController.savePreferences (String filename) throws BackendException
Definition at line 259 of file MainController.java.
References communicator.MainController.savePreferences().
void communicator.MainController.sendUserDefinedVariablesAndCommands () private
Definition at line 161 of file MainController.java.
References View.SlogoView.addUserFunctions(), View.SlogoView.addVariables(), commands.information.BaseUserDefinedContainer.getAllCustomCommands(), commands.information.BaseUserDefinedContainer.getAllVariablesAndValues(), and communicator.MainController.reportErrorToView().
Referenced by communicator.MainController.executeCommand().
void communicator.MainController.setGridAsActive (int gridID)
Definition at line 209 of file MainController.java.
References communicator.MainController.getGridContainer(), and commands.information.BaseGridContainer.setGridAsActive().
Referenced by View.SlogoView.build().
void communicator.MainController.setTimers () private
Definition at line 82 of file MainController.java.
References commandParser.CommandFactory.createCommand(), communicator.MainController.executeCommand(), communicator.MainController.reportErrorToView(), and View.SlogoView.setDisable().
Referenced by communicator.MainController.MainController().
void communicator.MainController.setTurtleAsActive (int turtleID)
Definition at line 268 of file MainController.java.
References commands.information.BaseTurtleContainer.setTurtleAsActive().
void communicator.MainController.start ()
Definition at line 129 of file MainController.java.
void communicator.MainController.stop ()
Definition at line 140 of file MainController.java.
Member Data Documentation
final String communicator.MainController.DEFAULT_ENGLISH_FILE = "src/resources/languages/English.properties" static private
Definition at line 45 of file MainController.java.
final String communicator.MainController.ENGLISH_TO_CLASS_FILE = "src/resources/languages/EnglishToClassName.properties" static private
Definition at line 57 of file MainController.java.
final String communicator.MainController.ERROR_READING_FROM_FILE = "Error reading from file" static private
Definition at line 43 of file MainController.java.
final String communicator.MainController.ERROR_WRITING_TO_FILE = "Error writing to file" static private
Definition at line 44 of file MainController.java.
AnimationTimer communicator.MainController.myCommandExecutionTimer private
Definition at line 51 of file MainController.java.
AtomicBoolean communicator.MainController.myCommandIsExecuting private
Definition at line 49 of file MainController.java.
AnimationTimer communicator.MainController.myCommandParserTimer private
Definition at line 52 of file MainController.java.
ConcurrentLinkedQueue<BaseCommand> communicator.MainController.myCommandQueue private
Definition at line 47 of file MainController.java.
CommandToClassTranslator communicator.MainController.myCommandToClassTranslator private
Definition at line 54 of file MainController.java.
Collection<BaseCommand> communicator.MainController.myExecutedCommands private
Definition at line 50 of file MainController.java.
IInformationGateway communicator.MainController.myInformationGateway private
Definition at line 55 of file MainController.java.
ConcurrentLinkedQueue<String> communicator.MainController.myInputsToParse private
Definition at line 48 of file MainController.java.
LanguageFileParser communicator.MainController.myTranslator private
Definition at line 53 of file MainController.java.
SlogoView communicator.MainController.myView private
Definition at line 46 of file MainController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/communicator/MainController.java