slogo_team13: GUIFunctions.SetBackgroundImage Class Reference
GUIFunctions.SetBackgroundImage Class Reference
Public Member Functions
SetBackgroundImage (GridTracker grid, Stage mainStage)
void doAction ()
void gridSetAction (Image img)
void doAction (List<?extends Number > newVal)
Public Member Functions inherited from GUIFunctions.PersonalizeMenu
PersonalizeMenu ()
Public Member Functions inherited from GUIFunctions.GridFunction
GridFunction ()
Private Attributes
Stage myStage
ImageView myImageView
Additional Inherited Members
Protected Attributes inherited from GUIFunctions.GridFunction
GridTracker allGrids
Detailed Description
Definition at line 24 of file SetBackgroundImage.java.
Constructor & Destructor Documentation
GUIFunctions.SetBackgroundImage.SetBackgroundImage (GridTracker grid, Stage mainStage)
Definition at line 27 of file SetBackgroundImage.java.
References GUIFunctions.GridFunction.allGrids.
Member Function Documentation
void GUIFunctions.SetBackgroundImage.doAction ()
Implements GUIFunctions.GUIFunction.
Definition at line 34 of file SetBackgroundImage.java.
References GUIFunctions.GridFunction.allGrids, View.GridTracker.getActiveGrid(), and GUIFunctions.SetBackgroundImage.gridSetAction().
void GUIFunctions.SetBackgroundImage.doAction (List<?extends Number > newVal)
Implements GUIFunctions.GUIFunction.
Definition at line 65 of file SetBackgroundImage.java.
void GUIFunctions.SetBackgroundImage.gridSetAction (Image img)
Definition at line 54 of file SetBackgroundImage.java.
References GUIFunctions.GridFunction.allGrids, View.GridTracker.getActiveGrid(), View.SingleGrid.getAllPens(), View.SingleGrid.getAllTurtles(), View.SingleGrid.getMyHeight(), and View.SingleGrid.getMyWidth().
Referenced by GUIFunctions.SetBackgroundImage.doAction().
Member Data Documentation
ImageView GUIFunctions.SetBackgroundImage.myImageView private
Definition at line 26 of file SetBackgroundImage.java.
Stage GUIFunctions.SetBackgroundImage.myStage private
Definition at line 25 of file SetBackgroundImage.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/GUIFunctions/SetBackgroundImage.java