slogo_team13: commands.information.MapBasedUserDefinedContainer Class Reference
commands.information.MapBasedUserDefinedContainer Class Reference
Public Member Functions
MapBasedUserDefinedContainer ()
boolean addVariable (String variable, BaseCommand command) throws BackendException
boolean addVariable (String variable, double value) throws BackendException
BaseCommand getValue (String variable) throws BackendException
BaseCommand popOffVariable (String variable)
void addNewCommand (String commandName, String innerCommands, String[] temporaryVariables)
BaseCommand getCreatedCommand (String commandName, String input, boolean isExpression) throws BackendException
Map< String, Double > getAllVariablesAndValues () throws BackendException
List< String > getAllCustomCommands ()
Public Member Functions inherited from commands.information.BaseUserDefinedContainer
abstract boolean addVariable (String variable, BaseCommand command) throws BackendException
abstract boolean addVariable (String variable, double value) throws BackendException
abstract BaseCommand getValue (String variable) throws BackendException
abstract BaseCommand popOffVariable (String variable)
abstract void addNewCommand (String commandName, String innerCommands, String[] temporaryVariables)
abstract BaseCommand getCreatedCommand (String commandName, String input, boolean isExpression) throws BackendException
boolean containsVariable (String variable) throws BackendException
boolean containsCustomCommand (String command)
abstract Map< String, Double > getAllVariablesAndValues () throws BackendException
abstract List< String > getAllCustomCommands ()
Private Attributes
Map< String, BaseCommand > myVariableToValuesMap
Map< String, String > myCreatedCommandMap
Map< String, String[]> myCreatedCommandVariableMap
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Map based implementation of BaseUserDefinedContainer
Author
Duke
Definition at line 21 of file MapBasedUserDefinedContainer.java.
Constructor & Destructor Documentation
commands.information.MapBasedUserDefinedContainer.MapBasedUserDefinedContainer ()
Definition at line 28 of file MapBasedUserDefinedContainer.java.
Member Function Documentation
void commands.information.MapBasedUserDefinedContainer.addNewCommand (String commandName, String innerCommands, String[] temporaryVariables)
Definition at line 78 of file MapBasedUserDefinedContainer.java.
boolean commands.information.MapBasedUserDefinedContainer.addVariable (String variable, BaseCommand command) throws BackendException
Definition at line 35 of file MapBasedUserDefinedContainer.java.
Referenced by commands.information.MapBasedUserDefinedContainer.addVariable().
boolean commands.information.MapBasedUserDefinedContainer.addVariable (String variable, double value) throws BackendException
Definition at line 51 of file MapBasedUserDefinedContainer.java.
References commands.information.MapBasedUserDefinedContainer.addVariable().
List<String> commands.information.MapBasedUserDefinedContainer.getAllCustomCommands ()
Definition at line 127 of file MapBasedUserDefinedContainer.java.
Map<String, Double> commands.information.MapBasedUserDefinedContainer.getAllVariablesAndValues () throws BackendException
Definition at line 111 of file MapBasedUserDefinedContainer.java.
References commands.BaseCommand.execute().
BaseCommand commands.information.MapBasedUserDefinedContainer.getCreatedCommand (String commandName, String input, boolean isExpression) throws BackendException
Definition at line 85 of file MapBasedUserDefinedContainer.java.
References commandParser.CommandFactory.createCommand(), commands.BaseCommand.getLeftoverString(), commands.variableCommands.CreatedCommand.setInnerCommand(), and commands.variableCommands.CreatedCommand.setVariables().
BaseCommand commands.information.MapBasedUserDefinedContainer.getValue (String variable) throws BackendException
Definition at line 59 of file MapBasedUserDefinedContainer.java.
BaseCommand commands.information.MapBasedUserDefinedContainer.popOffVariable (String variable)
Definition at line 68 of file MapBasedUserDefinedContainer.java.
Member Data Documentation
Map<String, String> commands.information.MapBasedUserDefinedContainer.myCreatedCommandMap private
Definition at line 25 of file MapBasedUserDefinedContainer.java.
Map<String, String[]> commands.information.MapBasedUserDefinedContainer.myCreatedCommandVariableMap private
Definition at line 26 of file MapBasedUserDefinedContainer.java.
Map<String, BaseCommand> commands.information.MapBasedUserDefinedContainer.myVariableToValuesMap private
Definition at line 24 of file MapBasedUserDefinedContainer.java.
final long commands.information.MapBasedUserDefinedContainer.serialVersionUID = 1L static private
Definition at line 23 of file MapBasedUserDefinedContainer.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/commands/information/MapBasedUserDefinedContainer.java