slogo_team13: commands.information.BaseUserDefinedContainer Class Reference
commands.information.BaseUserDefinedContainer Class Reference abstract
Public Member Functions
abstract boolean addVariable (String variable, BaseCommand command) throws BackendException
abstract boolean addVariable (String variable, double value) throws BackendException
abstract BaseCommand getValue (String variable) throws BackendException
abstract BaseCommand popOffVariable (String variable)
abstract void addNewCommand (String commandName, String innerCommands, String[] temporaryVariables)
abstract BaseCommand getCreatedCommand (String commandName, String input, boolean isExpression) throws BackendException
boolean containsVariable (String variable) throws BackendException
boolean containsCustomCommand (String command)
abstract Map< String, Double > getAllVariablesAndValues () throws BackendException
abstract List< String > getAllCustomCommands ()
Detailed Description
Container for all user defined inputs (i.e. variables and user defined commands). All variable and command containers must extend from this class in order for all the basic commands to work.
Author
Duke
Definition at line 17 of file BaseUserDefinedContainer.java.
Member Function Documentation
abstract void commands.information.BaseUserDefinedContainer.addNewCommand (String commandName, String innerCommands, String[] temporaryVariables) abstract
Adds user defined command
Parameters
commandName User defined command name
innerCommands String equivalent that the command represents
temporaryVariables Parameters associated with the command.
Referenced by commands.controlCommands.ToCommand.onExecute().
abstract boolean commands.information.BaseUserDefinedContainer.addVariable (String variable, BaseCommand command) throws BackendException abstract
Adds a variable.
Parameters
variable Variable name
command Command that the variable represents. Not the same as user defined commands.
Returns
Whether variable was successfully added.
Exceptions
BackendException Any exception while adding.
Referenced by commands.controlCommands.ForCommand.checkIfVariableExistsPreviously(), commands.controlCommands.DoCommand.checkIfVariableExistsPreviously(), commands.variableCommands.SetVariableCommand.onExecute(), commands.controlCommands.DoCommand.onExecute(), commands.controlCommands.ForCommand.onExecute(), commands.variableCommands.CreatedCommand.revertVariables(), commands.variableCommands.CreatedCommand.setNewVariables(), and commands.variableCommands.VariableCommandParseTest.testThatVariableIsGet().
abstract boolean commands.information.BaseUserDefinedContainer.addVariable (String variable, double value) throws BackendException abstract
Adds a variable.
Parameters
variable Variable name
value Double value of the variable.
Returns
Whether variable was successfully added.
Exceptions
BackendException Any exception while adding.
boolean commands.information.BaseUserDefinedContainer.containsCustomCommand (String command)
Definition at line 85 of file BaseUserDefinedContainer.java.
References commands.information.BaseUserDefinedContainer.getAllCustomCommands().
Referenced by commandParser.CommandFactory.createCommand().
boolean commands.information.BaseUserDefinedContainer.containsVariable (String variable) throws BackendException
Checks whether container has a specific variable.
Parameters
variable Variable to check.
Returns
Whether the container contains the variable.
Exceptions
BackendException Any exception while checking.
Definition at line 81 of file BaseUserDefinedContainer.java.
References commands.information.BaseUserDefinedContainer.getAllVariablesAndValues().
Referenced by commands.controlCommands.DoCommand.onExecute(), commands.controlCommands.ForCommand.onExecute(), and commands.variableCommands.CreatedCommand.setNewVariables().
abstract List<String> commands.information.BaseUserDefinedContainer.getAllCustomCommands () abstract
Gets all user defined custom commands
Returns
List of user commands.
Referenced by commands.information.BaseUserDefinedContainer.containsCustomCommand(), and communicator.MainController.sendUserDefinedVariablesAndCommands().
abstract Map<String, Double> commands.information.BaseUserDefinedContainer.getAllVariablesAndValues () throws BackendException abstract
Gets a mapping of all variables and their values.
Returns
Mapping of all variables and their values
Exceptions
BackendException Any exception while fetching the mapping.
Referenced by commands.information.BaseUserDefinedContainer.containsVariable(), and communicator.MainController.sendUserDefinedVariablesAndCommands().
abstract BaseCommand commands.information.BaseUserDefinedContainer.getCreatedCommand (String commandName, String input, boolean isExpression) throws BackendException abstract
Gets the command equivalent of the user defined command.
Parameters
commandName User defined command to fetch
input Parameters for the command.
isExpression Whether the command should be created as an expression
Returns
Command equivalent of usef defined command.
Exceptions
BackendException
Referenced by commandParser.CommandFactory.createCommand().
abstract BaseCommand commands.information.BaseUserDefinedContainer.getValue (String variable) throws BackendException abstract
Gets the value of variable
Parameters
variable Variable to get.
Returns
Value
Exceptions
BackendException Any exception while fetching value
Referenced by commands.variableCommands.GetVariableCommand.onExecute(), commands.controlCommands.DoCommand.onExecute(), commands.controlCommands.ForCommand.onExecute(), and commands.variableCommands.CreatedCommand.setNewVariables().
abstract BaseCommand commands.information.BaseUserDefinedContainer.popOffVariable (String variable) abstract
Removes a variable from the container.
Parameters
variable Variable to remove
Returns
Value that the variable corresponded to.
Referenced by commands.controlCommands.ForCommand.checkIfVariableExistsPreviously(), commands.controlCommands.DoCommand.checkIfVariableExistsPreviously(), and commands.variableCommands.CreatedCommand.revertVariables().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/commands/information/BaseUserDefinedContainer.java