slogo_team13: commandParser.CommandFactory Class Reference
commandParser.CommandFactory Class Reference
Static Public Member Functions
static BaseCommand createCommand (String input, boolean isExpression) throws BackendException
static void setInformationGateway (IInformationGateway informationGateway)
static void setCommandToClassRelation (Map< String, Class > commandToClassMap)
Static Private Member Functions
static String identifyFirstCommand (String input)
Static Private Attributes
static final String INVALID_COMMAND_CLASS_TYPE_MESSAGE = "Invalid command class type"
static Map< String, Class > myCommandToClassMap
static String myCommandSeparator = "\\s+"
static IInformationGateway myInformationHub
static Class[] x = { BaseUserDefinedContainer.class }
Detailed Description
Author
Rahul Harikrishnan, Duke Kim, $cotty $haw
    The Command Factory uses reflection to hide implementation details
    and creates the commands from the user's inputs using a key-value
    system.
    It is static because our createCommand method is recursive, so we
    need to avoid passing the factory to the individual commands.
Definition at line 24 of file CommandFactory.java.
Member Function Documentation
static BaseCommand commandParser.CommandFactory.createCommand (String input, boolean isExpression) throws BackendException static
Definition at line 32 of file CommandFactory.java.
References commands.information.BaseUserDefinedContainer.containsCustomCommand(), commands.information.IInformationGateway.getContainers(), commands.information.BaseUserDefinedContainer.getCreatedCommand(), commands.BaseCommand.getRequiredInformationTypes(), commandParser.CommandFactory.identifyFirstCommand(), and commands.BaseCommand.setRequiredInformation().
Referenced by commands.information.MapBasedUserDefinedContainer.getCreatedCommand(), tests.ExpressionCommandParseTest.naturalLogTest(), commands.turtleCommands.AskWithCommand.parseArguments(), commands.variableCommands.SetVariableCommand.parseArguments(), commands.expressionCommands.ExpressionCommand.parseArguments(), commands.controlCommands.IfCommand.parseArguments(), commands.controlCommands.IfElseCommand.parseArguments(), commands.turtleCommands.AskCommand.parseArguments(), commands.controlCommands.RepeatCommand.parseArguments(), commands.ViewCommand.parseArguments(), commands.controlCommands.ForCommand.parseArguments(), commands.turtleCommands.TurtleCommand.parseArguments(), commands.controlCommands.DoCommand.parseArguments(), commands.BaseCommand.setLeftoverCommands(), communicator.MainController.setTimers(), tests.AskWithTest.testAlwaysTrueAskWith(), tests.ExpressionCommandParseTest.testAnd(), tests.ExpressionCommandParseTest.testATan(), tests.ExpressionCommandParseTest.testCos(), tests.ExpressionCommandParseTest.testDifference(), tests.ExpressionCommandParseTest.testEqual(), tests.ExpressionCommandParseTest.testGreater(), tests.ExpressionCommandParseTest.testLess(), tests.ExpressionCommandParseTest.testMinus(), tests.ExpressionCommandParseTest.testNot(), tests.ExpressionCommandParseTest.testNotEqual(), tests.ExpressionCommandParseTest.testOr(), tests.ExpressionCommandParseTest.testPower(), tests.ExpressionCommandParseTest.testProduct(), tests.ExpressionCommandParseTest.testQuotient(), tests.ExpressionCommandParseTest.testRandom(), tests.ExpressionCommandParseTest.testRemainder(), tests.ExpressionCommandParseTest.testSin(), tests.ExpressionCommandParseTest.testSumParses(), tests.ExpressionCommandParseTest.testTan(), tests.AskTest.testThatAskCreatesTurtles(), commands.controlCommands.ContainerTest.testThatIfWorks(), commands.variableCommands.VariableCommandParseTest.testThatVariableIsGet(), tests.TurtleCommandsTest.testToParsing(), tests.ToCommandTest.testToParsing(), and tests.AskWithTest.testXCorAskWith().
static String commandParser.CommandFactory.identifyFirstCommand (String input) static private
Definition at line 85 of file CommandFactory.java.
Referenced by commandParser.CommandFactory.createCommand().
static void commandParser.CommandFactory.setCommandToClassRelation (Map< String, Class > commandToClassMap) static
Definition at line 80 of file CommandFactory.java.
Referenced by communicator.MainController.MainController(), commands.controlCommands.ContainerTest.processInput(), tests.AskTest.processInput(), tests.TurtleCommandsTest.processInput(), commands.variableCommands.VariableCommandParseTest.processInput(), tests.ToCommandTest.processInput(), tests.AskWithTest.processInput(), and tests.ExpressionCommandParseTest.processInput().
static void commandParser.CommandFactory.setInformationGateway (IInformationGateway informationGateway) static
Definition at line 76 of file CommandFactory.java.
Referenced by communicator.MainController.MainController(), commands.controlCommands.ContainerTest.processInput(), tests.AskTest.setFactory(), tests.TurtleCommandsTest.setFactory(), tests.ToCommandTest.setFactory(), and tests.AskWithTest.setFactory().
Member Data Documentation
final String commandParser.CommandFactory.INVALID_COMMAND_CLASS_TYPE_MESSAGE = "Invalid command class type" static private
Definition at line 26 of file CommandFactory.java.
String commandParser.CommandFactory.myCommandSeparator = "\\s+" static private
Definition at line 28 of file CommandFactory.java.
Map<String, Class> commandParser.CommandFactory.myCommandToClassMap static private
Definition at line 27 of file CommandFactory.java.
IInformationGateway commandParser.CommandFactory.myInformationHub static private
Definition at line 29 of file CommandFactory.java.
Class [] commandParser.CommandFactory.x = { BaseUserDefinedContainer.class } static private
Definition at line 30 of file CommandFactory.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/commandParser/CommandFactory.java