slogo_team13: GUIFunctions.BackgroundColor Class Reference
GUIFunctions.BackgroundColor Class Reference
Public Member Functions
BackgroundColor (GridTracker grid, ColorSelection colors)
void doAction (List<?extends Number > newVal)
void doAction (String myColor)
void doAction ()
Public Member Functions inherited from GUIFunctions.ColorFunction
ColorFunction ()
abstract void doAction (String s)
Public Member Functions inherited from GUIFunctions.GridFunction
GridFunction ()
Package Attributes
ColorSelection myColors
Package Attributes inherited from GUIFunctions.ColorFunction
GridTracker myGrids
Additional Inherited Members
Protected Attributes inherited from GUIFunctions.GridFunction
GridTracker allGrids
Detailed Description
Definition at line 12 of file BackgroundColor.java.
Constructor & Destructor Documentation
GUIFunctions.BackgroundColor.BackgroundColor (GridTracker grid, ColorSelection colors)
Definition at line 14 of file BackgroundColor.java.
References GUIFunctions.ColorFunction.myGrids.
Member Function Documentation
void GUIFunctions.BackgroundColor.doAction (List<?extends Number > newVal)
Implements GUIFunctions.GUIFunction.
Definition at line 21 of file BackgroundColor.java.
References View.GridTracker.getActiveGrid(), View.ColorSelection.getAvailableColors(), GUIFunctions.ColorFunction.myGrids, and View.SingleGrid.setBackgroundColor().
void GUIFunctions.BackgroundColor.doAction (String myColor)
Definition at line 25 of file BackgroundColor.java.
References View.GridTracker.getActiveGrid(), GUIFunctions.ColorFunction.myGrids, and View.SingleGrid.setBackgroundColor().
void GUIFunctions.BackgroundColor.doAction ()
Implements GUIFunctions.GUIFunction.
Definition at line 30 of file BackgroundColor.java.
Member Data Documentation
ColorSelection GUIFunctions.BackgroundColor.myColors package
Definition at line 13 of file BackgroundColor.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/GUIFunctions/BackgroundColor.java