slogo_team13: TableInformation.Column< G > Class Template Reference
TableInformation.Column< G > Class Template Reference abstract
Public Member Functions
Column (String s)
abstract void doEditingFunction (CellEditEvent< Turtle, G > myData, Turtle myTurtle)
Protected Member Functions
Callback< TableColumn< Turtle, G >, TableCell< Turtle, G > > makeCellFactory ()
abstract EditingCell< Turtle, G > makeEditingCell ()
abstract ReadOnlyObjectWrapper< G > doFunction (CellDataFeatures< Turtle, G > myData)
Private Member Functions
void makeColumn ()
Detailed Description
Definition at line 14 of file Column.java.
Constructor & Destructor Documentation
TableInformation.Column< G >.Column (String s)
Definition at line 15 of file Column.java.
Member Function Documentation
abstract void TableInformation.Column< G >.doEditingFunction (CellEditEvent< Turtle, G > myData, Turtle myTurtle) abstract
Referenced by TableInformation.TurtleVariablesTable.moveTurtle().
abstract ReadOnlyObjectWrapper<G> TableInformation.Column< G >.doFunction (CellDataFeatures< Turtle, G > myData) abstract protected
Referenced by TableInformation.Column< Integer >.makeColumn().
Callback<TableColumn<Turtle, G>, TableCell<Turtle, G> > TableInformation.Column< G >.makeCellFactory () protected
Definition at line 29 of file Column.java.
void TableInformation.Column< G >.makeColumn () private
Definition at line 20 of file Column.java.
Referenced by TableInformation.Column< Integer >.Column().
abstract EditingCell<Turtle, G> TableInformation.Column< G >.makeEditingCell () abstract protected
Referenced by TableInformation.Column< Integer >.makeCellFactory().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/TableInformation/Column.java