slogo_team13: model.TurtleFactory Class Reference
model.TurtleFactory Class Reference
Public Member Functions
void createTurtle (Image image)
List< Turtle > getActiveTurtles ()
Turtle findTurtle (int ID)
Private Attributes
List< Turtle > myActiveTurtles = new ArrayList<Turtle>()
Detailed Description
Author
Rahul Harikrishnan, Duke Kim, $cotty $haw
Definition at line 14 of file TurtleFactory.java.
Member Function Documentation
void model.TurtleFactory.createTurtle (Image image)
Definition at line 18 of file TurtleFactory.java.
References turtle.Turtle.setID().
Referenced by model.SlogoModel.initializeTurtle().
Turtle model.TurtleFactory.findTurtle (int ID)
Definition at line 36 of file TurtleFactory.java.
Referenced by model.SlogoModel.findTurtle().
List<Turtle> model.TurtleFactory.getActiveTurtles ()
Definition at line 32 of file TurtleFactory.java.
References model.TurtleFactory.myActiveTurtles.
Referenced by model.SlogoModel.getActiveTurtles().
Member Data Documentation
List<Turtle> model.TurtleFactory.myActiveTurtles = new ArrayList<Turtle>() private
Definition at line 16 of file TurtleFactory.java.
Referenced by model.TurtleFactory.getActiveTurtles().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/model/TurtleFactory.java