slogo_team13: View.SlogoView Class Reference
View.SlogoView Class Reference
Public Member Functions
SlogoView () throws ClassNotFoundException
void initialize (Stage mainStage)
void showError (String message)
void enable ()
void setDisable (Boolean toDisable)
void addVariables (Map< String, Double > myVariables)
void addUserFunctions (List< String > myFunctions)
Grid addGrid ()
Public Attributes
Queue< ButtonTemplate > myCommands =new LinkedList<ButtonTemplate>()
Static Public Attributes
static final String DEFAULT_RESOURCE_PACKAGE = "resources/"
Package Attributes
HashMap< String, GUIFunction > myUserFunctions =new HashMap<String, GUIFunction>()
Private Member Functions
KeyFrame build (int fps)
void sendCommandAndMakeButton (String command)
MenuBar addMenuBar ()
void makeLanguageMenu (Class myClass, MenuTemplate myMenu)
void makeAddMenu (MenuTemplate myAdd)
void addTurtle ()
Pane setTextArea ()
Button makeEnterButton ()
Button makeCommandButton ()
Text makeCommandHistoryLabel ()
void makeCommandHistoryBox ()
void createCommandLineWithLabel (Pane textArea)
Pane addButtons ()
void updateCommandHistory ()
void makeUserCommand (String command)
void executeUserCommand (String command)
ArrayList< ButtonTemplate > makeButtons (Class myClass, String location)
void makeMenu (Class myClass, MenuTemplate myMenu)
Collection< ScrollingBar > makeSlidingBars ()
void addLanguages ()
MenuTemplate createfileMenu ()
String saveFile ()
void saveFileToController (String fileName)
void checkNullFile (File myFile)
void makeListOfFunctions ()
Private Attributes
GridFactory myGridFactory
GridTracker myGrids
MainController myController
TabsOfGrids myGridTabs =new TabsOfGrids()
ColorSelection colorSelection
Group root =new Group()
Scene myScene
TextField commandLine
VBox commandHistoryBox
MenuTemplate userCommands
final int fps =100
Map< String, String > userCommandMap = new HashMap<>()
ResourceBundle myResources
Stage myStage
VariableTable myVariableTable
final int DEFAULT_MENU_HEIGHT =30
Static Private Attributes
static final Dimension DEFAULT_SIZE =new Dimension(1000,600)
static final int MAX_COMMAND_HISTORY = 5
Detailed Description
Definition at line 72 of file SlogoView.java.
Constructor & Destructor Documentation
View.SlogoView.SlogoView () throws ClassNotFoundException
Definition at line 100 of file SlogoView.java.
References View.SlogoView.build(), and View.SlogoView.makeListOfFunctions().
Member Function Documentation
Pane View.SlogoView.addButtons () private
Creates buttons on bottom of GUI
Returns
Definition at line 364 of file SlogoView.java.
References View.SlogoView.makeButtons(), and View.SlogoView.makeSlidingBars().
Referenced by View.SlogoView.initialize().
Grid View.SlogoView.addGrid ()
Used to create the original grid and any additional grids the user wants.
Returns
Definition at line 269 of file SlogoView.java.
References communicator.MainController.addGrid(), View.TabsOfGrids.addTab(), View.GridFactory.makeGrid(), and View.GridTracker.setActiveGrid().
Referenced by View.SlogoView.initialize().
void View.SlogoView.addLanguages () private
Definition at line 455 of file SlogoView.java.
Referenced by View.SlogoView.makeListOfFunctions().
MenuBar View.SlogoView.addMenuBar () private
Definition at line 186 of file SlogoView.java.
References View.MenuTemplate.addMenuItem(), View.SlogoView.createfileMenu(), View.SlogoView.makeAddMenu(), View.SlogoView.makeLanguageMenu(), and View.SlogoView.makeMenu().
Referenced by View.SlogoView.initialize().
void View.SlogoView.addTurtle () private
Definition at line 261 of file SlogoView.java.
References View.SingleGrid.addTurtle(), communicator.MainController.addTurtle(), View.GridTracker.getActiveGrid(), and View.Grid.getID().
Referenced by View.SlogoView.initialize().
void View.SlogoView.addUserFunctions (List< String > myFunctions)
Parameters
myFunctions
Definition at line 246 of file SlogoView.java.
References TableInformation.VariableTable.addInputs().
Referenced by communicator.MainController.sendUserDefinedVariablesAndCommands().
void View.SlogoView.addVariables (Map< String, Double > myVariables)
Parameters
myVariables
Definition at line 232 of file SlogoView.java.
References TableInformation.VariableTable.addVariables().
Referenced by communicator.MainController.sendUserDefinedVariablesAndCommands().
KeyFrame View.SlogoView.build (int fps) private
Returns
A KeyFrame for the TimeLine of the program
Definition at line 118 of file SlogoView.java.
References View.GridTracker.getActiveGrid(), View.TabsOfGrids.getActiveGrid(), View.Grid.getID(), View.GridTracker.setActiveGrid(), and communicator.MainController.setGridAsActive().
Referenced by View.SlogoView.SlogoView().
void View.SlogoView.checkNullFile (File myFile) private
Definition at line 487 of file SlogoView.java.
References communicator.MainController.loadPreferences().
void View.SlogoView.createCommandLineWithLabel (Pane textArea) private
Definition at line 340 of file SlogoView.java.
References View.SlogoView.sendCommandAndMakeButton().
Referenced by View.SlogoView.setTextArea().
MenuTemplate View.SlogoView.createfileMenu () private
Definition at line 467 of file SlogoView.java.
References View.MenuTemplate.addMenuItem(), View.SlogoView.saveFile(), and GUIFunctions.AskForInitialFile.sendFile().
Referenced by View.SlogoView.addMenuBar().
void View.SlogoView.enable ()
Definition at line 183 of file SlogoView.java.
void View.SlogoView.executeUserCommand (String command) private
Definition at line 397 of file SlogoView.java.
References communicator.MainController.receiveCommand(), View.SlogoView.sendCommandAndMakeButton(), and View.SlogoView.updateCommandHistory().
void View.SlogoView.initialize (Stage mainStage)
Creates a layout of the GUI and adds the objects to the Stage
Parameters
mainStage the Stage for the GUI to operate on
Exceptions
SecurityException
NoSuchMethodException
InvocationTargetException
IllegalArgumentException
IllegalAccessException
InstantiationException
ClassNotFoundException
Definition at line 142 of file SlogoView.java.
References View.SlogoView.addButtons(), View.SlogoView.addGrid(), View.SlogoView.addMenuBar(), View.SlogoView.addTurtle(), View.GridTracker.getActiveGrid(), View.GridFactory.setGridMap(), and View.SlogoView.setTextArea().
Referenced by View.Slogo.start().
void View.SlogoView.makeAddMenu (MenuTemplate myAdd) private
Definition at line 256 of file SlogoView.java.
References View.MenuTemplate.addMenuItem().
Referenced by View.SlogoView.addMenuBar().
ArrayList<ButtonTemplate> View.SlogoView.makeButtons (Class myClass, String location) private
creates all of the buttons for the GUI from a resource file
Parameters
myClass
location
Returns
Definition at line 413 of file SlogoView.java.
Referenced by View.SlogoView.addButtons().
Button View.SlogoView.makeCommandButton () private
Definition at line 317 of file SlogoView.java.
References View.SlogoView.makeUserCommand().
Referenced by View.SlogoView.setTextArea().
void View.SlogoView.makeCommandHistoryBox () private
Definition at line 334 of file SlogoView.java.
Referenced by View.SlogoView.setTextArea().
Text View.SlogoView.makeCommandHistoryLabel () private
Definition at line 327 of file SlogoView.java.
Referenced by View.SlogoView.setTextArea().
Button View.SlogoView.makeEnterButton () private
Definition at line 307 of file SlogoView.java.
Referenced by View.SlogoView.setTextArea().
void View.SlogoView.makeLanguageMenu (Class myClass, MenuTemplate myMenu) private
Definition at line 218 of file SlogoView.java.
References View.MenuTemplate.addMenuItem(), and GUIFunctions.LanguageMenu.doAction().
Referenced by View.SlogoView.addMenuBar().
void View.SlogoView.makeListOfFunctions () private
Creates a list of functions to be used with the GUI's buttons, menus, etc.
Definition at line 503 of file SlogoView.java.
References View.SlogoView.addLanguages().
Referenced by View.SlogoView.SlogoView().
void View.SlogoView.makeMenu (Class myClass, MenuTemplate myMenu) private
Creates all of the menus for the GUI from a resource file
Parameters
myClass
myMenu
Definition at line 438 of file SlogoView.java.
References View.MenuTemplate.addMenuItem().
Referenced by View.SlogoView.addMenuBar().
Collection<ScrollingBar> View.SlogoView.makeSlidingBars () private
Definition at line 448 of file SlogoView.java.
Referenced by View.SlogoView.addButtons().
void View.SlogoView.makeUserCommand (String command) private
allows the user to save a set of instructions as a menu item for easy access later
Parameters
command
Definition at line 390 of file SlogoView.java.
References View.MenuTemplate.addMenuItem().
Referenced by View.SlogoView.makeCommandButton().
String View.SlogoView.saveFile () private
Definition at line 475 of file SlogoView.java.
Referenced by View.SlogoView.createfileMenu().
void View.SlogoView.saveFileToController (String fileName) private
Definition at line 479 of file SlogoView.java.
References communicator.MainController.savePreferences().
void View.SlogoView.sendCommandAndMakeButton (String command) private
Passes the commands from the textbox on the GUI to the controller for parsing. Also creates a interactive button of the command to be shown in the command history.
Parameters
s String representing the command to send that was inputed by the user
Definition at line 173 of file SlogoView.java.
References communicator.MainController.receiveCommand(), and View.SlogoView.updateCommandHistory().
Referenced by View.SlogoView.createCommandLineWithLabel(), and View.SlogoView.executeUserCommand().
void View.SlogoView.setDisable (Boolean toDisable)
Disables all of the buttons on the GUI. Used when a command is sent to the backend to prevent concurrency issues.
Parameters
toDisable
Definition at line 212 of file SlogoView.java.
Referenced by communicator.MainController.executeCommand(), communicator.MainController.receiveCommand(), and communicator.MainController.setTimers().
Pane View.SlogoView.setTextArea () private
Creates all information on left side of screen
Returns
Definition at line 293 of file SlogoView.java.
References View.SlogoView.createCommandLineWithLabel(), View.SlogoView.makeCommandButton(), View.SlogoView.makeCommandHistoryBox(), View.SlogoView.makeCommandHistoryLabel(), and View.SlogoView.makeEnterButton().
Referenced by View.SlogoView.initialize().
void View.SlogoView.showError (String message)
Displays the error message "message" on the screen
Definition at line 164 of file SlogoView.java.
Referenced by communicator.MainController.reportErrorToView().
void View.SlogoView.updateCommandHistory () private
Definition at line 374 of file SlogoView.java.
References View.SlogoView.MAX_COMMAND_HISTORY.
Referenced by View.SlogoView.executeUserCommand(), and View.SlogoView.sendCommandAndMakeButton().
Member Data Documentation
ColorSelection View.SlogoView.colorSelection private
Definition at line 78 of file SlogoView.java.
VBox View.SlogoView.commandHistoryBox private
Definition at line 89 of file SlogoView.java.
TextField View.SlogoView.commandLine private
Definition at line 85 of file SlogoView.java.
final int View.SlogoView.DEFAULT_MENU_HEIGHT =30 private
Definition at line 97 of file SlogoView.java.
final String View.SlogoView.DEFAULT_RESOURCE_PACKAGE = "resources/" static
Definition at line 99 of file SlogoView.java.
final Dimension View.SlogoView.DEFAULT_SIZE =new Dimension(1000,600) static private
Definition at line 96 of file SlogoView.java.
final int View.SlogoView.fps =100 private
Definition at line 91 of file SlogoView.java.
final int View.SlogoView.MAX_COMMAND_HISTORY = 5 static private
Definition at line 98 of file SlogoView.java.
Referenced by View.SlogoView.updateCommandHistory().
Queue<ButtonTemplate> View.SlogoView.myCommands =new LinkedList<ButtonTemplate>()
Definition at line 83 of file SlogoView.java.
MainController View.SlogoView.myController private
Definition at line 76 of file SlogoView.java.
GridFactory View.SlogoView.myGridFactory private
Definition at line 74 of file SlogoView.java.
GridTracker View.SlogoView.myGrids private
Definition at line 75 of file SlogoView.java.
TabsOfGrids View.SlogoView.myGridTabs =new TabsOfGrids() private
Definition at line 77 of file SlogoView.java.
ResourceBundle View.SlogoView.myResources private
Definition at line 93 of file SlogoView.java.
Scene View.SlogoView.myScene private
Definition at line 84 of file SlogoView.java.
Stage View.SlogoView.myStage private
Definition at line 94 of file SlogoView.java.
HashMap<String, GUIFunction> View.SlogoView.myUserFunctions =new HashMap<String, GUIFunction>() package
Definition at line 88 of file SlogoView.java.
VariableTable View.SlogoView.myVariableTable private
Definition at line 95 of file SlogoView.java.
Group View.SlogoView.root =new Group() private
Definition at line 81 of file SlogoView.java.
Map<String, String> View.SlogoView.userCommandMap = new HashMap<>() private
Definition at line 92 of file SlogoView.java.
MenuTemplate View.SlogoView.userCommands private
Definition at line 90 of file SlogoView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/View/SlogoView.java