slogo_team13: View.GridFactory Class Reference
View.GridFactory Class Reference
Public Member Functions
GridFactory (KeyFrame frame, HashMap< String, GUIFunction > myHashMap) throws ClassNotFoundException
Grid makeGrid (String typeOfGrid) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException
void setGridMap (HashMap myGridMap)
Package Attributes
final Collection< Grid > allGrids
Private Member Functions
void makeGridClassMap () throws ClassNotFoundException
Private Attributes
final KeyFrame myFrame
final HashMap< String, Class<?extends Grid > > myGrids =new HashMap<String, Class<? extends Grid>>()
HashMap< String, GUIFunction > myMap
Static Private Attributes
static int my_ID =0
Detailed Description
Definition at line 13 of file GridFactory.java.
Constructor & Destructor Documentation
View.GridFactory.GridFactory (KeyFrame frame, HashMap< String, GUIFunction > myHashMap) throws ClassNotFoundException
Parameters
frame The frame of the View's Timeline
myHashMap the Map corresponding the the GUIFunctions
Exceptions
ClassNotFoundException
Definition at line 27 of file GridFactory.java.
References View.GridFactory.makeGridClassMap().
Member Function Documentation
Grid View.GridFactory.makeGrid (String typeOfGrid) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException
Makes a Grid of the desired class
Parameters
typeOfGrid the name of the Grid Class to be made
Returns
the Grid that was just created
Exceptions
InstantiationException
IllegalAccessException
IllegalArgumentException
InvocationTargetException
NoSuchMethodException
SecurityException
Definition at line 46 of file GridFactory.java.
Referenced by View.SlogoView.addGrid().
void View.GridFactory.makeGridClassMap () throws ClassNotFoundException private
Definition at line 52 of file GridFactory.java.
Referenced by View.GridFactory.GridFactory().
void View.GridFactory.setGridMap (HashMap myGridMap)
Sets the GUIFunction Map for all the Grids made in the Factory
Parameters
myGridMap represents the new GUIFunction Map for the Grid to use
Definition at line 64 of file GridFactory.java.
Referenced by View.SlogoView.initialize().
Member Data Documentation
final Collection<Grid> View.GridFactory.allGrids package
Definition at line 17 of file GridFactory.java.
int View.GridFactory.my_ID =0 static private
Definition at line 14 of file GridFactory.java.
final KeyFrame View.GridFactory.myFrame private
Definition at line 15 of file GridFactory.java.
final HashMap<String, Class<? extends Grid> > View.GridFactory.myGrids =new HashMap<String, Class<? extends Grid>>() private
Definition at line 16 of file GridFactory.java.
HashMap<String, GUIFunction> View.GridFactory.myMap private
Definition at line 18 of file GridFactory.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/View/GridFactory.java