slogo_team13: commands.information.BaseGridContainer Class Reference
commands.information.BaseGridContainer Class Reference abstract
Public Member Functions
abstract void updateDisplayOptions (String guiCommand)
abstract void updateDisplayOptions (String guiCommand, List< Double > parameters)
abstract void addGrid (Grid grid, boolean isActive)
abstract void setGridAsActive (int gridID)
abstract void removeGrid (int gridID)
abstract Collection< Grid > getActiveGrids ()
abstract void update (Collection< Turtle > turtles)
Detailed Description
Author
Rahul Harikrishnan, Duke Kim, $cotty $haw
In order for all the basic commands to work, all grid containers must extend from this base class. Should contain all grids.
Definition at line 15 of file BaseGridContainer.java.
Member Function Documentation
abstract void commands.information.BaseGridContainer.addGrid (Grid grid, boolean isActive) abstract
Adds a grid to the container.
Parameters
grid Grid to add
isActive Whether grid should be added as active or not
Referenced by communicator.MainController.addGrid(), and tests.AskTest.setFactory().
abstract Collection<Grid> commands.information.BaseGridContainer.getActiveGrids () abstract
Gets all active grids.
Returns
All active grids.
Referenced by commands.turtleCommands.MultipleTurtleCommand.addFutureActiveTurtleTurtles(), and commands.viewCommands.HomeCommand.onExecute().
abstract void commands.information.BaseGridContainer.removeGrid (int gridID) abstract
Removes a specific grid from the grid list.
Parameters
gridID ID of grid to remove
abstract void commands.information.BaseGridContainer.setGridAsActive (int gridID) abstract
Sets a specific grid as active.
Parameters
gridID ID of grid to set active.
Referenced by communicator.MainController.setGridAsActive().
abstract void commands.information.BaseGridContainer.update (Collection< Turtle > turtles) abstract
Tells grid(s) to update its turtles.
Parameters
turtles Turtles to update.
Referenced by commands.turtleCommands.BackCommand.onExecute(), commands.turtleCommands.ForwardCommand.onExecute(), commands.turtleCommands.RightCommand.onExecute(), commands.turtleCommands.SetHeadingCommand.onExecute(), commands.turtleCommands.LeftCommand.onExecute(), commands.viewCommands.ClearScreenCommand.onExecute(), commands.turtleCommands.TowardsCommand.onExecute(), commands.turtleCommands.SetPositionCommand.onExecute(), and commands.viewCommands.HomeCommand.onExecute().
abstract void commands.information.BaseGridContainer.updateDisplayOptions (String guiCommand) abstract
Tells the GUI to perform a specific function which takes no parameters based on the string provided.
Parameters
guiCommand String to specify GUI function
Referenced by commands.viewCommands.ClearStampsCommand.onExecute(), commands.viewCommands.StampCommand.onExecute(), commands.viewCommands.PenUpCommand.onExecute(), commands.viewQueries.PenColorQuery.onExecute(), commands.viewQueries.PenDownQuery.onExecute(), commands.viewCommands.PenDownCommand.onExecute(), commands.viewCommands.SetPenSizeCommand.onExecute(), commands.viewCommands.SetPenColorCommand.onExecute(), commands.viewCommands.ClearScreenCommand.onExecute(), commands.viewCommands.SetBackgroundCommand.onExecute(), commands.viewQueries.ShowingQuery.onExecute(), commands.viewQueries.ShapeQuery.onExecute(), and commands.viewCommands.SetPaletteCommand.onExecute().
abstract void commands.information.BaseGridContainer.updateDisplayOptions (String guiCommand, List< Double > parameters) abstract
Tells the GUI to perform a specific function which takes numbers as parameters based on the string provided.
Parameters
guiCommand guiCommand String to specify GUI function
parameters parameters required for the GUI function.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/commands/information/BaseGridContainer.java