slogo_team13: commands.information.SingleGridInformationGateway Class Reference
commands.information.SingleGridInformationGateway Class Reference
Public Member Functions
SingleGridInformationGateway ()
SingleGridInformationGateway (Grid grid, Turtle turtle)
IInformationContainer getContainer (Class<?extends IInformationContainer > containerType)
Collection< IInformationContainer > getContainers (Set< Class<?extends IInformationContainer >> containerTypes) throws BackendException
void addContainer (IInformationContainer container)
Private Attributes
SingleActiveGridContainer myGridContainer
Map< Integer, BaseTurtleContainer > myGridToTurtlesMap
BaseUserDefinedContainer myVariableContainer
Static Private Attributes
static final String INVALID_CONTAINER_TYPE_ERROR = "Invalid container type"
Detailed Description
Author
Duke An implementation of the IInformationGateway that uses one active grid, and has a one to one mapping of each grid to a turtle container. Also contains one variable container for all grids and turtles.
Definition at line 17 of file SingleGridInformationGateway.java.
Constructor & Destructor Documentation
commands.information.SingleGridInformationGateway.SingleGridInformationGateway ()
Definition at line 24 of file SingleGridInformationGateway.java.
commands.information.SingleGridInformationGateway.SingleGridInformationGateway (Grid grid, Turtle turtle)
Definition at line 30 of file SingleGridInformationGateway.java.
References commands.information.SingleActiveGridContainer.addGrid(), and View.Grid.getID().
Member Function Documentation
void commands.information.SingleGridInformationGateway.addContainer (IInformationContainer container)
Adds a container to the gateway.
Parameters
container Container to be added
Exceptions
BackendException Any exception while adding container
Implements commands.information.IInformationGateway.
Definition at line 82 of file SingleGridInformationGateway.java.
IInformationContainer commands.information.SingleGridInformationGateway.getContainer (Class<?extends IInformationContainer > containerType)
Gets the container corresponding to the requested container type
Parameters
containerType The type of container to get.
Returns
The requested information container
Implements commands.information.IInformationGateway.
Definition at line 39 of file SingleGridInformationGateway.java.
References View.Grid.getID(), commands.information.SingleGridInformationGateway.myGridContainer, and commands.information.SingleGridInformationGateway.myVariableContainer.
Referenced by commands.information.SingleGridInformationGateway.getContainers().
Collection<IInformationContainer> commands.information.SingleGridInformationGateway.getContainers (Set< Class<?extends IInformationContainer >> containerTypes) throws BackendException
Gets a collection of containers corresponding to the requested container types.
Parameters
containerTypes The types of containers to get.
Returns
Collection of requested information containers.
Exceptions
BackendException Any exception to be thrown.
Implements commands.information.IInformationGateway.
Definition at line 67 of file SingleGridInformationGateway.java.
References commands.information.SingleGridInformationGateway.getContainer().
Member Data Documentation
final String commands.information.SingleGridInformationGateway.INVALID_CONTAINER_TYPE_ERROR = "Invalid container type" static private
Definition at line 19 of file SingleGridInformationGateway.java.
SingleActiveGridContainer commands.information.SingleGridInformationGateway.myGridContainer private
Definition at line 20 of file SingleGridInformationGateway.java.
Referenced by commands.information.SingleGridInformationGateway.getContainer().
Map<Integer, BaseTurtleContainer> commands.information.SingleGridInformationGateway.myGridToTurtlesMap private
Definition at line 21 of file SingleGridInformationGateway.java.
BaseUserDefinedContainer commands.information.SingleGridInformationGateway.myVariableContainer private
Definition at line 22 of file SingleGridInformationGateway.java.
Referenced by commands.information.SingleGridInformationGateway.getContainer().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/commands/information/SingleGridInformationGateway.java