slogo_team13: View.TabsOfGrids Class Reference
View.TabsOfGrids Class Reference
Public Member Functions
TabsOfGrids ()
SingleGrid getActiveGrid ()
void addTab (String gridTitle, SingleGrid grid)
void disableTabPanes (Tab myTab)
void setUpKeyBoardHandler (Tab myTab)
void setGridTabsFocused (Tab myTab)
Private Attributes
EventHandler myEvent
Detailed Description
Definition at line 11 of file TabsOfGrids.java.
Constructor & Destructor Documentation
View.TabsOfGrids.TabsOfGrids ()
Definition at line 14 of file TabsOfGrids.java.
Member Function Documentation
void View.TabsOfGrids.addTab (String gridTitle, SingleGrid grid)
Definition at line 26 of file TabsOfGrids.java.
References View.TabsOfGrids.disableTabPanes(), View.SingleGrid.getMyHeight(), View.SingleGrid.getMyWidth(), View.TabsOfGrids.setGridTabsFocused(), and View.TabsOfGrids.setUpKeyBoardHandler().
Referenced by View.SlogoView.addGrid().
void View.TabsOfGrids.disableTabPanes (Tab myTab)
Definition at line 37 of file TabsOfGrids.java.
Referenced by View.TabsOfGrids.addTab().
SingleGrid View.TabsOfGrids.getActiveGrid ()
Definition at line 18 of file TabsOfGrids.java.
Referenced by View.SlogoView.build().
void View.TabsOfGrids.setGridTabsFocused (Tab myTab)
Definition at line 59 of file TabsOfGrids.java.
Referenced by View.TabsOfGrids.addTab().
void View.TabsOfGrids.setUpKeyBoardHandler (Tab myTab)
Definition at line 46 of file TabsOfGrids.java.
References View.SingleGrid.getActiveTurtles(), and View.SingleGrid.keyUpdate().
Referenced by View.TabsOfGrids.addTab().
Member Data Documentation
EventHandler View.TabsOfGrids.myEvent private
Definition at line 12 of file TabsOfGrids.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/View/TabsOfGrids.java