slogo_team13: commands.viewCommands.HomeCommand Class Reference
commands.viewCommands.HomeCommand Class Reference
Public Member Functions
HomeCommand (String command, boolean isExpression) throws BackendException
Public Member Functions inherited from commands.TurtleQuery
TurtleQuery (String userInput, boolean isExpression) throws BackendException
Public Member Functions inherited from commands.turtleCommands.TurtleCommand
TurtleCommand (String userInput, boolean isExpression) throws BackendException
Set< Class<?extends IInformationContainer > > getRequiredInformationTypes ()
void setRequiredInformation (Collection< IInformationContainer > containers)
Public Member Functions inherited from commands.BaseCommand
BaseCommand (String userInput, boolean isExpression) throws BackendException
double execute () throws BackendException
abstract Set< Class<?extends IInformationContainer > > getRequiredInformationTypes ()
abstract void setRequiredInformation (Collection< IInformationContainer > containers) throws BackendException
String getLeftoverString ()
Protected Member Functions
double onExecute () throws BackendException
Protected Member Functions inherited from commands.TurtleQuery
void parseArguments (String userInput) throws BackendException
int getArgumentCount ()
Protected Member Functions inherited from commands.turtleCommands.TurtleCommand
BaseTurtleContainer getTurtleContainer ()
BaseGridContainer getGridContainer ()
void parseArguments (String userInput) throws BackendException
BaseCommand[] getExpressionList ()
abstract int getArgumentCount ()
void reset ()
Protected Member Functions inherited from commands.BaseCommand
abstract double onExecute () throws BackendException
abstract void parseArguments (String userInput) throws BackendException
void setLeftoverCommands (String string) throws BackendException
String[] splitByInnerListCommand (String input)
boolean startsWithCommandStartIndicator (String input)
abstract void reset ()
Static Private Attributes
static final String EXACTLY_ONE_ACTIVE_GRID_IS_NOT_SET = "Exactly one active grid is not set"
Additional Inherited Members
Protected Attributes inherited from commands.BaseCommand
final String COMMAND_DELIMITER = "\\s+"
Static Protected Attributes inherited from commands.BaseCommand
static String COMMAND_INDICATOR = "liststart"
static String COMMAND_END_INDICATOR = "listend"
static String COMMAND_SEPARATOR = " "
static String VARIABLE_INDICATOR = "variable"
Detailed Description
Author
Rahul Harikrishnan, Duke Kim, $cotty $haw
Definition at line 19 of file HomeCommand.java.
Constructor & Destructor Documentation
commands.viewCommands.HomeCommand.HomeCommand (String command, boolean isExpression) throws BackendException
Definition at line 23 of file HomeCommand.java.
Member Function Documentation
double commands.viewCommands.HomeCommand.onExecute () throws BackendException protected
Definition at line 28 of file HomeCommand.java.
References commands.information.BaseGridContainer.getActiveGrids(), commands.information.BaseTurtleContainer.getActiveTurtles(), commands.turtleCommands.TurtleCommand.getGridContainer(), commands.turtleCommands.TurtleCommand.getTurtleContainer(), commands.information.BaseTurtleContainer.setPosition(), and commands.information.BaseGridContainer.update().
Member Data Documentation
final String commands.viewCommands.HomeCommand.EXACTLY_ONE_ACTIVE_GRID_IS_NOT_SET = "Exactly one active grid is not set" static private
Definition at line 21 of file HomeCommand.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/commands/viewCommands/HomeCommand.java