slogo_team13: turtle.Turtle Class Reference
turtle.Turtle Class Reference
Public Member Functions
Turtle (Position position, Image image)
void setActiveStatus (boolean isActive)
boolean isActive ()
void move (double xPos, double yPos)
void moveTowardsHeading (double increment)
void rotate (double rotateIncrement)
double getOrientation ()
double getXPos ()
double getYPos ()
void setXPos (double xPos)
void setYPos (double yPos)
void setRotation (double rotateVal)
void setPenColor (String color)
void setPenBorderStyle (BorderStyle style)
void setPenWidth (Number thickness)
Line penUndo ()
Pen getPen ()
Position undo ()
void setID (int ID)
int getID ()
void move (KeyCode e)
double setHeading (double absHeading)
double towardsPosition (double newXPos, double newYPos)
double setPosition (double newXPos, double newYPos)
void setVisibility (boolean isVisible)
Private Member Functions
void moveHorizontal (double xIncrement)
void setActive ()
void setInactive ()
void glow ()
void dimmer ()
void moveVertical (double yIncrement)
double[] getXYCoordinates ()
Private Attributes
Position myPosition
Pen myPen
Stack< Position > myPastPositions
int myID
boolean active =false
EventHandler< ActionEvent > myEvent
Static Private Attributes
static final int velocity =5
Detailed Description
Backend Turtle class that has ability to modify its position (location and orientation).
Definition at line 19 of file Turtle.java.
Constructor & Destructor Documentation
turtle.Turtle.Turtle (Position position, Image image)
The Turtle takes a Position object (Composition technique) which encapsulates the data concerning the turtle's movement.
Parameters
position - Position object that stores location information about the Turtle
Definition at line 31 of file Turtle.java.
References turtle.Turtle.setActive().
Member Function Documentation
void turtle.Turtle.dimmer () private
Definition at line 73 of file Turtle.java.
Referenced by turtle.Turtle.setInactive().
int turtle.Turtle.getID ()
Definition at line 179 of file Turtle.java.
References turtle.Turtle.myID.
Referenced by commands.turtleCommands.IDCommand.onExecute().
double turtle.Turtle.getOrientation ()
Implements commands.information.ITurtleBehavior.
Definition at line 113 of file Turtle.java.
References turtle.Position.getRotate().
Referenced by View.SingleGrid.moveTurtle().
Pen turtle.Turtle.getPen ()
Implements commands.information.ITurtleBehavior.
Definition at line 159 of file Turtle.java.
References turtle.Turtle.myPen.
Referenced by View.SingleGrid.addTurtle(), commands.information.BaseTurtleContainer.getPen(), View.SingleGrid.keepTurtleInBounds(), and GUIFunctions.Undo.undoLine().
double turtle.Turtle.getXPos ()
Returns
Current x-coordinate
Implements commands.information.ITurtleBehavior.
Definition at line 119 of file Turtle.java.
References turtle.Position.getXPos().
Referenced by View.SingleGrid.addTurtle(), commands.information.BaseTurtleContainer.getXPos(), turtle.Turtle.getXYCoordinates(), View.SingleGrid.keepTurtleInBounds(), View.SingleGrid.moveTurtle(), and GUIFunctions.StampImage.StampImage().
double [] turtle.Turtle.getXYCoordinates () private
Definition at line 208 of file Turtle.java.
References turtle.Turtle.getXPos(), and turtle.Turtle.getYPos().
Referenced by turtle.Turtle.setPosition(), and turtle.Turtle.towardsPosition().
double turtle.Turtle.getYPos ()
Returns
Current y-coordinate
Implements commands.information.ITurtleBehavior.
Definition at line 126 of file Turtle.java.
References turtle.Position.getYPos().
Referenced by View.SingleGrid.addTurtle(), turtle.Turtle.getXYCoordinates(), commands.information.BaseTurtleContainer.getYPos(), View.SingleGrid.keepTurtleInBounds(), View.SingleGrid.moveTurtle(), and GUIFunctions.StampImage.StampImage().
void turtle.Turtle.glow () private
Definition at line 67 of file Turtle.java.
Referenced by turtle.Turtle.setActive().
boolean turtle.Turtle.isActive ()
Definition at line 76 of file Turtle.java.
References turtle.Turtle.active.
void turtle.Turtle.move (double xPos, double yPos)
Implements commands.information.ITurtleBehavior.
Definition at line 89 of file Turtle.java.
References turtle.Position.getRotate(), turtle.Position.getXPos(), turtle.Position.getYPos(), turtle.Turtle.moveHorizontal(), and turtle.Turtle.moveVertical().
Referenced by View.SingleGrid.addTurtle(), commands.information.BaseTurtleContainer.move(), and View.TurtleMovement.TurtleMovement().
void turtle.Turtle.move (KeyCode e)
Definition at line 183 of file Turtle.java.
References turtle.Position.getRotate(), turtle.Position.getXPos(), turtle.Position.getYPos(), and turtle.Direction.move().
void turtle.Turtle.moveHorizontal (double xIncrement) private
Moves horizontally
Parameters
xIncrement - horizontal movement increment
Definition at line 46 of file Turtle.java.
References turtle.Position.moveHorizontal().
Referenced by turtle.Turtle.move().
void turtle.Turtle.moveTowardsHeading (double increment)
Move amount specified at current heading
Parameters
increment - straight-line distance to be moved
Implements commands.information.ITurtleBehavior.
Definition at line 99 of file Turtle.java.
References turtle.Position.getRotate(), turtle.Position.getXPos(), turtle.Position.getYPos(), and turtle.Position.move().
Referenced by commands.information.BaseTurtleContainer.moveTowardsHeading().
void turtle.Turtle.moveVertical (double yIncrement) private
Moves the vertically
Parameters
yIncrement - vertical movement increment
Definition at line 84 of file Turtle.java.
References turtle.Position.moveVertical().
Referenced by turtle.Turtle.move().
Line turtle.Turtle.penUndo ()
Implements commands.information.ITurtleBehavior.
Definition at line 156 of file Turtle.java.
References View.Pen.undo().
Referenced by commands.information.BaseTurtleContainer.penUndo().
void turtle.Turtle.rotate (double rotateIncrement)
Rotates by increment specified
Parameters
rotateIncrement - degrees of rotation
Implements commands.information.ITurtleBehavior.
Definition at line 109 of file Turtle.java.
References turtle.Position.rotate().
Referenced by commands.information.BaseTurtleContainer.rotate().
void turtle.Turtle.setActive () private
Definition at line 57 of file Turtle.java.
References turtle.Turtle.glow().
Referenced by turtle.Turtle.setActiveStatus(), and turtle.Turtle.Turtle().
void turtle.Turtle.setActiveStatus (boolean isActive)
Definition at line 49 of file Turtle.java.
References turtle.Turtle.setActive(), and turtle.Turtle.setInactive().
Referenced by commands.information.SingleGridTurtleContainer.addTurtle().
double turtle.Turtle.setHeading (double absHeading)
Implements commands.information.ITurtleBehavior.
Definition at line 194 of file Turtle.java.
References turtle.Position.getRotate(), and turtle.Position.setRotation().
void turtle.Turtle.setID (int ID)
Definition at line 175 of file Turtle.java.
Referenced by GUIFunctions.AddTurtle.addAction(), View.SingleGrid.addTurtle(), model.TurtleFactory.createTurtle(), and tests.AskWithTest.setFactory().
void turtle.Turtle.setInactive () private
Definition at line 62 of file Turtle.java.
References turtle.Turtle.dimmer().
Referenced by turtle.Turtle.setActiveStatus().
void turtle.Turtle.setPenBorderStyle (BorderStyle style)
Implements commands.information.ITurtleBehavior.
Definition at line 150 of file Turtle.java.
References View.Pen.setBorderStyle().
Referenced by commands.information.BaseTurtleContainer.setPenBorderStyle().
void turtle.Turtle.setPenColor (String color)
Implements commands.information.ITurtleBehavior.
Definition at line 147 of file Turtle.java.
References View.Pen.setColor().
Referenced by commands.information.BaseTurtleContainer.setPenColor().
void turtle.Turtle.setPenWidth (Number thickness)
Implements commands.information.ITurtleBehavior.
Definition at line 153 of file Turtle.java.
References View.Pen.changeThickness().
Referenced by commands.information.BaseTurtleContainer.setPenWidth().
double turtle.Turtle.setPosition (double newXPos, double newYPos)
Implements commands.information.ITurtleBehavior.
Definition at line 216 of file Turtle.java.
References turtle.Turtle.getXYCoordinates(), turtle.Turtle.setXPos(), and turtle.Turtle.setYPos().
Referenced by commands.information.BaseTurtleContainer.setPosition().
void turtle.Turtle.setRotation (double rotateVal)
Implements commands.information.ITurtleBehavior.
Definition at line 140 of file Turtle.java.
References turtle.Position.setRotation().
Referenced by model.SlogoModel.hardSetTurtle(), commands.information.BaseTurtleContainer.setRotation(), and turtle.Turtle.towardsPosition().
void turtle.Turtle.setVisibility (boolean isVisible)
Implements commands.information.ITurtleBehavior.
Definition at line 224 of file Turtle.java.
Referenced by commands.information.BaseTurtleContainer.setVisibility().
void turtle.Turtle.setXPos (double xPos)
Implements commands.information.ITurtleBehavior.
Definition at line 130 of file Turtle.java.
References turtle.Position.getRotate(), turtle.Position.getXPos(), turtle.Position.getYPos(), and turtle.Position.setXPos().
Referenced by TableInformation.XColumn.doEditingFunction(), model.SlogoModel.hardSetTurtle(), View.SingleGrid.keepTurtleInBounds(), turtle.Turtle.setPosition(), and commands.information.BaseTurtleContainer.setXPos().
void turtle.Turtle.setYPos (double yPos)
Implements commands.information.ITurtleBehavior.
Definition at line 135 of file Turtle.java.
References turtle.Position.setYPos().
Referenced by TableInformation.YColumn.doEditingFunction(), model.SlogoModel.hardSetTurtle(), View.SingleGrid.keepTurtleInBounds(), turtle.Turtle.setPosition(), and commands.information.BaseTurtleContainer.setYPos().
double turtle.Turtle.towardsPosition (double newXPos, double newYPos)
Implements commands.information.ITurtleBehavior.
Definition at line 201 of file Turtle.java.
References turtle.Turtle.getXYCoordinates(), and turtle.Turtle.setRotation().
Position turtle.Turtle.undo ()
Implements commands.information.ITurtleBehavior.
Definition at line 163 of file Turtle.java.
Referenced by commands.information.BaseTurtleContainer.undo().
Member Data Documentation
boolean turtle.Turtle.active =false private
Definition at line 24 of file Turtle.java.
Referenced by turtle.Turtle.isActive().
EventHandler<ActionEvent> turtle.Turtle.myEvent private
Definition at line 25 of file Turtle.java.
int turtle.Turtle.myID private
Definition at line 23 of file Turtle.java.
Referenced by turtle.Turtle.getID().
Stack<Position> turtle.Turtle.myPastPositions private
Definition at line 22 of file Turtle.java.
Pen turtle.Turtle.myPen private
Definition at line 21 of file Turtle.java.
Referenced by turtle.Turtle.getPen().
Position turtle.Turtle.myPosition private
Definition at line 20 of file Turtle.java.
final int turtle.Turtle.velocity =5 static private
Definition at line 26 of file Turtle.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/turtle/Turtle.java