slogo_team13: commands.controlCommands.DoCommand Class Reference
commands.controlCommands.DoCommand Class Reference
Public Member Functions
DoCommand (String userInput, boolean isExpression) throws BackendException
Public Member Functions inherited from commands.ControlCommand
ControlCommand (String userInput, boolean isExpression) throws BackendException
Set< Class<?extends IInformationContainer > > getRequiredInformationTypes ()
void setRequiredInformation (Collection< IInformationContainer > containers) throws BackendException
Public Member Functions inherited from commands.BaseCommand
BaseCommand (String userInput, boolean isExpression) throws BackendException
double execute () throws BackendException
abstract Set< Class<?extends IInformationContainer > > getRequiredInformationTypes ()
abstract void setRequiredInformation (Collection< IInformationContainer > containers) throws BackendException
String getLeftoverString ()
Protected Member Functions
double onExecute () throws BackendException
void parseArguments (String userInput) throws BackendException
Protected Member Functions inherited from commands.ControlCommand
BaseUserDefinedContainer getVariableContainer ()
void reset ()
Protected Member Functions inherited from commands.BaseCommand
abstract double onExecute () throws BackendException
abstract void parseArguments (String userInput) throws BackendException
void setLeftoverCommands (String string) throws BackendException
String[] splitByInnerListCommand (String input)
boolean startsWithCommandStartIndicator (String input)
abstract void reset ()
Private Member Functions
void checkIfVariableExistsPreviously (BaseCommand oldCommand) throws BackendException
Private Attributes
String myVariableName
BaseCommand myLimitCommand
BaseCommand myInternalCommand
BaseUserDefinedContainer myVariableContainer
boolean myVarExistsPreviously
Static Private Attributes
static final String INVALID_COMMAND_ENTERED = "Invalid command entered"
static final String INSUFFICIENT_COMMANDS_ENTERED = "Insufficient commands entered"
Additional Inherited Members
Protected Attributes inherited from commands.BaseCommand
final String COMMAND_DELIMITER = "\\s+"
Static Protected Attributes inherited from commands.ControlCommand
static String COMMAND_INDICATOR = "liststart"
static String COMMAND_END_INDICATOR = "listend"
static String COMMAND_SEPARATOR = " "
static String VARIABLE_INDICATOR = "variable"
Static Protected Attributes inherited from commands.BaseCommand
static String COMMAND_INDICATOR = "liststart"
static String COMMAND_END_INDICATOR = "listend"
static String COMMAND_SEPARATOR = " "
static String VARIABLE_INDICATOR = "variable"
Detailed Description
Author
Rahul Harikrishnan, Duke Kim, $cotty $haw
Definition at line 14 of file DoCommand.java.
Constructor & Destructor Documentation
commands.controlCommands.DoCommand.DoCommand (String userInput, boolean isExpression) throws BackendException
Definition at line 26 of file DoCommand.java.
Member Function Documentation
void commands.controlCommands.DoCommand.checkIfVariableExistsPreviously (BaseCommand oldCommand) throws BackendException private
Definition at line 56 of file DoCommand.java.
References commands.information.BaseUserDefinedContainer.addVariable(), and commands.information.BaseUserDefinedContainer.popOffVariable().
Referenced by commands.controlCommands.DoCommand.onExecute().
double commands.controlCommands.DoCommand.onExecute () throws BackendException protected
Definition at line 31 of file DoCommand.java.
References commands.information.BaseUserDefinedContainer.addVariable(), commands.controlCommands.DoCommand.checkIfVariableExistsPreviously(), commands.information.BaseUserDefinedContainer.containsVariable(), commands.BaseCommand.execute(), commands.information.BaseUserDefinedContainer.getValue(), and commands.ControlCommand.getVariableContainer().
void commands.controlCommands.DoCommand.parseArguments (String userInput) throws BackendException protected
Definition at line 66 of file DoCommand.java.
References commands.ControlCommand.COMMAND_SEPARATOR, commandParser.CommandFactory.createCommand(), commands.BaseCommand.setLeftoverCommands(), commands.BaseCommand.splitByInnerListCommand(), and commands.ControlCommand.VARIABLE_INDICATOR.
Member Data Documentation
final String commands.controlCommands.DoCommand.INSUFFICIENT_COMMANDS_ENTERED = "Insufficient commands entered" static private
Definition at line 17 of file DoCommand.java.
final String commands.controlCommands.DoCommand.INVALID_COMMAND_ENTERED = "Invalid command entered" static private
Definition at line 16 of file DoCommand.java.
BaseCommand commands.controlCommands.DoCommand.myInternalCommand private
Definition at line 21 of file DoCommand.java.
BaseCommand commands.controlCommands.DoCommand.myLimitCommand private
Definition at line 20 of file DoCommand.java.
boolean commands.controlCommands.DoCommand.myVarExistsPreviously private
Definition at line 24 of file DoCommand.java.
BaseUserDefinedContainer commands.controlCommands.DoCommand.myVariableContainer private
Definition at line 23 of file DoCommand.java.
String commands.controlCommands.DoCommand.myVariableName private
Definition at line 19 of file DoCommand.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/commands/controlCommands/DoCommand.java