slogo_team13: GUIFunctions.PenStyle Class Reference
GUIFunctions.PenStyle Class Reference
Public Member Functions
PenStyle (GridTracker grid, String whichStyle)
void doAction ()
void doAction (List<?extends Number > newVal)
void makeMap ()
Public Member Functions inherited from View.PenMenu
PenMenu ()
Public Member Functions inherited from GUIFunctions.GridFunction
GridFunction ()
Private Attributes
HashMap< String, BorderStyle > myStyleMap
String myStyle
Additional Inherited Members
Protected Attributes inherited from GUIFunctions.GridFunction
GridTracker allGrids
Detailed Description
Definition at line 10 of file PenStyle.java.
Constructor & Destructor Documentation
GUIFunctions.PenStyle.PenStyle (GridTracker grid, String whichStyle)
Definition at line 14 of file PenStyle.java.
References GUIFunctions.GridFunction.allGrids, and GUIFunctions.PenStyle.makeMap().
Member Function Documentation
void GUIFunctions.PenStyle.doAction ()
Implements GUIFunctions.GUIFunction.
Definition at line 21 of file PenStyle.java.
References GUIFunctions.GridFunction.allGrids, View.GridTracker.getActiveGrid(), and View.SingleGrid.getActivePens().
void GUIFunctions.PenStyle.doAction (List<?extends Number > newVal)
Implements GUIFunctions.GUIFunction.
Definition at line 28 of file PenStyle.java.
void GUIFunctions.PenStyle.makeMap ()
Definition at line 32 of file PenStyle.java.
Referenced by GUIFunctions.PenStyle.PenStyle().
Member Data Documentation
String GUIFunctions.PenStyle.myStyle private
Definition at line 12 of file PenStyle.java.
HashMap<String, BorderStyle> GUIFunctions.PenStyle.myStyleMap private
Definition at line 11 of file PenStyle.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/GUIFunctions/PenStyle.java