slogo_team13: commands.information.BaseTurtleContainer Class Reference
commands.information.BaseTurtleContainer Class Reference abstract
Classes
interface TurtleActionWithResult
Public Member Functions
abstract void removeTurtle (int turtleID)
abstract void addTurtle (Turtle turtle, boolean isActive)
abstract Collection< Turtle > getAllTurtles ()
abstract Collection< Integer > getActiveTurtlesByID ()
abstract void hardSetActiveTurtles (Collection< Integer > turtleIDs)
abstract Collection< Turtle > getActiveTurtles ()
abstract Collection< Integer > getAllTurtlesByID ()
abstract void clear ()
void rotate (double rotateIncrement)
void move (double xIncrement, double yIncrement)
double setHeading (double absHeading)
double towardsPosition (double newXPos, double newYPos)
double setPosition (double newXPos, double newYPos)
void moveTowardsHeading (double increment)
double getOrientation ()
double getXPos ()
double getYPos ()
void setXPos (double xPos)
void setYPos (double yPos)
void setRotation (double rotateVal)
void setPenColor (String color)
void setPenBorderStyle (BorderStyle style)
void setPenWidth (Number thickness)
Line penUndo ()
Pen getPen ()
Position undo ()
void setVisibility (boolean isVisible)
abstract void setTurtleAsActive (int turtleID)
Private Member Functions
Object loopOverTurtle (TurtleActionWithResult action)
Detailed Description
Author
Rahul Harikrishnan, Duke Kim, $cotty $haw
    The Base Turtle Container contains all the turtles in each grid and
    defines the allowed behaviors for each container
Definition at line 17 of file BaseTurtleContainer.java.
Member Function Documentation
abstract void commands.information.BaseTurtleContainer.addTurtle (Turtle turtle, boolean isActive) abstract
Adds a turtle to the container;
Parameters
turtle Turtle to add.
isActive Whether it is active or not
Referenced by commands.turtleCommands.MultipleTurtleCommand.addFutureActiveTurtleTurtles(), communicator.MainController.addTurtle(), and tests.AskWithTest.setFactory().
abstract void commands.information.BaseTurtleContainer.clear () abstract
Sets all turtles in the container as inactive.
Referenced by commands.viewCommands.ClearScreenCommand.onExecute().
abstract Collection<Turtle> commands.information.BaseTurtleContainer.getActiveTurtles () abstract
Gets all active turtles
Returns
All active turtles
Referenced by communicator.MainController.getActiveTurtles(), commands.information.BaseTurtleContainer.loopOverTurtle(), commands.turtleCommands.BackCommand.onExecute(), commands.turtleCommands.LeftCommand.onExecute(), commands.turtleCommands.RightCommand.onExecute(), commands.turtleCommands.ForwardCommand.onExecute(), commands.turtleCommands.SetHeadingCommand.onExecute(), commands.turtleCommands.IDCommand.onExecute(), commands.viewCommands.ClearScreenCommand.onExecute(), commands.turtleCommands.SetPositionCommand.onExecute(), commands.turtleCommands.TowardsCommand.onExecute(), and commands.viewCommands.HomeCommand.onExecute().
abstract Collection<Integer> commands.information.BaseTurtleContainer.getActiveTurtlesByID () abstract
Gets all active turtles by their IDs.
Returns
IDs of all active turtles.
Referenced by commands.turtleCommands.AskCommand.onExecute(), and commands.turtleCommands.AskWithCommand.onExecute().
abstract Collection<Turtle> commands.information.BaseTurtleContainer.getAllTurtles () abstract
Gets all turtles in the container
Returns
All turtles in the container
Referenced by commands.turtleCommands.NumberOfTurtlesCommand.onExecute(), tests.AskWithTest.testAlwaysTrueAskWith(), tests.AskTest.testThatAskCreatesTurtles(), and tests.AskWithTest.testXCorAskWith().
abstract Collection<Integer> commands.information.BaseTurtleContainer.getAllTurtlesByID () abstract
Gets all active turtles by their IDs
Returns
IDs of all active turtles
Referenced by commands.turtleCommands.MultipleTurtleCommand.addFutureActiveTurtleTurtles(), and commands.turtleCommands.AskWithCommand.onExecute().
double commands.information.BaseTurtleContainer.getOrientation ()
Implements commands.information.ITurtleBehavior.
Definition at line 134 of file BaseTurtleContainer.java.
References commands.information.BaseTurtleContainer.loopOverTurtle().
Referenced by commands.viewQueries.HeadingQuery.onExecute().
Pen commands.information.BaseTurtleContainer.getPen ()
Implements commands.information.ITurtleBehavior.
Definition at line 193 of file BaseTurtleContainer.java.
References turtle.Turtle.getPen(), and commands.information.BaseTurtleContainer.loopOverTurtle().
double commands.information.BaseTurtleContainer.getXPos ()
Implements commands.information.ITurtleBehavior.
Definition at line 139 of file BaseTurtleContainer.java.
References turtle.Turtle.getXPos(), and commands.information.BaseTurtleContainer.loopOverTurtle().
Referenced by commands.viewQueries.XCorQuery.onExecute().
double commands.information.BaseTurtleContainer.getYPos ()
Implements commands.information.ITurtleBehavior.
Definition at line 143 of file BaseTurtleContainer.java.
References turtle.Turtle.getYPos(), and commands.information.BaseTurtleContainer.loopOverTurtle().
Referenced by commands.viewQueries.YCorQuery.onExecute().
abstract void commands.information.BaseTurtleContainer.hardSetActiveTurtles (Collection< Integer > turtleIDs) abstract
Hard sets the active turtles to be the ones passed in. Active turtles from before will be set as inactive.
Parameters
turtleIDs
Referenced by commands.turtleCommands.MultipleTurtleCommand.addFutureActiveTurtleTurtles(), commands.turtleCommands.AskCommand.onExecute(), and commands.turtleCommands.AskWithCommand.onExecute().
Object commands.information.BaseTurtleContainer.loopOverTurtle (TurtleActionWithResult action) private
Performs specified action on all active turtles.
Parameters
action Action to be performed
Returns
Return value of action
Definition at line 88 of file BaseTurtleContainer.java.
References commands.information.BaseTurtleContainer.TurtleActionWithResult.execute(), and commands.information.BaseTurtleContainer.getActiveTurtles().
Referenced by commands.information.BaseTurtleContainer.getOrientation(), commands.information.BaseTurtleContainer.getPen(), commands.information.BaseTurtleContainer.getXPos(), commands.information.BaseTurtleContainer.getYPos(), commands.information.BaseTurtleContainer.move(), commands.information.BaseTurtleContainer.moveTowardsHeading(), commands.information.BaseTurtleContainer.penUndo(), commands.information.BaseTurtleContainer.rotate(), commands.information.BaseTurtleContainer.setHeading(), commands.information.BaseTurtleContainer.setPenBorderStyle(), commands.information.BaseTurtleContainer.setPenColor(), commands.information.BaseTurtleContainer.setPenWidth(), commands.information.BaseTurtleContainer.setPosition(), commands.information.BaseTurtleContainer.setRotation(), commands.information.BaseTurtleContainer.setVisibility(), commands.information.BaseTurtleContainer.setXPos(), commands.information.BaseTurtleContainer.setYPos(), commands.information.BaseTurtleContainer.towardsPosition(), and commands.information.BaseTurtleContainer.undo().
void commands.information.BaseTurtleContainer.move (double xIncrement, double yIncrement)
Implements commands.information.ITurtleBehavior.
Definition at line 105 of file BaseTurtleContainer.java.
References commands.information.BaseTurtleContainer.loopOverTurtle(), and turtle.Turtle.move().
void commands.information.BaseTurtleContainer.moveTowardsHeading (double increment)
Implements commands.information.ITurtleBehavior.
Definition at line 127 of file BaseTurtleContainer.java.
References commands.information.BaseTurtleContainer.loopOverTurtle(), and turtle.Turtle.moveTowardsHeading().
Referenced by commands.turtleCommands.BackCommand.onExecute(), and commands.turtleCommands.ForwardCommand.onExecute().
Line commands.information.BaseTurtleContainer.penUndo ()
Implements commands.information.ITurtleBehavior.
Definition at line 189 of file BaseTurtleContainer.java.
References commands.information.BaseTurtleContainer.loopOverTurtle(), and turtle.Turtle.penUndo().
abstract void commands.information.BaseTurtleContainer.removeTurtle (int turtleID) abstract
Removes a specific turtle by its ID.
Parameters
turtleID ID of turtle to remove.
void commands.information.BaseTurtleContainer.rotate (double rotateIncrement)
Implements commands.information.ITurtleBehavior.
Definition at line 97 of file BaseTurtleContainer.java.
References commands.information.BaseTurtleContainer.loopOverTurtle(), and turtle.Turtle.rotate().
Referenced by commands.turtleCommands.LeftCommand.onExecute(), and commands.turtleCommands.RightCommand.onExecute().
double commands.information.BaseTurtleContainer.setHeading (double absHeading)
Implements commands.information.ITurtleBehavior.
Definition at line 112 of file BaseTurtleContainer.java.
References commands.information.BaseTurtleContainer.loopOverTurtle().
Referenced by commands.turtleCommands.SetHeadingCommand.onExecute().
void commands.information.BaseTurtleContainer.setPenBorderStyle (BorderStyle style)
Implements commands.information.ITurtleBehavior.
Definition at line 175 of file BaseTurtleContainer.java.
References commands.information.BaseTurtleContainer.loopOverTurtle(), and turtle.Turtle.setPenBorderStyle().
void commands.information.BaseTurtleContainer.setPenColor (String color)
Implements commands.information.ITurtleBehavior.
Definition at line 168 of file BaseTurtleContainer.java.
References commands.information.BaseTurtleContainer.loopOverTurtle(), and turtle.Turtle.setPenColor().
void commands.information.BaseTurtleContainer.setPenWidth (Number thickness)
Implements commands.information.ITurtleBehavior.
Definition at line 182 of file BaseTurtleContainer.java.
References commands.information.BaseTurtleContainer.loopOverTurtle(), and turtle.Turtle.setPenWidth().
double commands.information.BaseTurtleContainer.setPosition (double newXPos, double newYPos)
Implements commands.information.ITurtleBehavior.
Definition at line 122 of file BaseTurtleContainer.java.
References commands.information.BaseTurtleContainer.loopOverTurtle(), and turtle.Turtle.setPosition().
Referenced by commands.viewCommands.ClearScreenCommand.onExecute(), commands.turtleCommands.SetPositionCommand.onExecute(), and commands.viewCommands.HomeCommand.onExecute().
void commands.information.BaseTurtleContainer.setRotation (double rotateVal)
Implements commands.information.ITurtleBehavior.
Definition at line 161 of file BaseTurtleContainer.java.
References commands.information.BaseTurtleContainer.loopOverTurtle(), and turtle.Turtle.setRotation().
abstract void commands.information.BaseTurtleContainer.setTurtleAsActive (int turtleID) abstract
Referenced by communicator.MainController.setTurtleAsActive().
void commands.information.BaseTurtleContainer.setVisibility (boolean isVisible)
Implements commands.information.ITurtleBehavior.
Definition at line 202 of file BaseTurtleContainer.java.
References commands.information.BaseTurtleContainer.loopOverTurtle(), and turtle.Turtle.setVisibility().
Referenced by commands.viewCommands.HideTurtleCommand.onExecute(), and commands.viewCommands.ShowTurtleCommand.onExecute().
void commands.information.BaseTurtleContainer.setXPos (double xPos)
Implements commands.information.ITurtleBehavior.
Definition at line 147 of file BaseTurtleContainer.java.
References commands.information.BaseTurtleContainer.loopOverTurtle(), and turtle.Turtle.setXPos().
void commands.information.BaseTurtleContainer.setYPos (double yPos)
Implements commands.information.ITurtleBehavior.
Definition at line 154 of file BaseTurtleContainer.java.
References commands.information.BaseTurtleContainer.loopOverTurtle(), and turtle.Turtle.setYPos().
double commands.information.BaseTurtleContainer.towardsPosition (double newXPos, double newYPos)
Implements commands.information.ITurtleBehavior.
Definition at line 117 of file BaseTurtleContainer.java.
References commands.information.BaseTurtleContainer.loopOverTurtle().
Referenced by commands.turtleCommands.TowardsCommand.onExecute().
Position commands.information.BaseTurtleContainer.undo ()
Implements commands.information.ITurtleBehavior.
Definition at line 197 of file BaseTurtleContainer.java.
References commands.information.BaseTurtleContainer.loopOverTurtle(), and turtle.Turtle.undo().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/commands/information/BaseTurtleContainer.java