slogo_team13: commandParser.CommandToClassTranslator Class Reference
commandParser.CommandToClassTranslator Class Reference
Public Member Functions
Map< String, Class > translateCommandToClass (File file) throws BackendException
Static Private Attributes
static final String INVALID_PROPERTIES_FILE = "Language file is not a valid .properties file"
static final String CLASS_NOT_FOUND = "Class Not Found"
Additional Inherited Members
Protected Member Functions inherited from commandParser.PropertiesFileReader
ResourceBundle getBundle (File file) throws MalformedURLException
String getFileNameWithoutExtension (File file)
Detailed Description
Author
Rahul Harikrishnan, Duke Kim, $cotty $haw
Definition at line 19 of file CommandToClassTranslator.java.
Member Function Documentation
Map<String, Class> commandParser.CommandToClassTranslator.translateCommandToClass (File file) throws BackendException
Definition at line 24 of file CommandToClassTranslator.java.
References commandParser.PropertiesFileReader.getBundle().
Referenced by tests.AskTest.processInput(), tests.TurtleCommandsTest.processInput(), and tests.AskWithTest.processInput().
Member Data Documentation
final String commandParser.CommandToClassTranslator.CLASS_NOT_FOUND = "Class Not Found" static private
Definition at line 22 of file CommandToClassTranslator.java.
final String commandParser.CommandToClassTranslator.INVALID_PROPERTIES_FILE = "Language file is not a valid .properties file" static private
Definition at line 21 of file CommandToClassTranslator.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/commandParser/CommandToClassTranslator.java