slogo_team13: commands.variableCommands.VariableCommand Class Reference
commands.variableCommands.VariableCommand Class Reference abstract
Public Member Functions
VariableCommand (String userInput, boolean isExpression) throws BackendException
Set< Class<?extends IInformationContainer > > getRequiredInformationTypes ()
void setRequiredInformation (Collection< IInformationContainer > containers)
Public Member Functions inherited from commands.BaseCommand
BaseCommand (String userInput, boolean isExpression) throws BackendException
double execute () throws BackendException
abstract Set< Class<?extends IInformationContainer > > getRequiredInformationTypes ()
abstract void setRequiredInformation (Collection< IInformationContainer > containers) throws BackendException
String getLeftoverString ()
Protected Member Functions
BaseUserDefinedContainer getVariableContainer ()
void reset ()
Protected Member Functions inherited from commands.BaseCommand
abstract double onExecute () throws BackendException
abstract void parseArguments (String userInput) throws BackendException
void setLeftoverCommands (String string) throws BackendException
String[] splitByInnerListCommand (String input)
boolean startsWithCommandStartIndicator (String input)
abstract void reset ()
Private Attributes
SlogoView myView
Turtle myTurtle
BaseUserDefinedContainer myVariableContainer
Additional Inherited Members
Protected Attributes inherited from commands.BaseCommand
final String COMMAND_DELIMITER = "\\s+"
Static Protected Attributes inherited from commands.BaseCommand
static String COMMAND_INDICATOR = "liststart"
static String COMMAND_END_INDICATOR = "listend"
static String COMMAND_SEPARATOR = " "
static String VARIABLE_INDICATOR = "variable"
Detailed Description
Author
Rahul Harikrishnan, Duke Kim, $cotty $haw
Definition at line 20 of file VariableCommand.java.
Constructor & Destructor Documentation
commands.variableCommands.VariableCommand.VariableCommand (String userInput, boolean isExpression) throws BackendException
Definition at line 26 of file VariableCommand.java.
Member Function Documentation
Set<Class<? extends IInformationContainer> > commands.variableCommands.VariableCommand.getRequiredInformationTypes ()
Definition at line 31 of file VariableCommand.java.
BaseUserDefinedContainer commands.variableCommands.VariableCommand.getVariableContainer () protected
Definition at line 52 of file VariableCommand.java.
References commands.variableCommands.VariableCommand.myVariableContainer.
Referenced by commands.variableCommands.GetVariableCommand.onExecute(), commands.variableCommands.SetVariableCommand.onExecute(), commands.variableCommands.CreatedCommand.revertVariables(), and commands.variableCommands.CreatedCommand.setNewVariables().
void commands.variableCommands.VariableCommand.reset () protected
Definition at line 57 of file VariableCommand.java.
void commands.variableCommands.VariableCommand.setRequiredInformation (Collection< IInformationContainer > containers)
Definition at line 37 of file VariableCommand.java.
Member Data Documentation
Turtle commands.variableCommands.VariableCommand.myTurtle private
Definition at line 23 of file VariableCommand.java.
BaseUserDefinedContainer commands.variableCommands.VariableCommand.myVariableContainer private
Definition at line 24 of file VariableCommand.java.
Referenced by commands.variableCommands.VariableCommand.getVariableContainer().
SlogoView commands.variableCommands.VariableCommand.myView private
Definition at line 22 of file VariableCommand.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/commands/variableCommands/VariableCommand.java