slogo_team13: commands.ViewCommand Class Reference
commands.ViewCommand Class Reference abstract
Public Member Functions
ViewCommand (String command, boolean isExpression) throws BackendException
Set< Class<?extends IInformationContainer > > getRequiredInformationTypes ()
void setRequiredInformation (Collection< IInformationContainer > containers) throws BackendException
Public Member Functions inherited from commands.BaseCommand
BaseCommand (String userInput, boolean isExpression) throws BackendException
double execute () throws BackendException
abstract Set< Class<?extends IInformationContainer > > getRequiredInformationTypes ()
abstract void setRequiredInformation (Collection< IInformationContainer > containers) throws BackendException
String getLeftoverString ()
Protected Member Functions
BaseGridContainer getGridContainer ()
void parseArguments (String userInput) throws BackendException
BaseCommand[] getExpressionList ()
abstract int getArgumentCount ()
void reset ()
Protected Member Functions inherited from commands.BaseCommand
abstract double onExecute () throws BackendException
abstract void parseArguments (String userInput) throws BackendException
void setLeftoverCommands (String string) throws BackendException
String[] splitByInnerListCommand (String input)
boolean startsWithCommandStartIndicator (String input)
abstract void reset ()
Private Attributes
BaseGridContainer myGridContainer
BaseCommand[] myArgumentList
Static Private Attributes
static final String INVALID_EXTENSION_OF_GRID_CONTAINER = "Invalid extension of Grid Container"
static final String INVALID_CONTAINERS_RECEIVED = "Invalid containers received"
static final String INVALID_NUMBER_OF_ARGUMENTS_PROVIDED = "Invalid number of arguments provided"
Additional Inherited Members
Protected Attributes inherited from commands.BaseCommand
final String COMMAND_DELIMITER = "\\s+"
Static Protected Attributes inherited from commands.BaseCommand
static String COMMAND_INDICATOR = "liststart"
static String COMMAND_END_INDICATOR = "listend"
static String COMMAND_SEPARATOR = " "
static String VARIABLE_INDICATOR = "variable"
Detailed Description
Author
Rahul Harikrishnan, Duke Kim, $cotty $haw
View command that extends BaseCommand, and whose sole purpose is to update the view.
Definition at line 19 of file ViewCommand.java.
Constructor & Destructor Documentation
commands.ViewCommand.ViewCommand (String command, boolean isExpression) throws BackendException
Definition at line 27 of file ViewCommand.java.
Member Function Documentation
abstract int commands.ViewCommand.getArgumentCount () abstract protected
Referenced by commands.ViewCommand.parseArguments().
BaseCommand [] commands.ViewCommand.getExpressionList () protected
Definition at line 84 of file ViewCommand.java.
References commands.ViewCommand.myArgumentList.
Referenced by commands.viewCommands.SetBackgroundCommand.onExecute(), commands.viewCommands.SetShapeCommand.onExecute(), commands.viewCommands.SetPenSizeCommand.onExecute(), commands.viewCommands.SetPenColorCommand.onExecute(), and commands.viewCommands.SetPaletteCommand.onExecute().
BaseGridContainer commands.ViewCommand.getGridContainer () protected
Definition at line 52 of file ViewCommand.java.
References commands.ViewCommand.myGridContainer.
Referenced by commands.viewCommands.ClearStampsCommand.onExecute(), commands.viewCommands.StampCommand.onExecute(), commands.viewCommands.PenDownCommand.onExecute(), commands.viewQueries.PenColorQuery.onExecute(), commands.viewQueries.PenDownQuery.onExecute(), commands.viewCommands.PenUpCommand.onExecute(), commands.viewQueries.ShowingQuery.onExecute(), commands.viewCommands.SetPenSizeCommand.onExecute(), commands.viewCommands.SetPenColorCommand.onExecute(), commands.viewCommands.SetShapeCommand.onExecute(), commands.viewCommands.SetBackgroundCommand.onExecute(), commands.viewQueries.ShapeQuery.onExecute(), and commands.viewCommands.SetPaletteCommand.onExecute().
Set<Class<? extends IInformationContainer> > commands.ViewCommand.getRequiredInformationTypes ()
Definition at line 32 of file ViewCommand.java.
void commands.ViewCommand.parseArguments (String userInput) throws BackendException protected
Definition at line 57 of file ViewCommand.java.
References commandParser.CommandFactory.createCommand(), commands.ViewCommand.getArgumentCount(), commands.BaseCommand.getLeftoverString(), and commands.BaseCommand.setLeftoverCommands().
void commands.ViewCommand.reset () protected
Definition at line 91 of file ViewCommand.java.
void commands.ViewCommand.setRequiredInformation (Collection< IInformationContainer > containers) throws BackendException
Definition at line 38 of file ViewCommand.java.
Member Data Documentation
final String commands.ViewCommand.INVALID_CONTAINERS_RECEIVED = "Invalid containers received" static private
Definition at line 22 of file ViewCommand.java.
final String commands.ViewCommand.INVALID_EXTENSION_OF_GRID_CONTAINER = "Invalid extension of Grid Container" static private
Definition at line 21 of file ViewCommand.java.
final String commands.ViewCommand.INVALID_NUMBER_OF_ARGUMENTS_PROVIDED = "Invalid number of arguments provided" static private
Definition at line 23 of file ViewCommand.java.
BaseCommand [] commands.ViewCommand.myArgumentList private
Definition at line 25 of file ViewCommand.java.
Referenced by commands.ViewCommand.getExpressionList().
BaseGridContainer commands.ViewCommand.myGridContainer private
Definition at line 24 of file ViewCommand.java.
Referenced by commands.ViewCommand.getGridContainer().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/commands/ViewCommand.java