slogo_team13: turtle.Direction Class Reference
turtle.Direction Class Reference
Public Member Functions
Direction (KeyCode e)
Position move (Position p, int speed)
void makeDirectionMap ()
Public Attributes
HashMap< KeyCode, MoveDirection > myDirections =new HashMap<KeyCode, MoveDirection>()
Private Attributes
MoveDirection direction
Detailed Description
Definition at line 7 of file Direction.java.
Constructor & Destructor Documentation
turtle.Direction.Direction (KeyCode e)
Definition at line 10 of file Direction.java.
References turtle.Direction.makeDirectionMap().
Member Function Documentation
void turtle.Direction.makeDirectionMap ()
Definition at line 20 of file Direction.java.
Referenced by turtle.Direction.Direction().
Position turtle.Direction.move (Position p, int speed)
Definition at line 17 of file Direction.java.
References turtle.MoveDirection.move().
Referenced by turtle.Turtle.move().
Member Data Documentation
MoveDirection turtle.Direction.direction private
Definition at line 8 of file Direction.java.
HashMap<KeyCode, MoveDirection> turtle.Direction.myDirections =new HashMap<KeyCode, MoveDirection>()
Definition at line 9 of file Direction.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/turtle/Direction.java