slogo_team13: model.SlogoModel Class Reference
model.SlogoModel Class Reference
Public Member Functions
void initializeModel ()
void hardSetTurtle (double x, double y, double orientationAngle)
void initializeTurtle (Image image)
List< Turtle > getActiveTurtles ()
Turtle findTurtle (int ID)
Private Attributes
Turtle myTurtle
BaseUserDefinedContainer myVariableContainer
TurtleFactory myTurtleFactory
Static Private Attributes
static final String INITIAL_TURTLE_SPRITE = "bowser.png"
Detailed Description
Author
Rahul Harikrishnan, Duke Kim, $cotty $haw
Definition at line 15 of file SlogoModel.java.
Member Function Documentation
Turtle model.SlogoModel.findTurtle (int ID)
Definition at line 39 of file SlogoModel.java.
References model.TurtleFactory.findTurtle().
List<Turtle> model.SlogoModel.getActiveTurtles ()
Definition at line 35 of file SlogoModel.java.
References model.TurtleFactory.getActiveTurtles().
void model.SlogoModel.hardSetTurtle (double x, double y, double orientationAngle)
Definition at line 25 of file SlogoModel.java.
References turtle.Turtle.setRotation(), turtle.Turtle.setXPos(), and turtle.Turtle.setYPos().
void model.SlogoModel.initializeModel ()
Definition at line 20 of file SlogoModel.java.
References model.SlogoModel.initializeTurtle().
void model.SlogoModel.initializeTurtle (Image image)
Definition at line 31 of file SlogoModel.java.
References model.TurtleFactory.createTurtle().
Referenced by model.SlogoModel.initializeModel().
Member Data Documentation
final String model.SlogoModel.INITIAL_TURTLE_SPRITE = "bowser.png" static private
Definition at line 16 of file SlogoModel.java.
Turtle model.SlogoModel.myTurtle private
Definition at line 17 of file SlogoModel.java.
TurtleFactory model.SlogoModel.myTurtleFactory private
Definition at line 19 of file SlogoModel.java.
BaseUserDefinedContainer model.SlogoModel.myVariableContainer private
Definition at line 18 of file SlogoModel.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/model/SlogoModel.java