slogo_team13: commands.ControlCommand Class Reference
commands.ControlCommand Class Reference abstract
Public Member Functions
ControlCommand (String userInput, boolean isExpression) throws BackendException
Set< Class<?extends IInformationContainer > > getRequiredInformationTypes ()
void setRequiredInformation (Collection< IInformationContainer > containers) throws BackendException
Public Member Functions inherited from commands.BaseCommand
BaseCommand (String userInput, boolean isExpression) throws BackendException
double execute () throws BackendException
abstract Set< Class<?extends IInformationContainer > > getRequiredInformationTypes ()
abstract void setRequiredInformation (Collection< IInformationContainer > containers) throws BackendException
String getLeftoverString ()
Protected Member Functions
BaseUserDefinedContainer getVariableContainer ()
void reset ()
Protected Member Functions inherited from commands.BaseCommand
abstract double onExecute () throws BackendException
abstract void parseArguments (String userInput) throws BackendException
void setLeftoverCommands (String string) throws BackendException
String[] splitByInnerListCommand (String input)
boolean startsWithCommandStartIndicator (String input)
abstract void reset ()
Static Protected Attributes
static String COMMAND_INDICATOR = "liststart"
static String COMMAND_END_INDICATOR = "listend"
static String COMMAND_SEPARATOR = " "
static String VARIABLE_INDICATOR = "variable"
Static Protected Attributes inherited from commands.BaseCommand
static String COMMAND_INDICATOR = "liststart"
static String COMMAND_END_INDICATOR = "listend"
static String COMMAND_SEPARATOR = " "
static String VARIABLE_INDICATOR = "variable"
Private Attributes
BaseUserDefinedContainer myVariableContainer
Static Private Attributes
static final String INVALID_CONTAINERS_RECEIVED
static final String INVALID_EXTENSION_OF_VARIABLE_CONTAINER
Additional Inherited Members
Protected Attributes inherited from commands.BaseCommand
final String COMMAND_DELIMITER = "\\s+"
Detailed Description
Commands for control structure. Has access to BaseUserDefinedContainer
Author
Rahul Harikrishnan, Duke Kim, $cotty $haw
Definition at line 17 of file ControlCommand.java.
Constructor & Destructor Documentation
commands.ControlCommand.ControlCommand (String userInput, boolean isExpression) throws BackendException
Definition at line 29 of file ControlCommand.java.
Member Function Documentation
Set<Class<? extends IInformationContainer> > commands.ControlCommand.getRequiredInformationTypes ()
Definition at line 34 of file ControlCommand.java.
BaseUserDefinedContainer commands.ControlCommand.getVariableContainer () protected
Definition at line 56 of file ControlCommand.java.
References commands.ControlCommand.myVariableContainer.
Referenced by commands.controlCommands.DoCommand.onExecute(), commands.controlCommands.ForCommand.onExecute(), and commands.controlCommands.ToCommand.onExecute().
void commands.ControlCommand.reset () protected
Definition at line 61 of file ControlCommand.java.
void commands.ControlCommand.setRequiredInformation (Collection< IInformationContainer > containers) throws BackendException
Definition at line 40 of file ControlCommand.java.
Member Data Documentation
String commands.ControlCommand.COMMAND_END_INDICATOR = "listend" static protected
Definition at line 24 of file ControlCommand.java.
String commands.ControlCommand.COMMAND_INDICATOR = "liststart" static protected
Definition at line 23 of file ControlCommand.java.
String commands.ControlCommand.COMMAND_SEPARATOR = " " static protected
Definition at line 25 of file ControlCommand.java.
Referenced by commands.controlCommands.ToCommand.parseArguments(), commands.controlCommands.ForCommand.parseArguments(), and commands.controlCommands.DoCommand.parseArguments().
final String commands.ControlCommand.INVALID_CONTAINERS_RECEIVED static private
Initial value:
=
            "Invalid containers received"
Definition at line 19 of file ControlCommand.java.
final String commands.ControlCommand.INVALID_EXTENSION_OF_VARIABLE_CONTAINER static private
Initial value:
=
            "Invalid extension of Variable Container"
Definition at line 21 of file ControlCommand.java.
BaseUserDefinedContainer commands.ControlCommand.myVariableContainer private
Definition at line 27 of file ControlCommand.java.
Referenced by commands.ControlCommand.getVariableContainer().
String commands.ControlCommand.VARIABLE_INDICATOR = "variable" static protected
Definition at line 26 of file ControlCommand.java.
Referenced by commands.controlCommands.ForCommand.parseArguments(), and commands.controlCommands.DoCommand.parseArguments().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/commands/ControlCommand.java