slogo_team13: commands.information.IInformationGateway Interface Reference
commands.information.IInformationGateway Interface Reference
Public Member Functions
IInformationContainer getContainer (Class<?extends IInformationContainer > containerType)
Collection< IInformationContainer > getContainers (Set< Class<?extends IInformationContainer >> containerTypes) throws BackendException
void addContainer (IInformationContainer container) throws BackendException
Detailed Description
Author
Duke The central point for all information related to the backend of the program, mostly the information required for commands. The reason for the existence of this class is to limit information access in the extending commands, in order to limit room for error for those wanting to extend commands more specific than BaseCommand, such as TurtleCommands, ControlCommands etc. At the same time, by providing a central point of information, it not only allows method command execution method signatures to be general, but also streamlines how data is accessed, which would ideally limit repeated data.
Definition at line 20 of file IInformationGateway.java.
Member Function Documentation
void commands.information.IInformationGateway.addContainer (IInformationContainer container) throws BackendException
Adds a container to the gateway.
Parameters
container Container to be added
Exceptions
BackendException Any exception while adding container
Implemented in commands.information.SingleGridInformationGateway.
Referenced by communicator.MainController.loadPreferences().
IInformationContainer commands.information.IInformationGateway.getContainer (Class<?extends IInformationContainer > containerType)
Gets the container corresponding to the requested container type
Parameters
containerType The type of container to get.
Returns
The requested information container
Implemented in commands.information.SingleGridInformationGateway.
Referenced by communicator.MainController.getTurtleContainer().
Collection<IInformationContainer> commands.information.IInformationGateway.getContainers (Set< Class<?extends IInformationContainer >> containerTypes) throws BackendException
Gets a collection of containers corresponding to the requested container types.
Parameters
containerTypes The types of containers to get.
Returns
Collection of requested information containers.
Exceptions
BackendException Any exception to be thrown.
Implemented in commands.information.SingleGridInformationGateway.
Referenced by commandParser.CommandFactory.createCommand().
The documentation for this interface was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/commands/information/IInformationGateway.java