slogo_team13: View.PenScrollingBar Class Reference
View.PenScrollingBar Class Reference
Public Member Functions
PenScrollingBar (String myLabel, int x, int y, int height, int width, int min, int max, int value, GUIFunction myFunction)
PenScrollingBar (String myLabel, int x, int y, GUIFunction myFunction)
void addEvent (EventHandler< ActionEvent > handler)
Public Member Functions inherited from View.ScrollingBar
ScrollingBar (String myLabel, int x, int y, int height, int width, int min, int max, int value, GUIFunction function)
Private Member Functions
ChangeListener< Number > addEvent ()
void setFocus ()
Additional Inherited Members
Protected Attributes inherited from View.ScrollingBar
int myX
int myY
int myHeight
int myWidth
GUIFunction myFunction
Slider myBar
Detailed Description
Definition at line 15 of file PenScrollingBar.java.
Constructor & Destructor Documentation
View.PenScrollingBar.PenScrollingBar (String myLabel, int x, int y, int height, int width, int min, int max, int value, GUIFunction myFunction)
Definition at line 17 of file PenScrollingBar.java.
References View.PenScrollingBar.setFocus().
View.PenScrollingBar.PenScrollingBar (String myLabel, int x, int y, GUIFunction myFunction)
Definition at line 23 of file PenScrollingBar.java.
References View.PenScrollingBar.setFocus().
Member Function Documentation
void View.PenScrollingBar.addEvent (EventHandler< ActionEvent > handler)
Creates an object on the GUI that the user can interact with
Parameters
handler ActionEvent for the object to react to
Implements View.UserObjects.
Definition at line 30 of file PenScrollingBar.java.
ChangeListener<Number> View.PenScrollingBar.addEvent () private
Definition at line 32 of file PenScrollingBar.java.
References GUIFunctions.GUIFunction.doAction(), and View.ScrollingBar.myFunction.
Referenced by View.PenScrollingBar.setFocus().
void View.PenScrollingBar.setFocus () private
Definition at line 43 of file PenScrollingBar.java.
References View.PenScrollingBar.addEvent(), and View.ScrollingBar.myBar.
Referenced by View.PenScrollingBar.PenScrollingBar().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/View/PenScrollingBar.java