slogo_team13: GUIFunctions.AddTurtle Class Reference
GUIFunctions.AddTurtle Class Reference
Public Member Functions
AddTurtle (GridTracker grid)
void doAction ()
void doAction (List<?extends Number > newVal)
Object addAction ()
Public Member Functions inherited from GUIFunctions.Add
void doAction ()
void doAction (List<?extends Number > newVal)
abstract Object addAction ()
Private Attributes
Turtle myTurtle
GridTracker myGrid
Detailed Description
Definition at line 12 of file AddTurtle.java.
Constructor & Destructor Documentation
GUIFunctions.AddTurtle.AddTurtle (GridTracker grid)
Definition at line 15 of file AddTurtle.java.
Member Function Documentation
Object GUIFunctions.AddTurtle.addAction ()
Definition at line 29 of file AddTurtle.java.
References View.GridTracker.getActiveGrid(), View.SingleGrid.getAllTurtles(), GUIFunctions.AddTurtle.myTurtle, and turtle.Turtle.setID().
void GUIFunctions.AddTurtle.doAction ()
Implements GUIFunctions.GUIFunction.
Definition at line 20 of file AddTurtle.java.
void GUIFunctions.AddTurtle.doAction (List<?extends Number > newVal)
Implements GUIFunctions.GUIFunction.
Definition at line 24 of file AddTurtle.java.
Member Data Documentation
GridTracker GUIFunctions.AddTurtle.myGrid private
Definition at line 14 of file AddTurtle.java.
Turtle GUIFunctions.AddTurtle.myTurtle private
Definition at line 13 of file AddTurtle.java.
Referenced by GUIFunctions.AddTurtle.addAction().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/GUIFunctions/AddTurtle.java