slogo_team13: View.ColorSelection Class Reference
View.ColorSelection Class Reference
Public Member Functions
ColorSelection (GridTracker grid)
List< String > getAvailableColors ()
void myColorPane ()
void setColor (int myIndex, String colorLowerCase)
void switchPosition (int firstIndex, String firstString, int secondIndex, String secondString)
Private Member Functions
void doColorEvent (String color)
Private Attributes
ArrayList< String > myColors = new ArrayList<>()
HashSet< ColorLabel > myLabels =new HashSet<ColorLabel>()
GridTracker myGrids
HBox colorBox =new HBox()
Detailed Description
Definition at line 17 of file ColorSelection.java.
Constructor & Destructor Documentation
View.ColorSelection.ColorSelection (GridTracker grid)
Definition at line 23 of file ColorSelection.java.
References View.ColorSelection.myColorPane().
Member Function Documentation
void View.ColorSelection.doColorEvent (String color) private
Definition at line 62 of file ColorSelection.java.
List<String> View.ColorSelection.getAvailableColors ()
Definition at line 45 of file ColorSelection.java.
References View.ColorSelection.myColors.
Referenced by GUIFunctions.BackgroundColor.doAction(), and GUIFunctions.PenColor.doAction().
void View.ColorSelection.myColorPane ()
Definition at line 48 of file ColorSelection.java.
Referenced by View.ColorSelection.ColorSelection(), and View.ColorSelection.setColor().
void View.ColorSelection.setColor (int myIndex, String colorLowerCase)
Definition at line 67 of file ColorSelection.java.
References View.ColorSelection.myColorPane(), and View.ColorSelection.switchPosition().
Referenced by View.SetPalette.doAction().
void View.ColorSelection.switchPosition (int firstIndex, String firstString, int secondIndex, String secondString)
Definition at line 78 of file ColorSelection.java.
Referenced by View.ColorSelection.setColor().
Member Data Documentation
HBox View.ColorSelection.colorBox =new HBox() private
Definition at line 21 of file ColorSelection.java.
ArrayList<String> View.ColorSelection.myColors = new ArrayList<>() private
Definition at line 18 of file ColorSelection.java.
Referenced by View.ColorSelection.getAvailableColors().
GridTracker View.ColorSelection.myGrids private
Definition at line 20 of file ColorSelection.java.
HashSet<ColorLabel> View.ColorSelection.myLabels =new HashSet<ColorLabel>() private
Definition at line 19 of file ColorSelection.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/View/ColorSelection.java