slogo_team13: tests.ExpressionCommandParseTest Class Reference
tests.ExpressionCommandParseTest Class Reference
Public Member Functions
void testSumParses () throws BackendException, ClassNotFoundException
void testDifference () throws BackendException, ClassNotFoundException
void testProduct () throws BackendException, ClassNotFoundException
void testQuotient () throws BackendException, ClassNotFoundException
void testRemainder () throws BackendException, ClassNotFoundException
void testRandom () throws BackendException, ClassNotFoundException
void testMinus () throws BackendException, ClassNotFoundException
void testPower () throws BackendException, ClassNotFoundException
void testSin () throws BackendException, ClassNotFoundException
void testCos () throws BackendException, ClassNotFoundException
void testTan () throws BackendException, ClassNotFoundException
void testATan () throws BackendException, ClassNotFoundException
void naturalLogTest () throws BackendException, ClassNotFoundException
void testLess () throws BackendException, ClassNotFoundException
void testGreater () throws BackendException, ClassNotFoundException
void testEqual () throws BackendException, ClassNotFoundException
void testNotEqual () throws BackendException, ClassNotFoundException
void testAnd () throws BackendException, ClassNotFoundException
void testOr () throws BackendException, ClassNotFoundException
void testNot () throws BackendException, ClassNotFoundException
Private Member Functions
String processInput (String input) throws BackendException, ClassNotFoundException
Static Private Attributes
static final double mySumTestAnswer = 26.0
Detailed Description
Author
Rahul Harikrishnan, Duke Kim, $cotty $haw
Definition at line 21 of file ExpressionCommandParseTest.java.
Member Function Documentation
void tests.ExpressionCommandParseTest.naturalLogTest () throws BackendException, ClassNotFoundException
Definition at line 220 of file ExpressionCommandParseTest.java.
References commandParser.CommandFactory.createCommand(), commands.BaseCommand.execute(), and tests.ExpressionCommandParseTest.processInput().
String tests.ExpressionCommandParseTest.processInput (String input) throws BackendException, ClassNotFoundException private
Definition at line 334 of file ExpressionCommandParseTest.java.
References commandParser.CommandFactory.setCommandToClassRelation(), and commandParser.LanguageFileParser.translateUserInputIntoEnglish().
Referenced by tests.ExpressionCommandParseTest.naturalLogTest(), tests.ExpressionCommandParseTest.testAnd(), tests.ExpressionCommandParseTest.testATan(), tests.ExpressionCommandParseTest.testCos(), tests.ExpressionCommandParseTest.testDifference(), tests.ExpressionCommandParseTest.testEqual(), tests.ExpressionCommandParseTest.testGreater(), tests.ExpressionCommandParseTest.testLess(), tests.ExpressionCommandParseTest.testMinus(), tests.ExpressionCommandParseTest.testNot(), tests.ExpressionCommandParseTest.testNotEqual(), tests.ExpressionCommandParseTest.testOr(), tests.ExpressionCommandParseTest.testPower(), tests.ExpressionCommandParseTest.testProduct(), tests.ExpressionCommandParseTest.testQuotient(), tests.ExpressionCommandParseTest.testRandom(), tests.ExpressionCommandParseTest.testRemainder(), tests.ExpressionCommandParseTest.testSin(), tests.ExpressionCommandParseTest.testSumParses(), and tests.ExpressionCommandParseTest.testTan().
void tests.ExpressionCommandParseTest.testAnd () throws BackendException, ClassNotFoundException
Definition at line 292 of file ExpressionCommandParseTest.java.
References commandParser.CommandFactory.createCommand(), commands.BaseCommand.execute(), and tests.ExpressionCommandParseTest.processInput().
void tests.ExpressionCommandParseTest.testATan () throws BackendException, ClassNotFoundException
Definition at line 204 of file ExpressionCommandParseTest.java.
References commandParser.CommandFactory.createCommand(), commands.BaseCommand.execute(), and tests.ExpressionCommandParseTest.processInput().
void tests.ExpressionCommandParseTest.testCos () throws BackendException, ClassNotFoundException
Definition at line 172 of file ExpressionCommandParseTest.java.
References commandParser.CommandFactory.createCommand(), commands.BaseCommand.execute(), and tests.ExpressionCommandParseTest.processInput().
void tests.ExpressionCommandParseTest.testDifference () throws BackendException, ClassNotFoundException
Definition at line 40 of file ExpressionCommandParseTest.java.
References commandParser.CommandFactory.createCommand(), commands.BaseCommand.execute(), and tests.ExpressionCommandParseTest.processInput().
void tests.ExpressionCommandParseTest.testEqual () throws BackendException, ClassNotFoundException
Definition at line 264 of file ExpressionCommandParseTest.java.
References commandParser.CommandFactory.createCommand(), commands.BaseCommand.execute(), and tests.ExpressionCommandParseTest.processInput().
void tests.ExpressionCommandParseTest.testGreater () throws BackendException, ClassNotFoundException
Definition at line 250 of file ExpressionCommandParseTest.java.
References commandParser.CommandFactory.createCommand(), commands.BaseCommand.execute(), and tests.ExpressionCommandParseTest.processInput().
void tests.ExpressionCommandParseTest.testLess () throws BackendException, ClassNotFoundException
Definition at line 236 of file ExpressionCommandParseTest.java.
References commandParser.CommandFactory.createCommand(), commands.BaseCommand.execute(), and tests.ExpressionCommandParseTest.processInput().
void tests.ExpressionCommandParseTest.testMinus () throws BackendException, ClassNotFoundException
Definition at line 124 of file ExpressionCommandParseTest.java.
References commandParser.CommandFactory.createCommand(), commands.BaseCommand.execute(), and tests.ExpressionCommandParseTest.processInput().
void tests.ExpressionCommandParseTest.testNot () throws BackendException, ClassNotFoundException
Definition at line 320 of file ExpressionCommandParseTest.java.
References commandParser.CommandFactory.createCommand(), commands.BaseCommand.execute(), and tests.ExpressionCommandParseTest.processInput().
void tests.ExpressionCommandParseTest.testNotEqual () throws BackendException, ClassNotFoundException
Definition at line 278 of file ExpressionCommandParseTest.java.
References commandParser.CommandFactory.createCommand(), commands.BaseCommand.execute(), and tests.ExpressionCommandParseTest.processInput().
void tests.ExpressionCommandParseTest.testOr () throws BackendException, ClassNotFoundException
Definition at line 306 of file ExpressionCommandParseTest.java.
References commandParser.CommandFactory.createCommand(), commands.BaseCommand.execute(), and tests.ExpressionCommandParseTest.processInput().
void tests.ExpressionCommandParseTest.testPower () throws BackendException, ClassNotFoundException
Definition at line 140 of file ExpressionCommandParseTest.java.
References commandParser.CommandFactory.createCommand(), commands.BaseCommand.execute(), and tests.ExpressionCommandParseTest.processInput().
void tests.ExpressionCommandParseTest.testProduct () throws BackendException, ClassNotFoundException
Definition at line 58 of file ExpressionCommandParseTest.java.
References commandParser.CommandFactory.createCommand(), commands.BaseCommand.execute(), and tests.ExpressionCommandParseTest.processInput().
void tests.ExpressionCommandParseTest.testQuotient () throws BackendException, ClassNotFoundException
Definition at line 73 of file ExpressionCommandParseTest.java.
References commandParser.CommandFactory.createCommand(), commands.BaseCommand.execute(), and tests.ExpressionCommandParseTest.processInput().
void tests.ExpressionCommandParseTest.testRandom () throws BackendException, ClassNotFoundException
Definition at line 104 of file ExpressionCommandParseTest.java.
References commandParser.CommandFactory.createCommand(), commands.BaseCommand.execute(), and tests.ExpressionCommandParseTest.processInput().
void tests.ExpressionCommandParseTest.testRemainder () throws BackendException, ClassNotFoundException
Definition at line 88 of file ExpressionCommandParseTest.java.
References commandParser.CommandFactory.createCommand(), commands.BaseCommand.execute(), and tests.ExpressionCommandParseTest.processInput().
void tests.ExpressionCommandParseTest.testSin () throws BackendException, ClassNotFoundException
Definition at line 156 of file ExpressionCommandParseTest.java.
References commandParser.CommandFactory.createCommand(), commands.BaseCommand.execute(), and tests.ExpressionCommandParseTest.processInput().
void tests.ExpressionCommandParseTest.testSumParses () throws BackendException, ClassNotFoundException
Definition at line 26 of file ExpressionCommandParseTest.java.
References commandParser.CommandFactory.createCommand(), commands.BaseCommand.execute(), and tests.ExpressionCommandParseTest.processInput().
void tests.ExpressionCommandParseTest.testTan () throws BackendException, ClassNotFoundException
Definition at line 188 of file ExpressionCommandParseTest.java.
References commandParser.CommandFactory.createCommand(), commands.BaseCommand.execute(), and tests.ExpressionCommandParseTest.processInput().
Member Data Documentation
final double tests.ExpressionCommandParseTest.mySumTestAnswer = 26.0 static private
Definition at line 23 of file ExpressionCommandParseTest.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/tests/ExpressionCommandParseTest.java