slogo_team13: View.ScrollingBar Class Reference
View.ScrollingBar Class Reference abstract
Public Member Functions
ScrollingBar (String myLabel, int x, int y, int height, int width, int min, int max, int value, GUIFunction function)
Public Member Functions inherited from View.UserObjects
void addEvent (EventHandler< ActionEvent > handler)
Protected Attributes
int myX
int myY
int myHeight
int myWidth
GUIFunction myFunction
Slider myBar
Private Member Functions
void makeScrollingBar (int min, int max, int value)
void makeLabel (String s)
Detailed Description
Definition at line 12 of file ScrollingBar.java.
Constructor & Destructor Documentation
View.ScrollingBar.ScrollingBar (String myLabel, int x, int y, int height, int width, int min, int max, int value, GUIFunction function)
Definition at line 19 of file ScrollingBar.java.
References View.ScrollingBar.makeLabel(), View.ScrollingBar.makeScrollingBar(), and x().
Member Function Documentation
void View.ScrollingBar.makeLabel (String s) private
Definition at line 34 of file ScrollingBar.java.
Referenced by View.ScrollingBar.ScrollingBar().
void View.ScrollingBar.makeScrollingBar (int min, int max, int value) private
Definition at line 28 of file ScrollingBar.java.
Referenced by View.ScrollingBar.ScrollingBar().
Member Data Documentation
Slider View.ScrollingBar.myBar protected
Definition at line 18 of file ScrollingBar.java.
Referenced by View.PenScrollingBar.setFocus().
GUIFunction View.ScrollingBar.myFunction protected
Definition at line 17 of file ScrollingBar.java.
Referenced by View.PenScrollingBar.addEvent().
int View.ScrollingBar.myHeight protected
Definition at line 15 of file ScrollingBar.java.
int View.ScrollingBar.myWidth protected
Definition at line 16 of file ScrollingBar.java.
int View.ScrollingBar.myX protected
Definition at line 13 of file ScrollingBar.java.
int View.ScrollingBar.myY protected
Definition at line 14 of file ScrollingBar.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/View/ScrollingBar.java