slogo_team13: turtle.Position Class Reference
turtle.Position Class Reference
Public Member Functions
Position ()
Position (double xPos, double yPos)
Position (double xPos, double yPos, double rotatePos)
void moveHorizontal (double xIncrement)
void moveVertical (double yIncrement)
void move (double increment)
void rotate (double rotateIncrement)
double getRotate ()
double getXPos ()
double getYPos ()
boolean equals (Object o)
void setXPos (double xPos)
void setYPos (double yPos)
void setRotation (double rotateVal)
Private Attributes
double myXPos
double myYPos
double myRotate
Detailed Description
Position object that stores and manipulates basic location (x-, y- coordinates) and rotation orientation (degrees). Can be extended to incorporate a z-coordinate for a 3D rendering.
Definition at line 7 of file Position.java.
Constructor & Destructor Documentation
turtle.Position.Position ()
No argument constructor
Definition at line 15 of file Position.java.
turtle.Position.Position (double xPos, double yPos)
Constructor that sets the initial x-, and y- coordinates
Parameters
xPos - initial x-coordinate
yPos - initial y-coordinate
Definition at line 22 of file Position.java.
turtle.Position.Position (double xPos, double yPos, double rotatePos)
Alternate constructor that takes an additional angle orientation (degrees) parameter
Parameters
xPos - initial x-coordinate
yPos - initial y-coordinate
rotatePos - initial orientation (degrees)
Definition at line 33 of file Position.java.
Member Function Documentation
boolean turtle.Position.equals (Object o)
Definition at line 92 of file Position.java.
double turtle.Position.getRotate ()
Returns
Current rotation angle
Definition at line 73 of file Position.java.
References turtle.Position.myRotate.
Referenced by turtle.Turtle.getOrientation(), turtle.Turtle.move(), turtle.Turtle.moveTowardsHeading(), turtle.Turtle.setHeading(), and turtle.Turtle.setXPos().
double turtle.Position.getXPos ()
Returns
Current x-coordinate
Definition at line 80 of file Position.java.
References turtle.Position.myXPos.
Referenced by turtle.Turtle.getXPos(), turtle.Left.move(), turtle.Right.move(), turtle.Turtle.move(), turtle.Turtle.moveTowardsHeading(), and turtle.Turtle.setXPos().
double turtle.Position.getYPos ()
Returns
Current y-coordinate
Definition at line 87 of file Position.java.
References turtle.Position.myYPos.
Referenced by turtle.Turtle.getYPos(), turtle.Down.move(), turtle.Up.move(), turtle.Turtle.move(), turtle.Turtle.moveTowardsHeading(), and turtle.Turtle.setXPos().
void turtle.Position.move (double increment)
Move amount specified at current heading
Parameters
increment - straight-line distance to be moved
Definition at line 58 of file Position.java.
References turtle.Position.moveHorizontal(), and turtle.Position.moveVertical().
Referenced by turtle.Turtle.moveTowardsHeading().
void turtle.Position.moveHorizontal (double xIncrement)
Move horizontally
Parameters
xIncrement - horizontal movement increment
Definition at line 42 of file Position.java.
Referenced by turtle.Position.move(), and turtle.Turtle.moveHorizontal().
void turtle.Position.moveVertical (double yIncrement)
Move vertically
Parameters
yIncrement - vertical movement increment
Definition at line 50 of file Position.java.
Referenced by turtle.Position.move(), and turtle.Turtle.moveVertical().
void turtle.Position.rotate (double rotateIncrement)
Rotate by specified increment
Parameters
rotateIncrement - rotation increment
Definition at line 66 of file Position.java.
Referenced by turtle.Turtle.rotate().
void turtle.Position.setRotation (double rotateVal)
Definition at line 102 of file Position.java.
Referenced by turtle.Turtle.setHeading(), and turtle.Turtle.setRotation().
void turtle.Position.setXPos (double xPos)
Definition at line 96 of file Position.java.
Referenced by turtle.Left.move(), turtle.Right.move(), and turtle.Turtle.setXPos().
void turtle.Position.setYPos (double yPos)
Definition at line 99 of file Position.java.
Referenced by turtle.Down.move(), turtle.Up.move(), and turtle.Turtle.setYPos().
Member Data Documentation
double turtle.Position.myRotate private
Definition at line 10 of file Position.java.
Referenced by turtle.Position.getRotate().
double turtle.Position.myXPos private
Definition at line 8 of file Position.java.
Referenced by turtle.Position.getXPos().
double turtle.Position.myYPos private
Definition at line 9 of file Position.java.
Referenced by turtle.Position.getYPos().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/turtle/Position.java