slogo_team13: View.Grid Class Reference
View.Grid Class Reference abstract
Public Member Functions
int getID ()
abstract Turtle addTurtle (Turtle myTurtle)
void setMap (HashMap setMyMap)
abstract Turtle addTurtle ()
abstract void updateGUI (String myFunction)
abstract void updateGUI (String myFunction, List<?extends Number > myNumber)
abstract void sendErrorMessage (String s)
abstract void update (Collection< Turtle > activatedTurtles)
Static Public Attributes
static final String DEFAULT_RESOURCE_SOURCE ="/resources/GUIFunctionsMap"
Protected Attributes
int myID
HashMap< String, Class > myMap =new HashMap<String, Class>()
EventHandler< KeyEvent > myEvent
Detailed Description
Definition at line 14 of file Grid.java.
Member Function Documentation
abstract Turtle View.Grid.addTurtle (Turtle myTurtle) abstract
Referenced by commands.turtleCommands.MultipleTurtleCommand.addFutureActiveTurtleTurtles().
abstract Turtle View.Grid.addTurtle () abstract
int View.Grid.getID ()
Definition at line 20 of file Grid.java.
References View.Grid.myID.
Referenced by View.SlogoView.addTurtle(), View.SlogoView.build(), commands.information.SingleGridInformationGateway.getContainer(), commands.information.SingleActiveGridContainer.removeGrid(), and commands.information.SingleGridInformationGateway.SingleGridInformationGateway().
abstract void View.Grid.sendErrorMessage (String s) abstract
void View.Grid.setMap (HashMap setMyMap)
Definition at line 24 of file Grid.java.
abstract void View.Grid.update (Collection< Turtle > activatedTurtles) abstract
Referenced by commands.information.SingleActiveGridContainer.update().
abstract void View.Grid.updateGUI (String myFunction) abstract
Referenced by commands.information.SingleActiveGridContainer.updateDisplayOptions().
abstract void View.Grid.updateGUI (String myFunction, List<?extends Number > myNumber) abstract
Member Data Documentation
final String View.Grid.DEFAULT_RESOURCE_SOURCE ="/resources/GUIFunctionsMap" static
Definition at line 18 of file Grid.java.
EventHandler<KeyEvent> View.Grid.myEvent protected
Definition at line 17 of file Grid.java.
int View.Grid.myID protected
Definition at line 15 of file Grid.java.
Referenced by View.Grid.getID(), and View.SingleGrid.SingleGrid().
HashMap<String, Class> View.Grid.myMap =new HashMap<String, Class>() protected
Definition at line 16 of file Grid.java.
Referenced by View.SingleGrid.SingleGrid().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/View/Grid.java