slogo_team13: View.SingleGrid Class Reference
View.SingleGrid Class Reference
Public Member Functions
SingleGrid ()
SingleGrid (KeyFrame frame, HashMap myMap, int ID)
int getMyHeight ()
int getMyWidth ()
Collection< Turtle > getAllTurtles ()
Turtle addTurtle ()
void setBackgroundColor (String color)
void moveTurtle (Turtle t)
void update (Collection< Turtle > activatedTurtles)
void keyUpdate ()
void keepTurtleInBounds (Turtle t)
Collection< Turtle > getActiveTurtles ()
Collection< Pen > getAllPens ()
Collection< Pen > getActivePens ()
void updateGUI (String myFunction)
void updateGUI (String myFunction, List<?extends Number > myNumber)
void sendErrorMessage (String s)
Turtle addTurtle (Turtle myTurtle)
Public Member Functions inherited from View.Grid
int getID ()
abstract Turtle addTurtle (Turtle myTurtle)
void setMap (HashMap setMyMap)
abstract Turtle addTurtle ()
abstract void updateGUI (String myFunction)
abstract void updateGUI (String myFunction, List<?extends Number > myNumber)
abstract void sendErrorMessage (String s)
abstract void update (Collection< Turtle > activatedTurtles)
Private Member Functions
Collection< Pen > getPens (Collection< Turtle > myTurtles)
Private Attributes
String backgroundColor = "FFFFFF"
int myHeight
int myWidth
ImageView myImageView
HashSet< Turtle > allTurtles =new HashSet<Turtle>()
HashSet< Turtle > activeTurtles =new HashSet<Turtle>()
HashMap< String, GUIFunction > myGridFunctions =new HashMap<String, GUIFunction>()
boolean outOfBounds
Static Private Attributes
static final Dimension DEFAULT_GRID_SIZE = new Dimension(800, 500)
Additional Inherited Members
Static Public Attributes inherited from View.Grid
static final String DEFAULT_RESOURCE_SOURCE ="/resources/GUIFunctionsMap"
Protected Attributes inherited from View.Grid
int myID
HashMap< String, Class > myMap =new HashMap<String, Class>()
EventHandler< KeyEvent > myEvent
Detailed Description
Definition at line 30 of file SingleGrid.java.
Constructor & Destructor Documentation
View.SingleGrid.SingleGrid ()
Definition at line 41 of file SingleGrid.java.
View.SingleGrid.SingleGrid (KeyFrame frame, HashMap myMap, int ID)
Definition at line 44 of file SingleGrid.java.
References View.Grid.myID, View.Grid.myMap, and View.SingleGrid.setBackgroundColor().
Member Function Documentation
Turtle View.SingleGrid.addTurtle ()
Definition at line 65 of file SingleGrid.java.
References View.SingleGrid.getAllTurtles(), and turtle.Turtle.setID().
Referenced by View.SlogoView.addTurtle().
Turtle View.SingleGrid.addTurtle (Turtle myTurtle)
Definition at line 177 of file SingleGrid.java.
References turtle.Turtle.getPen(), turtle.Turtle.getXPos(), turtle.Turtle.getYPos(), turtle.Turtle.move(), View.SingleGrid.moveTurtle(), and View.Pen.setInitialPosition().
Collection<Pen> View.SingleGrid.getActivePens ()
Definition at line 158 of file SingleGrid.java.
References View.SingleGrid.getActiveTurtles(), and View.SingleGrid.getPens().
Referenced by GUIFunctions.SetPenDown.doAction(), GUIFunctions.SetPenUp.doAction(), GUIFunctions.PenThickness.doAction(), GUIFunctions.PenColor.doAction(), and GUIFunctions.PenStyle.doAction().
Collection<Turtle> View.SingleGrid.getActiveTurtles ()
Definition at line 146 of file SingleGrid.java.
References View.SingleGrid.activeTurtles.
Referenced by GUIFunctions.ClearFunction.doAction(), GUIFunctions.Undo.doAction(), GUIFunctions.Stamp.doAction(), GUIFunctions.TurtleImageChange.doAction(), View.SingleGrid.getActivePens(), View.SingleGrid.keyUpdate(), TableInformation.TurtleVariablesTable.moveTurtle(), and View.TabsOfGrids.setUpKeyBoardHandler().
Collection<Pen> View.SingleGrid.getAllPens ()
Definition at line 155 of file SingleGrid.java.
References View.SingleGrid.getPens().
Referenced by GUIFunctions.SetBackgroundImage.gridSetAction().
Collection<Turtle> View.SingleGrid.getAllTurtles ()
Definition at line 62 of file SingleGrid.java.
References View.SingleGrid.allTurtles.
Referenced by GUIFunctions.AddTurtle.addAction(), View.SingleGrid.addTurtle(), GUIFunctions.ClearFunction.doAction(), GUIFunctions.SetBackgroundImage.gridSetAction(), and TableInformation.TurtleVariablesTable.updateList().
int View.SingleGrid.getMyHeight ()
Definition at line 56 of file SingleGrid.java.
References View.SingleGrid.myHeight.
Referenced by View.TabsOfGrids.addTab(), GUIFunctions.ToggleGridLines.drawGridLine(), GUIFunctions.SetBackgroundImage.gridSetAction(), and GUIFunctions.ToggleGridLines.makeGridLines().
int View.SingleGrid.getMyWidth ()
Definition at line 59 of file SingleGrid.java.
References View.SingleGrid.myWidth.
Referenced by View.TabsOfGrids.addTab(), GUIFunctions.ToggleGridLines.drawGridLine(), GUIFunctions.SetBackgroundImage.gridSetAction(), and GUIFunctions.ToggleGridLines.makeGridLines().
Collection<Pen> View.SingleGrid.getPens (Collection< Turtle > myTurtles) private
Definition at line 161 of file SingleGrid.java.
Referenced by View.SingleGrid.getActivePens(), and View.SingleGrid.getAllPens().
void View.SingleGrid.keepTurtleInBounds (Turtle t)
Allows the turtle to "Wrap" around the borders of the drawing instead of disappearing
Definition at line 114 of file SingleGrid.java.
References View.Pen.drawLine(), turtle.Turtle.getPen(), View.Pen.getPenDown(), turtle.Turtle.getXPos(), turtle.Turtle.getYPos(), View.SingleGrid.myHeight, View.SingleGrid.myWidth, View.Pen.setPenDown(), turtle.Turtle.setXPos(), and turtle.Turtle.setYPos().
Referenced by View.SingleGrid.keyUpdate(), and View.SingleGrid.update().
void View.SingleGrid.keyUpdate ()
Similar to update except it is activated by directional key presses
Definition at line 102 of file SingleGrid.java.
References View.SingleGrid.getActiveTurtles(), View.SingleGrid.keepTurtleInBounds(), and View.SingleGrid.moveTurtle().
Referenced by View.TabsOfGrids.setUpKeyBoardHandler().
void View.SingleGrid.moveTurtle (Turtle t)
Definition at line 79 of file SingleGrid.java.
References turtle.Turtle.getOrientation(), turtle.Turtle.getXPos(), and turtle.Turtle.getYPos().
Referenced by View.SingleGrid.addTurtle(), GUIFunctions.Undo.doAction(), View.SingleGrid.keyUpdate(), and View.SingleGrid.update().
void View.SingleGrid.sendErrorMessage (String s)
Definition at line 174 of file SingleGrid.java.
void View.SingleGrid.setBackgroundColor (String color)
Definition at line 74 of file SingleGrid.java.
Referenced by GUIFunctions.BackgroundColor.doAction(), and View.SingleGrid.SingleGrid().
void View.SingleGrid.update (Collection< Turtle > activatedTurtles)
Takes in the coordinates (x,y) from the controller and pops the last coordinate from the stack to call move(int x, int y)
Parameters
x x location on the Grid
y y location on the Grid
Definition at line 89 of file SingleGrid.java.
References View.SingleGrid.keepTurtleInBounds(), and View.SingleGrid.moveTurtle().
Referenced by GUIFunctions.Undo.doAction(), and TableInformation.TurtleVariablesTable.moveTurtle().
void View.SingleGrid.updateGUI (String myFunction)
Definition at line 168 of file SingleGrid.java.
void View.SingleGrid.updateGUI (String myFunction, List<?extends Number > myNumber)
Definition at line 171 of file SingleGrid.java.
Member Data Documentation
HashSet<Turtle> View.SingleGrid.activeTurtles =new HashSet<Turtle>() private
Definition at line 38 of file SingleGrid.java.
Referenced by View.SingleGrid.getActiveTurtles().
HashSet<Turtle> View.SingleGrid.allTurtles =new HashSet<Turtle>() private
Definition at line 37 of file SingleGrid.java.
Referenced by View.SingleGrid.getAllTurtles().
String View.SingleGrid.backgroundColor = "FFFFFF" private
Definition at line 33 of file SingleGrid.java.
final Dimension View.SingleGrid.DEFAULT_GRID_SIZE = new Dimension(800, 500) static private
Definition at line 32 of file SingleGrid.java.
HashMap<String, GUIFunction> View.SingleGrid.myGridFunctions =new HashMap<String, GUIFunction>() private
Definition at line 39 of file SingleGrid.java.
int View.SingleGrid.myHeight private
Definition at line 34 of file SingleGrid.java.
Referenced by View.SingleGrid.getMyHeight(), and View.SingleGrid.keepTurtleInBounds().
ImageView View.SingleGrid.myImageView private
Definition at line 36 of file SingleGrid.java.
int View.SingleGrid.myWidth private
Definition at line 35 of file SingleGrid.java.
Referenced by View.SingleGrid.getMyWidth(), and View.SingleGrid.keepTurtleInBounds().
boolean View.SingleGrid.outOfBounds private
Definition at line 40 of file SingleGrid.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/View/SingleGrid.java