slogo_team13: commands.controlCommands.IfCommand Class Reference
commands.controlCommands.IfCommand Class Reference
Public Member Functions
IfCommand (String userInput, boolean isExpression) throws BackendException
Public Member Functions inherited from commands.ControlCommand
ControlCommand (String userInput, boolean isExpression) throws BackendException
Set< Class<?extends IInformationContainer > > getRequiredInformationTypes ()
void setRequiredInformation (Collection< IInformationContainer > containers) throws BackendException
Public Member Functions inherited from commands.BaseCommand
BaseCommand (String userInput, boolean isExpression) throws BackendException
double execute () throws BackendException
abstract Set< Class<?extends IInformationContainer > > getRequiredInformationTypes ()
abstract void setRequiredInformation (Collection< IInformationContainer > containers) throws BackendException
String getLeftoverString ()
Protected Member Functions
double onExecute () throws BackendException
void parseArguments (String userInput) throws BackendException
Protected Member Functions inherited from commands.ControlCommand
BaseUserDefinedContainer getVariableContainer ()
void reset ()
Protected Member Functions inherited from commands.BaseCommand
abstract double onExecute () throws BackendException
abstract void parseArguments (String userInput) throws BackendException
void setLeftoverCommands (String string) throws BackendException
String[] splitByInnerListCommand (String input)
boolean startsWithCommandStartIndicator (String input)
abstract void reset ()
Private Attributes
BaseCommand myExpression
BaseCommand myInternalCommand
Additional Inherited Members
Protected Attributes inherited from commands.BaseCommand
final String COMMAND_DELIMITER = "\\s+"
Static Protected Attributes inherited from commands.ControlCommand
static String COMMAND_INDICATOR = "liststart"
static String COMMAND_END_INDICATOR = "listend"
static String COMMAND_SEPARATOR = " "
static String VARIABLE_INDICATOR = "variable"
Static Protected Attributes inherited from commands.BaseCommand
static String COMMAND_INDICATOR = "liststart"
static String COMMAND_END_INDICATOR = "listend"
static String COMMAND_SEPARATOR = " "
static String VARIABLE_INDICATOR = "variable"
Detailed Description
Author
Rahul Harikrishnan, Duke Kim, $cotty $haw
Definition at line 13 of file IfCommand.java.
Constructor & Destructor Documentation
commands.controlCommands.IfCommand.IfCommand (String userInput, boolean isExpression) throws BackendException
Definition at line 18 of file IfCommand.java.
Member Function Documentation
double commands.controlCommands.IfCommand.onExecute () throws BackendException protected
Definition at line 23 of file IfCommand.java.
References commands.BaseCommand.execute().
void commands.controlCommands.IfCommand.parseArguments (String userInput) throws BackendException protected
Definition at line 36 of file IfCommand.java.
References commandParser.CommandFactory.createCommand(), commands.BaseCommand.getLeftoverString(), commands.BaseCommand.setLeftoverCommands(), and commands.BaseCommand.splitByInnerListCommand().
Member Data Documentation
BaseCommand commands.controlCommands.IfCommand.myExpression private
Definition at line 15 of file IfCommand.java.
BaseCommand commands.controlCommands.IfCommand.myInternalCommand private
Definition at line 16 of file IfCommand.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/commands/controlCommands/IfCommand.java