slogo_team13: TableInformation.VariableTable Class Reference
TableInformation.VariableTable Class Reference
Public Member Functions
VariableTable ()
void addVariables (List< UserInput > myUserInputFunctions)
void addInputs (List< UserInput > myUserInputFunctions)
Private Member Functions
void createTimeLine ()
KeyFrame build ()
void updateVariables ()
void updateFunctions ()
void makeTableView (TableView myTable)
void setTableStyle ()
TableColumn makeVariableNameColumn ()
TableColumn makeVariableValueColumn ()
TableColumn makeFunctionsVariableColumn ()
Private Attributes
ArrayList< UserInput > myVariables
ArrayList< UserInput > myFunctions
TableView variables
TableView functions
Static Private Attributes
static final Dimension DEFAULT_SIZE =new Dimension(500,500)
Detailed Description
Definition at line 31 of file VariableTable.java.
Constructor & Destructor Documentation
TableInformation.VariableTable.VariableTable ()
Definition at line 37 of file VariableTable.java.
References TableInformation.VariableTable.createTimeLine(), TableInformation.VariableTable.makeFunctionsVariableColumn(), TableInformation.VariableTable.makeVariableNameColumn(), TableInformation.VariableTable.makeVariableValueColumn(), and TableInformation.VariableTable.setTableStyle().
Member Function Documentation
void TableInformation.VariableTable.addInputs (List< UserInput > myUserInputFunctions)
Definition at line 86 of file VariableTable.java.
Referenced by View.SlogoView.addUserFunctions().
void TableInformation.VariableTable.addVariables (List< UserInput > myUserInputFunctions)
Definition at line 81 of file VariableTable.java.
Referenced by View.SlogoView.addVariables().
KeyFrame TableInformation.VariableTable.build () private
Definition at line 69 of file VariableTable.java.
References TableInformation.VariableTable.updateFunctions(), and TableInformation.VariableTable.updateVariables().
Referenced by TableInformation.VariableTable.createTimeLine().
void TableInformation.VariableTable.createTimeLine () private
Definition at line 63 of file VariableTable.java.
References TableInformation.VariableTable.build().
Referenced by TableInformation.VariableTable.VariableTable().
TableColumn TableInformation.VariableTable.makeFunctionsVariableColumn () private
Definition at line 147 of file VariableTable.java.
Referenced by TableInformation.VariableTable.VariableTable().
void TableInformation.VariableTable.makeTableView (TableView myTable) private
Definition at line 107 of file VariableTable.java.
TableColumn TableInformation.VariableTable.makeVariableNameColumn () private
Definition at line 116 of file VariableTable.java.
Referenced by TableInformation.VariableTable.VariableTable().
TableColumn TableInformation.VariableTable.makeVariableValueColumn () private
Definition at line 131 of file VariableTable.java.
References GUIFunctions.Variable.getValue().
Referenced by TableInformation.VariableTable.VariableTable().
void TableInformation.VariableTable.setTableStyle () private
Definition at line 110 of file VariableTable.java.
Referenced by TableInformation.VariableTable.VariableTable().
void TableInformation.VariableTable.updateFunctions () private
Definition at line 99 of file VariableTable.java.
Referenced by TableInformation.VariableTable.build().
void TableInformation.VariableTable.updateVariables () private
Definition at line 91 of file VariableTable.java.
Referenced by TableInformation.VariableTable.build().
Member Data Documentation
final Dimension TableInformation.VariableTable.DEFAULT_SIZE =new Dimension(500,500) static private
Definition at line 33 of file VariableTable.java.
TableView TableInformation.VariableTable.functions private
Definition at line 36 of file VariableTable.java.
ArrayList<UserInput> TableInformation.VariableTable.myFunctions private
Definition at line 34 of file VariableTable.java.
ArrayList<UserInput> TableInformation.VariableTable.myVariables private
Definition at line 32 of file VariableTable.java.
TableView TableInformation.VariableTable.variables private
Definition at line 35 of file VariableTable.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/TableInformation/VariableTable.java