slogo_team13: View.ButtonTemplate Class Reference
View.ButtonTemplate Class Reference
Public Member Functions
ButtonTemplate (String s, double x, double y, GUIFunction myFunction)
ButtonTemplate (String s, double x, double y, GUIFunction myFunction, int width, int height)
ButtonTemplate (String s, double x, double y, EventHandler myEvent, int width, int height)
void addEvent (EventHandler< ActionEvent > handler)
void setStyle (int text)
void actionOnMouseHover ()
void actionOnMouseExit ()
Private Attributes
final int textSize =10
final int offSet =2
Detailed Description
Definition at line 10 of file ButtonTemplate.java.
Constructor & Destructor Documentation
View.ButtonTemplate.ButtonTemplate (String s, double x, double y, GUIFunction myFunction)
Constructor
Parameters
s Label for the Button
handler Event for the Button to react upon
Definition at line 18 of file ButtonTemplate.java.
View.ButtonTemplate.ButtonTemplate (String s, double x, double y, GUIFunction myFunction, int width, int height)
Definition at line 22 of file ButtonTemplate.java.
View.ButtonTemplate.ButtonTemplate (String s, double x, double y, EventHandler myEvent, int width, int height)
Definition at line 26 of file ButtonTemplate.java.
References View.ButtonTemplate.addEvent(), and View.ButtonTemplate.setStyle().
Member Function Documentation
void View.ButtonTemplate.actionOnMouseExit ()
Definition at line 46 of file ButtonTemplate.java.
References View.ButtonTemplate.setStyle().
void View.ButtonTemplate.actionOnMouseHover ()
Definition at line 43 of file ButtonTemplate.java.
References View.ButtonTemplate.setStyle().
void View.ButtonTemplate.addEvent (EventHandler< ActionEvent > handler)
Creates an object on the GUI that the user can interact with
Parameters
handler ActionEvent for the object to react to
Implements View.UserObjects.
Definition at line 36 of file ButtonTemplate.java.
Referenced by View.ButtonTemplate.ButtonTemplate().
void View.ButtonTemplate.setStyle (int text)
Definition at line 39 of file ButtonTemplate.java.
Referenced by View.ButtonTemplate.actionOnMouseExit(), View.ButtonTemplate.actionOnMouseHover(), and View.ButtonTemplate.ButtonTemplate().
Member Data Documentation
final int View.ButtonTemplate.offSet =2 private
Definition at line 12 of file ButtonTemplate.java.
final int View.ButtonTemplate.textSize =10 private
Definition at line 11 of file ButtonTemplate.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/View/ButtonTemplate.java