slogo_team13: TableInformation.TurtleVariablesTable Class Reference
TableInformation.TurtleVariablesTable Class Reference
Public Member Functions
TurtleVariablesTable (GridTracker grid)
Private Member Functions
KeyFrame build ()
void updateList ()
void setColumnEditable ()
void moveTurtle (Column myColumn, CellEditEvent< Turtle, Object > myTurtle)
boolean makeMap ()
Private Attributes
GridTracker allGrids
Collection< Column > myColumns
Detailed Description
Definition at line 33 of file TurtleVariablesTable.java.
Constructor & Destructor Documentation
TableInformation.TurtleVariablesTable.TurtleVariablesTable (GridTracker grid)
Definition at line 37 of file TurtleVariablesTable.java.
References TableInformation.TurtleVariablesTable.build(), TableInformation.TurtleVariablesTable.makeMap(), TableInformation.TurtleVariablesTable.setColumnEditable(), and TableInformation.TurtleVariablesTable.updateList().
Member Function Documentation
KeyFrame TableInformation.TurtleVariablesTable.build () private
Definition at line 65 of file TurtleVariablesTable.java.
References TableInformation.TurtleVariablesTable.updateList().
Referenced by TableInformation.TurtleVariablesTable.TurtleVariablesTable().
boolean TableInformation.TurtleVariablesTable.makeMap () private
Definition at line 112 of file TurtleVariablesTable.java.
Referenced by TableInformation.TurtleVariablesTable.TurtleVariablesTable().
void TableInformation.TurtleVariablesTable.moveTurtle (Column myColumn, CellEditEvent< Turtle, Object > myTurtle) private
Definition at line 99 of file TurtleVariablesTable.java.
References TableInformation.Column< G >.doEditingFunction(), View.SingleGrid.getActiveTurtles(), and View.SingleGrid.update().
Referenced by TableInformation.TurtleVariablesTable.setColumnEditable().
void TableInformation.TurtleVariablesTable.setColumnEditable () private
Definition at line 87 of file TurtleVariablesTable.java.
References TableInformation.TurtleVariablesTable.moveTurtle().
Referenced by TableInformation.TurtleVariablesTable.TurtleVariablesTable().
void TableInformation.TurtleVariablesTable.updateList () private
Definition at line 76 of file TurtleVariablesTable.java.
References View.SingleGrid.getAllTurtles().
Referenced by TableInformation.TurtleVariablesTable.build(), and TableInformation.TurtleVariablesTable.TurtleVariablesTable().
Member Data Documentation
GridTracker TableInformation.TurtleVariablesTable.allGrids private
Definition at line 35 of file TurtleVariablesTable.java.
Collection<Column> TableInformation.TurtleVariablesTable.myColumns private
Definition at line 36 of file TurtleVariablesTable.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/TableInformation/TurtleVariablesTable.java