slogo_team13: commands.information.SingleActiveGridContainer Class Reference
commands.information.SingleActiveGridContainer Class Reference
Public Member Functions
SingleActiveGridContainer ()
SingleActiveGridContainer (Grid grid)
void addGrid (Grid grid, boolean isActive)
void setGridAsActive (int gridID)
void removeGrid (int gridID)
Collection< Grid > getActiveGrids ()
void updateDisplayOptions (String guiCommand)
void updateDisplayOptions (String guiCommand, List< Double > parameters)
void update (Collection< Turtle > turtles)
Public Member Functions inherited from commands.information.BaseGridContainer
abstract void updateDisplayOptions (String guiCommand)
abstract void updateDisplayOptions (String guiCommand, List< Double > parameters)
abstract void addGrid (Grid grid, boolean isActive)
abstract void setGridAsActive (int gridID)
abstract void removeGrid (int gridID)
abstract Collection< Grid > getActiveGrids ()
abstract void update (Collection< Turtle > turtles)
Private Attributes
List< Grid > myGridList
Grid myActiveGrid
Detailed Description
An implementation of grid container that has only one active grid at a time
Author
Duke
Definition at line 17 of file SingleActiveGridContainer.java.
Constructor & Destructor Documentation
commands.information.SingleActiveGridContainer.SingleActiveGridContainer ()
Definition at line 23 of file SingleActiveGridContainer.java.
commands.information.SingleActiveGridContainer.SingleActiveGridContainer (Grid grid)
Definition at line 27 of file SingleActiveGridContainer.java.
Member Function Documentation
void commands.information.SingleActiveGridContainer.addGrid (Grid grid, boolean isActive)
Definition at line 34 of file SingleActiveGridContainer.java.
Referenced by commands.information.SingleGridInformationGateway.SingleGridInformationGateway().
Collection<Grid> commands.information.SingleActiveGridContainer.getActiveGrids ()
Definition at line 61 of file SingleActiveGridContainer.java.
void commands.information.SingleActiveGridContainer.removeGrid (int gridID)
Definition at line 51 of file SingleActiveGridContainer.java.
References View.Grid.getID().
void commands.information.SingleActiveGridContainer.setGridAsActive (int gridID)
Definition at line 42 of file SingleActiveGridContainer.java.
void commands.information.SingleActiveGridContainer.update (Collection< Turtle > turtles)
Definition at line 76 of file SingleActiveGridContainer.java.
References View.Grid.update().
void commands.information.SingleActiveGridContainer.updateDisplayOptions (String guiCommand)
Definition at line 66 of file SingleActiveGridContainer.java.
References View.Grid.updateGUI().
void commands.information.SingleActiveGridContainer.updateDisplayOptions (String guiCommand, List< Double > parameters)
Definition at line 71 of file SingleActiveGridContainer.java.
References View.Grid.updateGUI().
Member Data Documentation
Grid commands.information.SingleActiveGridContainer.myActiveGrid private
Definition at line 21 of file SingleActiveGridContainer.java.
List<Grid> commands.information.SingleActiveGridContainer.myGridList private
Definition at line 20 of file SingleActiveGridContainer.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/commands/information/SingleActiveGridContainer.java