slogo_team13: GUIFunctions.PenColor Class Reference
GUIFunctions.PenColor Class Reference
Public Member Functions
PenColor (GridTracker grid, ColorSelection color)
void doAction ()
void doAction (List<?extends Number > newVal)
void doAction (String myColor)
Public Member Functions inherited from GUIFunctions.ColorFunction
ColorFunction ()
abstract void doAction (String s)
Public Member Functions inherited from GUIFunctions.GridFunction
GridFunction ()
Package Attributes
ColorSelection myColors
Package Attributes inherited from GUIFunctions.ColorFunction
GridTracker myGrids
Additional Inherited Members
Protected Attributes inherited from GUIFunctions.GridFunction
GridTracker allGrids
Detailed Description
Definition at line 9 of file PenColor.java.
Constructor & Destructor Documentation
GUIFunctions.PenColor.PenColor (GridTracker grid, ColorSelection color)
Definition at line 11 of file PenColor.java.
References GUIFunctions.GridFunction.allGrids.
Member Function Documentation
void GUIFunctions.PenColor.doAction ()
Implements GUIFunctions.GUIFunction.
Definition at line 16 of file PenColor.java.
void GUIFunctions.PenColor.doAction (List<?extends Number > newVal)
Implements GUIFunctions.GUIFunction.
Definition at line 21 of file PenColor.java.
References GUIFunctions.GridFunction.allGrids, View.GridTracker.getActiveGrid(), View.SingleGrid.getActivePens(), and View.ColorSelection.getAvailableColors().
void GUIFunctions.PenColor.doAction (String myColor)
Definition at line 28 of file PenColor.java.
References GUIFunctions.GridFunction.allGrids, View.GridTracker.getActiveGrid(), and View.SingleGrid.getActivePens().
Member Data Documentation
ColorSelection GUIFunctions.PenColor.myColors package
Definition at line 10 of file PenColor.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/GUIFunctions/PenColor.java