slogo_team13: commands.variableCommands.CreatedCommand Class Reference
commands.variableCommands.CreatedCommand Class Reference
Public Member Functions
CreatedCommand (String userInput, boolean isExpression) throws BackendException
void setVariables (String[] variables, BaseCommand[] variableValues)
void setInnerCommand (BaseCommand innerCommand)
Public Member Functions inherited from commands.variableCommands.VariableCommand
VariableCommand (String userInput, boolean isExpression) throws BackendException
Set< Class<?extends IInformationContainer > > getRequiredInformationTypes ()
void setRequiredInformation (Collection< IInformationContainer > containers)
Public Member Functions inherited from commands.BaseCommand
BaseCommand (String userInput, boolean isExpression) throws BackendException
double execute () throws BackendException
abstract Set< Class<?extends IInformationContainer > > getRequiredInformationTypes ()
abstract void setRequiredInformation (Collection< IInformationContainer > containers) throws BackendException
String getLeftoverString ()
Protected Member Functions
double onExecute () throws BackendException
void parseArguments (String userInput) throws BackendException
Protected Member Functions inherited from commands.variableCommands.VariableCommand
BaseUserDefinedContainer getVariableContainer ()
void reset ()
Protected Member Functions inherited from commands.BaseCommand
abstract double onExecute () throws BackendException
abstract void parseArguments (String userInput) throws BackendException
void setLeftoverCommands (String string) throws BackendException
String[] splitByInnerListCommand (String input)
boolean startsWithCommandStartIndicator (String input)
abstract void reset ()
Private Member Functions
void setNewVariables () throws BackendException
void revertVariables () throws BackendException
Private Attributes
Map< String, BaseCommand > myNewVariableToCommandMap
BaseCommand myInnerCommand
Map< String, BaseCommand > myOldExistingVariableMap
Collection< String > myNonExistingVariables
Additional Inherited Members
Protected Attributes inherited from commands.BaseCommand
final String COMMAND_DELIMITER = "\\s+"
Static Protected Attributes inherited from commands.BaseCommand
static String COMMAND_INDICATOR = "liststart"
static String COMMAND_END_INDICATOR = "listend"
static String COMMAND_SEPARATOR = " "
static String VARIABLE_INDICATOR = "variable"
Detailed Description
Author
Rahul Harikrishnan, Duke Kim, $cotty $haw
Definition at line 18 of file CreatedCommand.java.
Constructor & Destructor Documentation
commands.variableCommands.CreatedCommand.CreatedCommand (String userInput, boolean isExpression) throws BackendException
Definition at line 25 of file CreatedCommand.java.
Member Function Documentation
double commands.variableCommands.CreatedCommand.onExecute () throws BackendException protected
Definition at line 33 of file CreatedCommand.java.
References commands.BaseCommand.execute(), commands.variableCommands.CreatedCommand.revertVariables(), and commands.variableCommands.CreatedCommand.setNewVariables().
void commands.variableCommands.CreatedCommand.parseArguments (String userInput) throws BackendException protected
Definition at line 78 of file CreatedCommand.java.
References commands.BaseCommand.setLeftoverCommands().
void commands.variableCommands.CreatedCommand.revertVariables () throws BackendException private
Definition at line 56 of file CreatedCommand.java.
References commands.information.BaseUserDefinedContainer.addVariable(), commands.variableCommands.VariableCommand.getVariableContainer(), and commands.information.BaseUserDefinedContainer.popOffVariable().
Referenced by commands.variableCommands.CreatedCommand.onExecute().
void commands.variableCommands.CreatedCommand.setInnerCommand (BaseCommand innerCommand)
Definition at line 73 of file CreatedCommand.java.
Referenced by commands.information.MapBasedUserDefinedContainer.getCreatedCommand().
void commands.variableCommands.CreatedCommand.setNewVariables () throws BackendException private
Definition at line 40 of file CreatedCommand.java.
References commands.information.BaseUserDefinedContainer.addVariable(), commands.information.BaseUserDefinedContainer.containsVariable(), commands.BaseCommand.execute(), commands.information.BaseUserDefinedContainer.getValue(), and commands.variableCommands.VariableCommand.getVariableContainer().
Referenced by commands.variableCommands.CreatedCommand.onExecute().
void commands.variableCommands.CreatedCommand.setVariables (String[] variables, BaseCommand[] variableValues)
Definition at line 67 of file CreatedCommand.java.
Referenced by commands.information.MapBasedUserDefinedContainer.getCreatedCommand().
Member Data Documentation
BaseCommand commands.variableCommands.CreatedCommand.myInnerCommand private
Definition at line 21 of file CreatedCommand.java.
Map<String, BaseCommand> commands.variableCommands.CreatedCommand.myNewVariableToCommandMap private
Definition at line 20 of file CreatedCommand.java.
Collection<String> commands.variableCommands.CreatedCommand.myNonExistingVariables private
Definition at line 23 of file CreatedCommand.java.
Map<String, BaseCommand> commands.variableCommands.CreatedCommand.myOldExistingVariableMap private
Definition at line 22 of file CreatedCommand.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/commands/variableCommands/CreatedCommand.java