slogo_team13: View.ColorLabel Class Reference
View.ColorLabel Class Reference
Public Member Functions
ColorLabel (double x, double y, double width, double height, String myName, ColorFunction myGUIFunction)
void isActive (String color)
void setStyle (int text)
Private Member Functions
void addEvent ()
void setActive (boolean active)
Private Attributes
boolean isActive
ColorFunction myFunction
int myEffectSize =2
final int myTextSize =10
Detailed Description
Definition at line 5 of file ColorLabel.java.
Constructor & Destructor Documentation
View.ColorLabel.ColorLabel (double x, double y, double width, double height, String myName, ColorFunction myGUIFunction)
Definition at line 10 of file ColorLabel.java.
References View.ColorLabel.addEvent(), and View.ColorLabel.setStyle().
Member Function Documentation
void View.ColorLabel.addEvent () private
Definition at line 19 of file ColorLabel.java.
Referenced by View.ColorLabel.ColorLabel().
void View.ColorLabel.isActive (String color)
Definition at line 30 of file ColorLabel.java.
References GUIFunctions.ColorFunction.doAction().
void View.ColorLabel.setActive (boolean active) private
Definition at line 22 of file ColorLabel.java.
References View.ColorLabel.setStyle().
void View.ColorLabel.setStyle (int text)
Definition at line 35 of file ColorLabel.java.
Referenced by View.ColorLabel.ColorLabel(), and View.ColorLabel.setActive().
Member Data Documentation
boolean View.ColorLabel.isActive private
Definition at line 6 of file ColorLabel.java.
int View.ColorLabel.myEffectSize =2 private
Definition at line 8 of file ColorLabel.java.
ColorFunction View.ColorLabel.myFunction private
Definition at line 7 of file ColorLabel.java.
final int View.ColorLabel.myTextSize =10 private
Definition at line 9 of file ColorLabel.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/View/ColorLabel.java