slogo_team13: commands.BaseCommand Class Reference
commands.BaseCommand Class Reference abstract
Public Member Functions
BaseCommand (String userInput, boolean isExpression) throws BackendException
double execute () throws BackendException
abstract Set< Class<?extends IInformationContainer > > getRequiredInformationTypes ()
abstract void setRequiredInformation (Collection< IInformationContainer > containers) throws BackendException
String getLeftoverString ()
Protected Member Functions
abstract double onExecute () throws BackendException
abstract void parseArguments (String userInput) throws BackendException
void setLeftoverCommands (String string) throws BackendException
String[] splitByInnerListCommand (String input)
boolean startsWithCommandStartIndicator (String input)
abstract void reset ()
Protected Attributes
final String COMMAND_DELIMITER = "\\s+"
Static Protected Attributes
static String COMMAND_INDICATOR = "liststart"
static String COMMAND_END_INDICATOR = "listend"
static String COMMAND_SEPARATOR = " "
static String VARIABLE_INDICATOR = "variable"
Private Member Functions
BaseCommand getNextCommand ()
int findIndexOfInnerListCommandEnd (String input)
Private Attributes
BaseCommand myNextCommand
String myLeftoverString = ""
boolean myExpressionFlag
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Author
Rahul Harikrishnan, Duke Kim, $cotty $haw
Abstract class for all commands. All other types of commands will extend the BaseCommand.
Definition at line 19 of file BaseCommand.java.
Constructor & Destructor Documentation
commands.BaseCommand.BaseCommand (String userInput, boolean isExpression) throws BackendException
Parameters
userInput
Exceptions
BackendException TODO
Definition at line 36 of file BaseCommand.java.
References commands.BaseCommand.parseArguments().
Member Function Documentation
double commands.BaseCommand.execute () throws BackendException
Method returns the computation of the turtle command
Exceptions
BackendException TODO
Definition at line 49 of file BaseCommand.java.
References commands.BaseCommand.execute(), commands.BaseCommand.getNextCommand(), commands.BaseCommand.onExecute(), and commands.BaseCommand.reset().
Referenced by commands.BaseCommand.execute(), communicator.MainController.executeCommand(), commands.information.MapBasedUserDefinedContainer.getAllVariablesAndValues(), tests.ExpressionCommandParseTest.naturalLogTest(), commands.expressionCommands.ArcTanCommand.onExecute(), commands.expressionCommands.NaturalLogCommand.onExecute(), commands.expressionCommands.NegativeCommand.onExecute(), commands.expressionCommands.NotCommand.onExecute(), commands.expressionCommands.NotEqualCommand.onExecute(), commands.expressionCommands.AndCommand.onExecute(), commands.expressionCommands.OrCommand.onExecute(), commands.expressionCommands.ProductCommand.onExecute(), commands.expressionCommands.CosCommand.onExecute(), commands.expressionCommands.QuotientCommand.onExecute(), commands.expressionCommands.DifferenceCommand.onExecute(), commands.expressionCommands.RandomIntegerCommand.onExecute(), commands.expressionCommands.ExponentCommand.onExecute(), commands.expressionCommands.RemainderCommand.onExecute(), commands.expressionCommands.SinCommand.onExecute(), commands.expressionCommands.SumCommand.onExecute(), commands.expressionCommands.TanCommand.onExecute(), commands.expressionCommands.GreaterCommand.onExecute(), commands.expressionCommands.EqualCommand.onExecute(), commands.expressionCommands.LessCommand.onExecute(), commands.turtleCommands.LeftCommand.onExecute(), commands.turtleCommands.RightCommand.onExecute(), commands.turtleCommands.SetHeadingCommand.onExecute(), commands.turtleCommands.ForwardCommand.onExecute(), commands.turtleCommands.BackCommand.onExecute(), commands.variableCommands.GetVariableCommand.onExecute(), commands.viewCommands.SetBackgroundCommand.onExecute(), commands.viewCommands.SetPenColorCommand.onExecute(), commands.viewCommands.SetPenSizeCommand.onExecute(), commands.viewCommands.SetShapeCommand.onExecute(), commands.controlCommands.IfCommand.onExecute(), commands.controlCommands.RepeatCommand.onExecute(), commands.turtleCommands.SetPositionCommand.onExecute(), commands.turtleCommands.TowardsCommand.onExecute(), commands.controlCommands.IfElseCommand.onExecute(), commands.variableCommands.SetVariableCommand.onExecute(), commands.viewCommands.SetPaletteCommand.onExecute(), commands.controlCommands.DoCommand.onExecute(), commands.variableCommands.CreatedCommand.onExecute(), commands.controlCommands.ForCommand.onExecute(), commands.turtleCommands.AskWithCommand.onExecute(), commands.variableCommands.CreatedCommand.setNewVariables(), tests.AskWithTest.testAlwaysTrueAskWith(), tests.ExpressionCommandParseTest.testAnd(), tests.ExpressionCommandParseTest.testATan(), tests.ExpressionCommandParseTest.testCos(), tests.ExpressionCommandParseTest.testDifference(), tests.ExpressionCommandParseTest.testEqual(), tests.ExpressionCommandParseTest.testGreater(), tests.ExpressionCommandParseTest.testLess(), tests.ExpressionCommandParseTest.testMinus(), tests.ExpressionCommandParseTest.testNot(), tests.ExpressionCommandParseTest.testNotEqual(), tests.ExpressionCommandParseTest.testOr(), tests.ExpressionCommandParseTest.testPower(), tests.ExpressionCommandParseTest.testProduct(), tests.ExpressionCommandParseTest.testQuotient(), tests.ExpressionCommandParseTest.testRandom(), tests.ExpressionCommandParseTest.testRemainder(), tests.ExpressionCommandParseTest.testSin(), tests.ExpressionCommandParseTest.testSumParses(), tests.ExpressionCommandParseTest.testTan(), tests.AskTest.testThatAskCreatesTurtles(), commands.controlCommands.ContainerTest.testThatIfWorks(), commands.variableCommands.VariableCommandParseTest.testThatVariableIsGet(), tests.TurtleCommandsTest.testToParsing(), tests.ToCommandTest.testToParsing(), and tests.AskWithTest.testXCorAskWith().
int commands.BaseCommand.findIndexOfInnerListCommandEnd (String input) private
Definition at line 99 of file BaseCommand.java.
Referenced by commands.BaseCommand.splitByInnerListCommand().
String commands.BaseCommand.getLeftoverString ()
Definition at line 70 of file BaseCommand.java.
References commands.BaseCommand.myLeftoverString.
Referenced by commands.information.MapBasedUserDefinedContainer.getCreatedCommand(), commands.variableCommands.SetVariableCommand.parseArguments(), commands.expressionCommands.ExpressionCommand.parseArguments(), commands.controlCommands.IfCommand.parseArguments(), commands.controlCommands.IfElseCommand.parseArguments(), commands.controlCommands.RepeatCommand.parseArguments(), commands.ViewCommand.parseArguments(), commands.controlCommands.ForCommand.parseArguments(), and commands.turtleCommands.TurtleCommand.parseArguments().
BaseCommand commands.BaseCommand.getNextCommand () private
Definition at line 64 of file BaseCommand.java.
References commands.BaseCommand.myNextCommand.
Referenced by commands.BaseCommand.execute().
abstract Set<Class<? extends IInformationContainer> > commands.BaseCommand.getRequiredInformationTypes () abstract
Referenced by commandParser.CommandFactory.createCommand().
abstract double commands.BaseCommand.onExecute () throws BackendException abstract protected
Referenced by commands.BaseCommand.execute().
abstract void commands.BaseCommand.parseArguments (String userInput) throws BackendException abstract protected
Referenced by commands.BaseCommand.BaseCommand().
abstract void commands.BaseCommand.reset () abstract protected
Referenced by commands.BaseCommand.execute().
void commands.BaseCommand.setLeftoverCommands (String string) throws BackendException protected
Definition at line 74 of file BaseCommand.java.
References commandParser.CommandFactory.createCommand().
Referenced by commands.TurtleQuery.parseArguments(), commands.ViewQuery.parseArguments(), commands.turtleCommands.TellCommand.parseArguments(), commands.NumericalCommand.parseArguments(), commands.variableCommands.GetVariableCommand.parseArguments(), commands.turtleCommands.AskWithCommand.parseArguments(), commands.variableCommands.SetVariableCommand.parseArguments(), commands.controlCommands.IfElseCommand.parseArguments(), commands.controlCommands.IfCommand.parseArguments(), commands.expressionCommands.ExpressionCommand.parseArguments(), commands.turtleCommands.AskCommand.parseArguments(), commands.controlCommands.RepeatCommand.parseArguments(), commands.controlCommands.ToCommand.parseArguments(), commands.ViewCommand.parseArguments(), commands.controlCommands.ForCommand.parseArguments(), commands.turtleCommands.TurtleCommand.parseArguments(), commands.controlCommands.DoCommand.parseArguments(), and commands.variableCommands.CreatedCommand.parseArguments().
abstract void commands.BaseCommand.setRequiredInformation (Collection< IInformationContainer > containers) throws BackendException abstract
Referenced by commandParser.CommandFactory.createCommand().
String [] commands.BaseCommand.splitByInnerListCommand (String input) protected
Definition at line 83 of file BaseCommand.java.
References commands.BaseCommand.COMMAND_SEPARATOR, commands.BaseCommand.findIndexOfInnerListCommandEnd(), and commands.BaseCommand.startsWithCommandStartIndicator().
Referenced by commands.turtleCommands.TellCommand.parseArguments(), commands.turtleCommands.AskWithCommand.parseArguments(), commands.controlCommands.IfElseCommand.parseArguments(), commands.controlCommands.IfCommand.parseArguments(), commands.turtleCommands.AskCommand.parseArguments(), commands.controlCommands.RepeatCommand.parseArguments(), commands.controlCommands.ToCommand.parseArguments(), commands.controlCommands.ForCommand.parseArguments(), and commands.controlCommands.DoCommand.parseArguments().
boolean commands.BaseCommand.startsWithCommandStartIndicator (String input) protected
Definition at line 122 of file BaseCommand.java.
Referenced by commands.BaseCommand.splitByInnerListCommand().
Member Data Documentation
final String commands.BaseCommand.COMMAND_DELIMITER = "\\s+" protected
Definition at line 24 of file BaseCommand.java.
Referenced by commands.variableCommands.GetVariableCommand.parseArguments(), and commands.variableCommands.SetVariableCommand.parseArguments().
String commands.BaseCommand.COMMAND_END_INDICATOR = "listend" static protected
Definition at line 26 of file BaseCommand.java.
String commands.BaseCommand.COMMAND_INDICATOR = "liststart" static protected
Definition at line 25 of file BaseCommand.java.
String commands.BaseCommand.COMMAND_SEPARATOR = " " static protected
Definition at line 27 of file BaseCommand.java.
Referenced by commands.turtleCommands.TellCommand.parseArguments(), commands.BaseCommand.splitByInnerListCommand(), and commands.turtleCommands.MultipleTurtleCommand.storeFutureActiveIDs().
boolean commands.BaseCommand.myExpressionFlag private
Definition at line 23 of file BaseCommand.java.
String commands.BaseCommand.myLeftoverString = "" private
Definition at line 22 of file BaseCommand.java.
Referenced by commands.BaseCommand.getLeftoverString().
BaseCommand commands.BaseCommand.myNextCommand private
Definition at line 21 of file BaseCommand.java.
Referenced by commands.BaseCommand.getNextCommand().
final long commands.BaseCommand.serialVersionUID = 1L static private
Definition at line 20 of file BaseCommand.java.
String commands.BaseCommand.VARIABLE_INDICATOR = "variable" static protected
Definition at line 28 of file BaseCommand.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/commands/BaseCommand.java