slogo_team13: GUIFunctions.Undo Class Reference
GUIFunctions.Undo Class Reference
Public Member Functions
Undo (GridTracker grid)
void doAction ()
void doAction (List<?extends Number > newVal)
Public Member Functions inherited from GUIFunctions.BottomFunctions
BottomFunctions ()
Public Member Functions inherited from GUIFunctions.GridFunction
GridFunction ()
Private Member Functions
void undoLine (Turtle t)
Additional Inherited Members
Protected Attributes inherited from GUIFunctions.GridFunction
GridTracker allGrids
Detailed Description
Definition at line 10 of file Undo.java.
Constructor & Destructor Documentation
GUIFunctions.Undo.Undo (GridTracker grid)
Definition at line 11 of file Undo.java.
References GUIFunctions.GridFunction.allGrids.
Member Function Documentation
void GUIFunctions.Undo.doAction ()
Implements GUIFunctions.GUIFunction.
Definition at line 16 of file Undo.java.
References GUIFunctions.GridFunction.allGrids, View.GridTracker.getActiveGrid(), View.SingleGrid.getActiveTurtles(), View.SingleGrid.moveTurtle(), GUIFunctions.Undo.undoLine(), and View.SingleGrid.update().
void GUIFunctions.Undo.doAction (List<?extends Number > newVal)
Implements GUIFunctions.GUIFunction.
Definition at line 33 of file Undo.java.
void GUIFunctions.Undo.undoLine (Turtle t) private
Definition at line 27 of file Undo.java.
References GUIFunctions.GridFunction.allGrids, View.GridTracker.getActiveGrid(), turtle.Turtle.getPen(), and View.Pen.undo().
Referenced by GUIFunctions.Undo.doAction().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/GUIFunctions/Undo.java