slogo_team13: GUIFunctions.ToggleGridLines Class Reference
GUIFunctions.ToggleGridLines Class Reference
Public Member Functions
ToggleGridLines (GridTracker grid, int gridSize)
void doAction ()
void removeGridLines ()
void makeGridLines ()
void doAction (List<?extends Number > newVal)
Public Member Functions inherited from GUIFunctions.PersonalizeMenu
PersonalizeMenu ()
Public Member Functions inherited from GUIFunctions.GridFunction
GridFunction ()
Package Attributes
boolean showGridLines
int translate
Private Member Functions
void drawGridLine (int y, int x)
Private Attributes
Collection< Line > myGridLines
SingleGrid myGrid
Additional Inherited Members
Protected Attributes inherited from GUIFunctions.GridFunction
GridTracker allGrids
Detailed Description
Definition at line 12 of file ToggleGridLines.java.
Constructor & Destructor Documentation
GUIFunctions.ToggleGridLines.ToggleGridLines (GridTracker grid, int gridSize)
Definition at line 18 of file ToggleGridLines.java.
References GUIFunctions.GridFunction.allGrids.
Member Function Documentation
void GUIFunctions.ToggleGridLines.doAction ()
Implements GUIFunctions.GUIFunction.
Definition at line 26 of file ToggleGridLines.java.
References GUIFunctions.GridFunction.allGrids, View.GridTracker.getActiveGrid(), GUIFunctions.ToggleGridLines.makeGridLines(), and GUIFunctions.ToggleGridLines.removeGridLines().
void GUIFunctions.ToggleGridLines.doAction (List<?extends Number > newVal)
Implements GUIFunctions.GUIFunction.
Definition at line 63 of file ToggleGridLines.java.
void GUIFunctions.ToggleGridLines.drawGridLine (int y, int x) private
Definition at line 51 of file ToggleGridLines.java.
References View.SingleGrid.getMyHeight(), and View.SingleGrid.getMyWidth().
Referenced by GUIFunctions.ToggleGridLines.makeGridLines().
void GUIFunctions.ToggleGridLines.makeGridLines ()
Definition at line 43 of file ToggleGridLines.java.
References GUIFunctions.ToggleGridLines.drawGridLine(), View.SingleGrid.getMyHeight(), View.SingleGrid.getMyWidth(), and GUIFunctions.ToggleGridLines.translate.
Referenced by GUIFunctions.ToggleGridLines.doAction().
void GUIFunctions.ToggleGridLines.removeGridLines ()
Definition at line 38 of file ToggleGridLines.java.
Referenced by GUIFunctions.ToggleGridLines.doAction().
Member Data Documentation
SingleGrid GUIFunctions.ToggleGridLines.myGrid private
Definition at line 16 of file ToggleGridLines.java.
Collection<Line> GUIFunctions.ToggleGridLines.myGridLines private
Definition at line 15 of file ToggleGridLines.java.
boolean GUIFunctions.ToggleGridLines.showGridLines package
Definition at line 13 of file ToggleGridLines.java.
int GUIFunctions.ToggleGridLines.translate package
Definition at line 14 of file ToggleGridLines.java.
Referenced by GUIFunctions.ToggleGridLines.makeGridLines().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/GUIFunctions/ToggleGridLines.java