slogo_team13: commandParser.LanguageFileParser Class Reference
commandParser.LanguageFileParser Class Reference
Public Member Functions
LanguageFileParser (File fileName) throws BackendException
Map< String, String > extractFromLanguageFile (File file) throws BackendException
String translateUserInputIntoEnglish (String userInput) throws BackendException
String translateCommand (String command) throws BackendException
Private Member Functions
void setToPreviousMap ()
String translateByRegex (String rawCommand)
Private Attributes
Map< String, String > myUserInputToEnglishTranslationMap
Map< String, String > myPreviousTranslationMap
Static Private Attributes
static final String INVALID_COMMAND_MESSAGE = "Invalid command provided"
static final String COMMAND_INDICATOR = "[a-zA-Z_]+(\\?)?"
static final char COMMENT_INDICATOR = '#'
static String COMMAND_SEPARATOR = "\\s+"
static String SINGLE_SPACE_SEPARATOR = " "
Additional Inherited Members
Protected Member Functions inherited from commandParser.PropertiesFileReader
ResourceBundle getBundle (File file) throws MalformedURLException
String getFileNameWithoutExtension (File file)
Detailed Description
Author
Rahul Harikrishnan, Duke Kim, $cotty $haw
Definition at line 21 of file LanguageFileParser.java.
Constructor & Destructor Documentation
commandParser.LanguageFileParser.LanguageFileParser (File fileName) throws BackendException
Definition at line 25 of file LanguageFileParser.java.
References commandParser.LanguageFileParser.extractFromLanguageFile().
Member Function Documentation
Map<String, String> commandParser.LanguageFileParser.extractFromLanguageFile (File file) throws BackendException
Definition at line 36 of file LanguageFileParser.java.
References commandParser.PropertiesFileReader.getBundle(), commandParser.LanguageFileParser.myUserInputToEnglishTranslationMap, and commandParser.LanguageFileParser.setToPreviousMap().
Referenced by commandParser.LanguageFileParser.LanguageFileParser(), and communicator.MainController.loadLanguage().
void commandParser.LanguageFileParser.setToPreviousMap () private
Definition at line 62 of file LanguageFileParser.java.
References commandParser.LanguageFileParser.myPreviousTranslationMap.
Referenced by commandParser.LanguageFileParser.extractFromLanguageFile().
String commandParser.LanguageFileParser.translateByRegex (String rawCommand) private
Definition at line 98 of file LanguageFileParser.java.
Referenced by commandParser.LanguageFileParser.translateCommand().
String commandParser.LanguageFileParser.translateCommand (String command) throws BackendException
Definition at line 81 of file LanguageFileParser.java.
References commandParser.LanguageFileParser.translateByRegex().
Referenced by commandParser.LanguageFileParser.translateUserInputIntoEnglish().
String commandParser.LanguageFileParser.translateUserInputIntoEnglish (String userInput) throws BackendException
Definition at line 66 of file LanguageFileParser.java.
References commandParser.LanguageFileParser.translateCommand().
Referenced by commands.controlCommands.ContainerTest.processInput(), tests.AskTest.processInput(), tests.TurtleCommandsTest.processInput(), commands.variableCommands.VariableCommandParseTest.processInput(), tests.ToCommandTest.processInput(), tests.AskWithTest.processInput(), tests.ExpressionCommandParseTest.processInput(), and communicator.MainController.receiveCommand().
Member Data Documentation
final String commandParser.LanguageFileParser.COMMAND_INDICATOR = "[a-zA-Z_]+(\\?)?" static private
Definition at line 29 of file LanguageFileParser.java.
String commandParser.LanguageFileParser.COMMAND_SEPARATOR = "\\s+" static private
Definition at line 31 of file LanguageFileParser.java.
final char commandParser.LanguageFileParser.COMMENT_INDICATOR = '#' static private
Definition at line 30 of file LanguageFileParser.java.
final String commandParser.LanguageFileParser.INVALID_COMMAND_MESSAGE = "Invalid command provided" static private
Definition at line 23 of file LanguageFileParser.java.
Map<String, String> commandParser.LanguageFileParser.myPreviousTranslationMap private
Definition at line 34 of file LanguageFileParser.java.
Referenced by commandParser.LanguageFileParser.setToPreviousMap().
Map<String, String> commandParser.LanguageFileParser.myUserInputToEnglishTranslationMap private
Definition at line 33 of file LanguageFileParser.java.
Referenced by commandParser.LanguageFileParser.extractFromLanguageFile().
String commandParser.LanguageFileParser.SINGLE_SPACE_SEPARATOR = " " static private
Definition at line 32 of file LanguageFileParser.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/commandParser/LanguageFileParser.java