slogo_team13: View.Pen Class Reference
View.Pen Class Reference
Public Member Functions
Pen ()
String getPenColor ()
void changeThickness (Number howThick)
void setInitialPosition (Double x, Double y)
void setColor (String color)
void setBorderStyle (BorderStyle style)
Line undo ()
Line drawLine (double xPos, double yPos)
void setPenDown (boolean down)
boolean getPenDown ()
Private Member Functions
void setLineStyle (Line myLine)
Private Attributes
Stack< Line > myLines
String myColor
BorderStyle myStyle
int myThickness
boolean penDown
double startX
double startY
Detailed Description
Definition at line 17 of file Pen.java.
Constructor & Destructor Documentation
View.Pen.Pen ()
Definition at line 26 of file Pen.java.
Member Function Documentation
void View.Pen.changeThickness (Number howThick)
Definition at line 38 of file Pen.java.
Referenced by turtle.Turtle.setPenWidth().
Line View.Pen.drawLine (double xPos, double yPos)
Definition at line 61 of file Pen.java.
References View.Pen.setLineStyle().
Referenced by View.SingleGrid.keepTurtleInBounds().
String View.Pen.getPenColor ()
Definition at line 34 of file Pen.java.
References View.Pen.myColor.
boolean View.Pen.getPenDown ()
Definition at line 92 of file Pen.java.
References View.Pen.penDown.
Referenced by View.SingleGrid.keepTurtleInBounds().
void View.Pen.setBorderStyle (BorderStyle style)
Definition at line 49 of file Pen.java.
Referenced by turtle.Turtle.setPenBorderStyle().
void View.Pen.setColor (String color)
Definition at line 46 of file Pen.java.
Referenced by turtle.Turtle.setPenColor().
void View.Pen.setInitialPosition (Double x, Double y)
Definition at line 42 of file Pen.java.
Referenced by View.SingleGrid.addTurtle().
void View.Pen.setLineStyle (Line myLine) private
determines appearance of line such as color and thickness
Parameters
myLine
Definition at line 77 of file Pen.java.
References GUIFunctions.BorderStyle.getStyle().
Referenced by View.Pen.drawLine().
void View.Pen.setPenDown (boolean down)
Definition at line 89 of file Pen.java.
Referenced by View.SingleGrid.keepTurtleInBounds().
Line View.Pen.undo ()
Definition at line 52 of file Pen.java.
Referenced by turtle.Turtle.penUndo(), and GUIFunctions.Undo.undoLine().
Member Data Documentation
String View.Pen.myColor private
Definition at line 19 of file Pen.java.
Referenced by View.Pen.getPenColor().
Stack<Line> View.Pen.myLines private
Definition at line 18 of file Pen.java.
BorderStyle View.Pen.myStyle private
Definition at line 20 of file Pen.java.
int View.Pen.myThickness private
Definition at line 21 of file Pen.java.
boolean View.Pen.penDown private
Definition at line 22 of file Pen.java.
Referenced by View.Pen.getPenDown().
double View.Pen.startX private
Definition at line 23 of file Pen.java.
double View.Pen.startY private
Definition at line 24 of file Pen.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/View/Pen.java