slogo_team13: commands.turtleCommands.MultipleTurtleCommand Class Reference
commands.turtleCommands.MultipleTurtleCommand Class Reference abstract
Public Member Functions
MultipleTurtleCommand (String userInput, boolean isExpression) throws BackendException
List< Integer > getFutureActiveTurtleIDs ()
void setFutureActiveTurtleIDs (List< Integer > tempActiveTurtleIDs)
BaseCommand getInternalCommand ()
void setInternalCommand (BaseCommand internalCommand)
Public Member Functions inherited from commands.turtleCommands.TurtleCommand
TurtleCommand (String userInput, boolean isExpression) throws BackendException
Set< Class<?extends IInformationContainer > > getRequiredInformationTypes ()
void setRequiredInformation (Collection< IInformationContainer > containers)
Public Member Functions inherited from commands.BaseCommand
BaseCommand (String userInput, boolean isExpression) throws BackendException
double execute () throws BackendException
abstract Set< Class<?extends IInformationContainer > > getRequiredInformationTypes ()
abstract void setRequiredInformation (Collection< IInformationContainer > containers) throws BackendException
String getLeftoverString ()
Protected Member Functions
int findMax (List< Integer > list)
boolean isEven (int number)
int getArgumentCount ()
void addFutureActiveTurtleTurtles () throws BackendException
void storeFutureActiveIDs (String innerInput) throws BackendException
Protected Member Functions inherited from commands.turtleCommands.TurtleCommand
BaseTurtleContainer getTurtleContainer ()
BaseGridContainer getGridContainer ()
void parseArguments (String userInput) throws BackendException
BaseCommand[] getExpressionList ()
abstract int getArgumentCount ()
void reset ()
Protected Member Functions inherited from commands.BaseCommand
abstract double onExecute () throws BackendException
abstract void parseArguments (String userInput) throws BackendException
void setLeftoverCommands (String string) throws BackendException
String[] splitByInnerListCommand (String input)
boolean startsWithCommandStartIndicator (String input)
abstract void reset ()
Protected Attributes
BaseCommand myInternalCommand
List< Integer > myFutureActiveTurtleIDs
String[] myTurtleIDs
Protected Attributes inherited from commands.BaseCommand
final String COMMAND_DELIMITER = "\\s+"
Static Protected Attributes
static final String CONSTANT_INDICATOR = "constant"
static final String INVALID_ERROR_MESSAGE = "Malformed input for Turtle IDs"
static final String NO_SINGLE_ACTIVE_GRID = "Exactly one grid is not active"
static final String INVALID_SYNTAX_FOR_ID = "Invalid syntax for ID"
static final String INVALID_TURTLE_ID_NEGATIVE_VALUE = "Invalid Turtle ID: negative value"
Static Protected Attributes inherited from commands.BaseCommand
static String COMMAND_INDICATOR = "liststart"
static String COMMAND_END_INDICATOR = "listend"
static String COMMAND_SEPARATOR = " "
static String VARIABLE_INDICATOR = "variable"
Static Private Attributes
static final int EVEN_NUMBER_CHECKER = 2
Detailed Description
Author
Rahul Harikrishnan, Duke Kim, $cotty $haw
Definition at line 17 of file MultipleTurtleCommand.java.
Constructor & Destructor Documentation
commands.turtleCommands.MultipleTurtleCommand.MultipleTurtleCommand (String userInput, boolean isExpression) throws BackendException
Definition at line 29 of file MultipleTurtleCommand.java.
Member Function Documentation
void commands.turtleCommands.MultipleTurtleCommand.addFutureActiveTurtleTurtles () throws BackendException protected
Definition at line 69 of file MultipleTurtleCommand.java.
References View.Grid.addTurtle(), commands.information.BaseTurtleContainer.addTurtle(), commands.turtleCommands.MultipleTurtleCommand.findMax(), commands.information.BaseGridContainer.getActiveGrids(), commands.information.BaseTurtleContainer.getAllTurtlesByID(), commands.turtleCommands.MultipleTurtleCommand.getFutureActiveTurtleIDs(), commands.turtleCommands.TurtleCommand.getGridContainer(), commands.turtleCommands.TurtleCommand.getTurtleContainer(), and commands.information.BaseTurtleContainer.hardSetActiveTurtles().
Referenced by commands.turtleCommands.TellCommand.onExecute(), and commands.turtleCommands.AskCommand.onExecute().
int commands.turtleCommands.MultipleTurtleCommand.findMax (List< Integer > list) protected
Definition at line 34 of file MultipleTurtleCommand.java.
Referenced by commands.turtleCommands.MultipleTurtleCommand.addFutureActiveTurtleTurtles().
int commands.turtleCommands.MultipleTurtleCommand.getArgumentCount () protected
Definition at line 65 of file MultipleTurtleCommand.java.
List<Integer> commands.turtleCommands.MultipleTurtleCommand.getFutureActiveTurtleIDs ()
Definition at line 48 of file MultipleTurtleCommand.java.
References commands.turtleCommands.MultipleTurtleCommand.myFutureActiveTurtleIDs.
Referenced by commands.turtleCommands.MultipleTurtleCommand.addFutureActiveTurtleTurtles().
BaseCommand commands.turtleCommands.MultipleTurtleCommand.getInternalCommand ()
Definition at line 56 of file MultipleTurtleCommand.java.
References commands.turtleCommands.MultipleTurtleCommand.myInternalCommand.
Referenced by commands.turtleCommands.AskCommand.onExecute().
boolean commands.turtleCommands.MultipleTurtleCommand.isEven (int number) protected
Definition at line 44 of file MultipleTurtleCommand.java.
Referenced by commands.turtleCommands.TellCommand.parseArguments(), and commands.turtleCommands.MultipleTurtleCommand.storeFutureActiveIDs().
void commands.turtleCommands.MultipleTurtleCommand.setFutureActiveTurtleIDs (List< Integer > tempActiveTurtleIDs)
Definition at line 52 of file MultipleTurtleCommand.java.
void commands.turtleCommands.MultipleTurtleCommand.setInternalCommand (BaseCommand internalCommand)
Definition at line 60 of file MultipleTurtleCommand.java.
Referenced by commands.turtleCommands.AskCommand.parseArguments().
void commands.turtleCommands.MultipleTurtleCommand.storeFutureActiveIDs (String innerInput) throws BackendException protected
Definition at line 93 of file MultipleTurtleCommand.java.
References commands.BaseCommand.COMMAND_SEPARATOR, and commands.turtleCommands.MultipleTurtleCommand.isEven().
Referenced by commands.turtleCommands.AskCommand.parseArguments().
Member Data Documentation
final String commands.turtleCommands.MultipleTurtleCommand.CONSTANT_INDICATOR = "constant" static protected
Definition at line 19 of file MultipleTurtleCommand.java.
Referenced by commands.turtleCommands.TellCommand.parseArguments().
final int commands.turtleCommands.MultipleTurtleCommand.EVEN_NUMBER_CHECKER = 2 static private
Definition at line 18 of file MultipleTurtleCommand.java.
final String commands.turtleCommands.MultipleTurtleCommand.INVALID_ERROR_MESSAGE = "Malformed input for Turtle IDs" static protected
Definition at line 20 of file MultipleTurtleCommand.java.
Referenced by commands.turtleCommands.TellCommand.parseArguments().
final String commands.turtleCommands.MultipleTurtleCommand.INVALID_SYNTAX_FOR_ID = "Invalid syntax for ID" static protected
Definition at line 22 of file MultipleTurtleCommand.java.
final String commands.turtleCommands.MultipleTurtleCommand.INVALID_TURTLE_ID_NEGATIVE_VALUE = "Invalid Turtle ID: negative value" static protected
Definition at line 23 of file MultipleTurtleCommand.java.
Referenced by commands.turtleCommands.TellCommand.parseArguments().
List<Integer> commands.turtleCommands.MultipleTurtleCommand.myFutureActiveTurtleIDs protected
Definition at line 25 of file MultipleTurtleCommand.java.
Referenced by commands.turtleCommands.MultipleTurtleCommand.getFutureActiveTurtleIDs(), and commands.turtleCommands.TellCommand.parseArguments().
BaseCommand commands.turtleCommands.MultipleTurtleCommand.myInternalCommand protected
Definition at line 24 of file MultipleTurtleCommand.java.
Referenced by commands.turtleCommands.MultipleTurtleCommand.getInternalCommand().
String [] commands.turtleCommands.MultipleTurtleCommand.myTurtleIDs protected
Definition at line 26 of file MultipleTurtleCommand.java.
Referenced by commands.turtleCommands.TellCommand.onExecute(), and commands.turtleCommands.TellCommand.parseArguments().
final String commands.turtleCommands.MultipleTurtleCommand.NO_SINGLE_ACTIVE_GRID = "Exactly one grid is not active" static protected
Definition at line 21 of file MultipleTurtleCommand.java.
Referenced by commands.turtleCommands.TellCommand.parseArguments().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team13/repository/src/commands/turtleCommands/MultipleTurtleCommand.java